### ISSUE TITLE
Remove duplicate codes in CITEST_Loader

### ISSUE THREAD

**Issue by RodolfoSilva** [kenjis/ci-phpunit-test#10]
Most of the code in this class already exists in the parent class.

**Comment by kenjis** [comment]
It is intentionally. What's your problem?

**Comment by RodolfoSilva** [comment]
But this way this overriding the `{subclass_prefix}Loader.php`

**Comment by kenjis** [comment]
Now `MY_Loader` extends `CITEST_Loader`.

By the way, what do you do in MY_Loader?

**Comment by kenjis** [comment]
Now your MY_Loader can extends `CI_Loder` (replaeced version).

**Comment by RodolfoSilva** [comment]
Ok... close #10

**Comment by RodolfoSilva** [comment]
Ok... close #10
