### ISSUE TITLE
Custom exception handler not fired on unit test

### ISSUE THREAD

**Issue by pascencio** [kenjis/ci-phpunit-test#100]
Hi Kenjis,

I have a controllers that use some business logic, when an error happen it thrown an exception. In codeigniter I implement an exception handler with pre_controller hook and use  set_exception_handler sentence, this works perfectly in my app, but when I try test my code, the exception handler not catch the error.

In my tests the hooks are enabled and the hook is called, but the exception not is handled.

Do you have any idea?

Thanks!

**Comment by kenjis** [comment]
You should not have  business logic in your controllers. :-)

I have no idea about exception hander. I never use it by myself.
If you show sample code to reproduce your problem, I might see something.

**Comment by kenjis** [comment]
Oh my bad. You wrote *a controllers that use some business logic*. Sorry.

**Comment by pascencio** [comment]
I solved my problem with an try/catch and process the exception with my exception handler. Then I get the output and test with assertContaints.

```
try {
			$this->request('PUT', 'ShoppingCart/addProduct' , $payload);
		} catch (ServiceException $e) {
			$handler = new ExceptionHandler();
			$code = $e->getCode();
			$handler->handle_exceptions($e,TRUE);
			$output = ob_get_clean();
		}
		$this->assertContains("Transaction not found", $output);
	}
```
Thanks!
