### ISSUE TITLE
MonkeyPatch: patchMethod that return boolean not triggered

### ISSUE THREAD

**Issue by pascencio** [kenjis/ci-phpunit-test#101]
Hi Kenjis:

Me again. Sorry for my frequently questions, but I like your library and I'm using it in my development.
I have some models that returns boolean value and not are triggered from MonkeyPatch.

Any idea?

Thanks again!

**Comment by pascencio** [comment]
The problem disapear and I dont know why... Maybe some code in the cache folder... I dont know.

**Comment by kenjis** [comment]
@pascencio 

Monkey Patching always caches source files. But if you update time stamp of a original source file, the cache would be updated automatically. So normally you don't have to clear cache manually.

You can find cache files:
* `application/tests/_ci_phpunit_test/tmp/cache/src/`

If you get something wrong, check the cache file, or just remove `tmp/cache` folder.
