### ISSUE TITLE
Non-existent class: CI_Table

### ISSUE THREAD

**Issue by smaximiliano** [kenjis/ci-phpunit-test#102]
When I trying to assert:

`$output = $this->request('GET', 'user/index');`
`$this->assertContains('<div class="container">', $output);`

I am getting this error:

`Failed asserting that 'Non-existent class: CI_Table' contains "<div class="container">".`

I downloaded the ci-phpunit-test currrent version, and codeigniter 3. In the User controller I used 2 libraries, 1 loaded by codeigniter autoload and the other loaded through constructor.

In user/index method I only have one code line

`  function index(){
    $this->load_view('page');
  }`

Thank you!

**Comment by kenjis** [comment]
It seems CodeIgniter searches `CI_Table` class, but there is no such class.

**Comment by smaximiliano** [comment]
Exactly! There is anyone who know solve this problem?

**Comment by smaximiliano** [comment]
OMG! I resolved it! Searching I found that Codeigniter have a Table library... In my project, I have a Table library... Yes... I changed my user library name to "MyTable" and worked correctly... My bad...

**Comment by kenjis** [comment]
Oh! I've forgotten that library. https://www.codeigniter.com/user_guide/libraries/table.html
Anyway it is good to hear you solved it.

**Comment by smaximiliano** [comment]
I was hoping insults. I go and see your kind reply... you made my day! :D Thank you for everything!
