### ISSUE TITLE
External Redirect

### ISSUE THREAD

**Issue by hoersten** [kenjis/ci-phpunit-test#105]
I added pull request #104 to fix assertRedirect when you're redirecting to an external site.  Currently a controller with redirect('http://www.example.com') fails assertRedirect('http://www.example.com'), it's expecting something along the lines of http://localhost:8000/http://www.example.com.

There's also a corresponding pull request 4 on the test app ci-app-for-ci-phpunit-test

**Comment by kenjis** [comment]
Merged #104.

You don't have to post both PR and issue. Only PR is enough.
