### ISSUE TITLE
Doubling MY_* classes.

### ISSUE THREAD

**Issue by trungdq88** [kenjis/ci-phpunit-test#107]
Hi, can `ci-phpunit-test` doubling `MY_*` classes? I tried the following snippet but the error message say that it could not find the `logged_in` method.

        $this->request->setCallable(
            function ($CI) {
                // Get mock object
                $session = $this->getDouble(
                    'MY_Session', ['logged_in' => TRUE]
                );
                // Inject mock object
                $CI->session = $session;
            }
        );

Error message:

        Fatal error: Call to undefined method CI_Session::logged_in() in

Please help.

**Comment by kenjis** [comment]
> it could not find the logged_in method.

But the error says "undefined method **CI_Session::get_session_array()**".

Where did the error occurred?

**Comment by trungdq88** [comment]
Hi, it's my typo. The error message should be undefined method CI_Session::logged_in()
(Just tried to censor the method name)
Đinh Quang Trung

**Comment by kenjis** [comment]
Why `CI_Session::logged_in()`?
It seems `MY_Session` should be called, not `CI_Session`.

If you can show the cotroller code, it might help.

**Comment by trungdq88** [comment]
Test case:

    public function edit_request_song_without_login() {
        $this->request->setCallable(
            function ($CI) {
                // Get mock object
                $session = $this->getDouble(
                    'MY_Session', ['logged_in' => FALSE]
                );
                // Inject mock object
                $CI->session = $session;
            }
        );
        $output = $this->request('POST', ['Request_partial', 'edit'], [
            'song_id' => $this->song_id,
        ]);
        $this->assertEquals(lang('no.edit.permission'), trim($output));
    }

Controller code:

    class Request_partial extends Partial_Controller {
        ...
        public function edit($song_id = NULL) {
                call_user_func([$this, 'check_login']);
        }
        public function check_login() {
                $result = $this->session->logged_in();
        }
    }

`MY_Session.php`

class MY_Session extends CI_Session {
    function logged_in() {
        return ...
    }
}

Just want to mention that I use `call_user_func` in the edit method in `Request_partial` controller, is that ok?

**Comment by kenjis** [comment]
It seems your code should work, you can double your `MY_Session`.
But the error shows `$this->session` in the controller is an instance of `CI_Session`.
I don't know why it is NOT `MY_Session`.

Does your controller work fine when you access it via your web browser?

**Comment by trungdq88** [comment]
Thank you for such a wise advice. I was too confident to not to test in via my web browser, the `MY_Session.php` was not actually worked as the same way in CodeIgniter 3. I followed a workaround found on [StackOverflow](http://stackoverflow.com/questions/13300283/extending-the-session-library-in-codeigniter-3) to fix the `MY_Session`. Beside that, `ci-phpunit-test` is function normally.

We can close this issue now. Thank you.
