### ISSUE TITLE
Doesn't install with composer

### ISSUE THREAD

**Issue by eldan88** [kenjis/ci-phpunit-test#111]
Hi,

 Thank you for publishing this great package. I was trying to install it on composer and I got the following error messages

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - don't install kenjis/ci-phpunit-test v0.11.3|remove nikic/php-parser v0.9.5
    - don't install nikic/php-parser v0.9.5|don't install kenjis/ci-phpunit-test v0.11.3
    - don't install kenjis/ci-phpunit-test v0.11.3|don't install nikic/php-parser v0.9.5
    - Installation request for kenjis/ci-phpunit-test ^0.11.3 -> satisfiable by kenjis/ci-phpunit-test[v0.11.3].
    - Installation request for nikic/php-parser == 0.9.5.0 -> satisfiable by nikic/php-parser[v0.9.5].

Any idea on what to do?

**Comment by kenjis** [comment]
ci-phpunit-test includes `nikic/php-parser` 2.0.0.
It conflicts v0.9.5.

**Comment by eldan88** [comment]
I am not sure what you mean by that..What do you suggest on fixing it?

**Comment by kenjis** [comment]
You can't install both v0.9.5 and v2.0.0.
If you use ci-phpunit-test, you must remove v0.9.5.
