### ISSUE TITLE
Access test in sub-folders

### ISSUE THREAD

**Issue by eldan88** [kenjis/ci-phpunit-test#112]
Can you please tell me how can I access a test in a sub folder in the controllers folder. 
For example I have a file named Postproject_test in the client folder so the full path would be 

test/controller/client/Postproject_test

When I run this command phpunit  `phpunit client/postporject_test`

I get this

tests > phpunit client/postporject_test
Cannot open file "client/postporject/test.php"

I would really appreciate if you can help me figure this out. Thanks!

**Comment by kenjis** [comment]
~~~
$ cd application/tests/
$ phpunit controller/client/Postproject_test.php
~~~

**Comment by eldan88** [comment]
Thanks a lot for your response...and another question I have.. When I invoke a specific method in a controller it does not return anything. 

This is the code I am using

```

class Postproject_test extends TestCase {

		public $CI;


	public function setUp(){

        $this->CI = get_instance();

	}


	public function test_index()
	{

		$test= $this->request('GET', ['Home', 'test']);


		var_dump($test);




	}


}

```

When I run phpunit I get the following

/controllers/client/Postproject_test.php:29:
NULL

**Comment by kenjis** [comment]
Remove the `setUp()` method. You don't need it, because `$this->request()` does that.
But I don't know why you get null.

When you access it via your browser, what do you get?

**Comment by eldan88** [comment]
Nevermind there was a session redirect issue if the logged session if is not set. 
Another question I have is when use the $this->request() method on a specific method that return a value, the value doesn't return example

`class UnitTest extends CI_Controller {


    public function __construct(){
    
    parent::__construct();
   
    $this->load->helper(["html","url","form" ]);
    $this->load->model([""]);

    
    }
  public  function index(){
     return   "Hello world";


    }
}`


```

class Postproject_test extends TestCase {


	public function test_index()
	{

		$test = $this->request('GET', 'UnitTest/index');
		 $this->assertContains(
            'Hello world', $test
        );


	}

}

```

**Comment by kenjis** [comment]
Sorry, my previous comment was wrong. You don't have to remove the `setUp()`.

By the way, the test you wrote in your previous comment fails?
It seems it passes.
I don't know why it fails at all.

**Comment by eldan88** [comment]
There are a couple of problems I running into.

1. I am unable to select a specific file in a specific folder to run the test. For example. I am in the test folder. When I run  phpunit controller/client/Postproject_test.php, I get  a 
Cannot open file "controller/client/Postproject/test.php" error message

It will only work when I just run $ phpunit

2.The TestCase::request($method, $argv, $params = []) doesn't return the return values from a controller method for some reason when I set :
		$test = $this->request('GET', ["UnitTest","index2"]);
index2 return a string. But when I var_dump($test) it shows empty

3) The TestCase::request($method, $argv, $params = [])  is unable to find controllers in sub folders. For example when I type the shared folder before UnitTest the following 		$test = $this->request('GET', ["**shared/**UnitTest","index2"]);

The request method is unable to locate that file. I am not sure whats going...but if you can replicate the issue on your end just to see what I am talking about, then that would be awesome.

Thank you!

**Comment by eldan88** [comment]
Sorry I have updated the last comment. I figured out on of the issues. 

It seems to me that the $this->request method is only used for http requests... what methos can i use to invoke a method im a controller and just simply get the return  value?

**Comment by kenjis** [comment]
You can't do like this: `$this->request('GET', ["shared/UnitTest","index2"]);`
Because the first element is a classname. That is not a classname.

You can specify a URI as a string: `$this->request('GET', "shared/unittest/index2");`

**Comment by eldan88** [comment]
Thanks. But how do I assert against a return value on a specific method using  `$this->request()` ?

**Comment by kenjis** [comment]
I don't know why your 1. happens.

A test for controller is normally like this:
https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/v0.11.3/application/tests/controllers/sub/Sub_test.php

**Comment by eldan88** [comment]
Yes but if the index method only has a return (no echo statement) it does not output the value when running phpunit

**Comment by kenjis** [comment]
Oh, you're right. If a controller returns (not echo), you can't get the return value with using `$this->request()`.

**Comment by eldan88** [comment]
Okay then how can I retrieve the return value?

**Comment by kenjis** [comment]
~~~php
$c = new UnitTest();
$actual = $c->index();
$expected = 'Hello world';
$this->assertEquals($expeced, $actual):
~~~

But this approach is more difficult. Because controllers has many hidden dependencies.

By the way, how do you use the controller like that? CodeIgniter does not support controllers like that, I think.

**Comment by eldan88** [comment]
I don't use codeigniter like that. I am just finding a way to invoke certain methods in the controller and preforming assertion tests, based on the return values not on what gets echoed out using http...

When I instantiate a new class.. it applies CI_ to my all  libraries that get auto loaded, and its unable to find my libraries.. How do I find a work around for that?

**Comment by kenjis** [comment]
I don't understand what you do. How do you use the controller?

**Comment by eldan88** [comment]
Below is a sample method I would like unit test....in on my controllers. I want to see if asserts to true... how can would I be able to do that with the $this->request() method? 



 ```
 //Function only used for call back validation
    public function checkPassword($password){


        $email = $this->input->post("email");

        $result = $this->signin_model->verifyPublicUser($password,$email);

        /*The $result signin model queries both the client and freelancer table. Make sure that only client can succussfuly post
        projects and not freelancer*/
        if($result && $this->signin_model->last_table_queried != "freelancer"){
            return true;
        } else {
            $this->form_validation->set_message('checkPassword', 'Invalid username or password');
            return false;

        }

    }
```

**Comment by kenjis** [comment]
Thank you. I got your situation.
What is your exact error message?

**Comment by kenjis** [comment]
> how can would I be able to do that with the $this->request() method? 

You don't test the method with `$this->request()` directly. Because the method is not a real public method. It is used by another method in the controller. So you just test the real public mehtod, then you can test the callback method, too.

**Comment by eldan88** [comment]
I don't understand what you mean. Can you please give me a code example?

**Comment by kenjis** [comment]
I think the controller has a login action method. If so, you can write test for the login method with `$this->request()`.

The login method calls `checkPassword()`, so you can test it indirectly if you test the login method.

For example, see https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/master/application/controllers/Auth.php
`edit_user()` calls `_valid_csrf_nonce()`. So if you write test for `edit_user()`, you could also test `_valid_csrf_nonce()`.

**Comment by eldan88** [comment]
Yes I get that the index() method invokes the checkPassword method.. and if I do call the index() method through the the `$this->request() method ` how do I assert a true or false values from the checkPassword method if the `$this->request()` is purely based on HTTP?

**Comment by kenjis** [comment]
If you test like that, you can't assert the return value of checkPassword() directly.
You can arrange the conditions that `checkPassword()` returns true or false, and run `index()`.

Yes, this approach is not good when you really want to test `checkPassword()` directly.

**Comment by eldan88** [comment]
Yes but the index() method invokes a bunch of other code also not just  checkPassword.... i just dont understand how much you can possibly test using HTTP resonses... doesnt make any sense to me

**Comment by kenjis** [comment]
What do you exactly want to test?

**Comment by eldan88** [comment]
Well I want to mostly unit test.. so I just do as you mentioned..


$c = new UnitTest();
$actual = $c->index();
$expected = 'Hello world';
$this->assertEquals($expeced, $actual);

 So thats fine

**Comment by eldan88** [comment]
The one thing I am having a problem with is I have some libraries that get autoloaded in the config file.  The problem is that the files get autoloaded with the word "CI" prepended to the class and file name. Which causes an issues finding the autoloaded files

I even went ahead and changed the library name with the "CI" prepended but then I get the following error message  
Error: Class 'CI_CI_globalfuncsnippets' not found

the name of my library is CI_globalfuncsnippets

Can you please tell me how that can be fixed? 

Other then that everything works well. Thanks

**Comment by kenjis** [comment]
I need minimum sample code to reproduce your error.

It seems there is a problem around CodeIgniter's autoloading and ci-phpunit-test, but now I don't know why you get the error. That is, your error is unknown bug for me.

I have tests to use autoloading:

* https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/master/application/config/autoload.php#L63-L66
* https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/master/application/controllers/Ci_autoload_library.php

And the test passes.

**Comment by kenjis** [comment]
@eldan88 Maybe adding `$this->resetInstance()` in your `setUp()` solves your problem.
See https://github.com/kenjis/ci-phpunit-test/blob/master/docs/FunctionAndClassReference.md#testcaseresetinstance

**Comment by eldan88** [comment]
Still not working... Can you please add my on skype...It will be easier and much faster if I just quickly show you whats happening 

My skype id is eldan88
