### ISSUE TITLE
Can't find "system" folder. Using Windows 10.

### ISSUE THREAD

**Issue by Zetzumarshen** [kenjis/ci-phpunit-test#114]
Hello, I'm trying to install ci-phpunit-test using composer. The error log is this:

> Notice: Undefined offset: 1 in C:\xampp\htdocs\Projects\ProjectName\src\vendor\kenjis\ci-phpunit-test\install.php on line 14
> 
> Call Stack:
>     0.0002     120752   1. {main}() C:\xampp\htdocs\Projects\ProjectName\src\vendor\kenjis\ci-phpunit-test\install.php:0
> 
> Fatal error: Uncaught exception 'Exception' with message 'Can't find "system" folder.' in C:\xampp\htdocs\Projects\ProjectName\src\vendor\kenjis\ci-phpunit-test\Installer.php on line 40
> 
> Exception: Can't find "system" folder. in C:\xampp\htdocs\Projects\ProjectName\src\vendor\kenjis\ci-phpunit-test\Installer.php on line 40
> 
> Call Stack:
>     0.0002     120752   1. {main}() C:\xampp\htdocs\Projects\ProjectName\src\vendor\kenjis\ci-phpunit-test\install.php:0
>     0.0078     140768   2. Installer::install() C:\xampp\htdocs\Projects\ProjectName\src\vendor\kenjis\ci-phpunit-test\install.php:18
>     0.3781     141752   3. Installer::fixPath() C:\xampp\htdocs\Projects\ProjectName\src\vendor\kenjis\ci-phpunit-test\Installer.php:21

I'm running win10 at the project root. I've installed codeigniter successfully using [this guide](https://github.com/kenjis/codeigniter-composer-installer). 

Thank you in advance.

**Comment by lingfengchencn** [comment]
win10 is ok;
Do you  required CI first ?

**Comment by Zetzumarshen** [comment]
Here is the content of composer.json

`{
	"description" : "The CodeIgniter Application with Composer",
	"require": {
		"php": ">=5.3.2",
		"codeigniter/framework": "3.0.*"
	},
	"require-dev": {
		"mikey179/vfsStream": "1.1.*",
		"kenjis/ci-phpunit-test": "^0.12.0"
	}
}
`

**Comment by kenjis** [comment]
I don't know why you have the error.
Do you have `vendor/codeigniter/framework/system` folder?

**Comment by rpereira15** [comment]
Dude, you need to copy install.php and installer.php and paste on root folder.
After that, must edit linha on install.php "require __DIR__ . '/Installer.php';" for require './Installer.php';
So, when you do this, open terminal and execute command "php install.php"

For me worked fine!

**Comment by kenjis** [comment]
It seems you forgot to run `install.php`.

All you have to do is like this:
~~~
$ cd /path/to/codeigniter/
$ composer require kenjis/ci-phpunit-test --dev
$ php vendor/kenjis/ci-phpunit-test/install.php
~~~

See https://github.com/kenjis/ci-phpunit-test#installation

**Comment by kenjis** [comment]
If you still have questions, feel free to create another issue.

**Comment by Boffice** [comment]
This is old but still present for me i am adding this to custom folder ci_root/modules/facebook i did custom folder command 

``` php vendor/kenjis/ci-phpunit-test/install.php -a ../../application -p ../../ -t tests Fatal error: Uncaught Exception: Can't find "system" folder. in /var/www/html/modules/facebook/vendor/kenjis/ci-phpunit-test/lib/Installer.php:121```
