### ISSUE TITLE
Can I run phpunit automatically?

### ISSUE THREAD

**Issue by kentasaito** [kenjis/ci-phpunit-test#115]
In application/tests directory, phpunit worked manually.
`(PATH)/codeigniter/application/tests $ phpunit`
> PHPUnit 4.8.24 by Sebastian Bergmann and contributors.
> .....
> Time: 217 ms, Memory: 15.75Mb
> OK (5 tests, 5 assertions)

Then, I tried piece/stagehand-testrunner to run phpunit automatically.
`(PATH)/codeigniter/application/tests $ ../../vendor/bin/testrunner phpunit --phpunit-config=phpunit.xml -a .`
> Fatal error: Call to undefined function PhpParser\canonicalize() in /(PATH)/codeigniter/application/tests/_ci_phpunit_test/patcher/third_party/PHP-Parser/test/PhpParser/CodeTestAbstract.php on line 37
> 
> A PHP Error was encountered
> 
> Severity:    Error
> Message:     Call to undefined function PhpParser\canonicalize()
> Filename:    /(PATH)/codeigniter/application/tests/_ci_phpunit_test/patcher/third_party/PHP-Parser/test/PhpParser/CodeTestAbstract.php
> Line Number: 37
> 
> Backtrace:
> 
> Fatal error: Uncaught exception 'CIPHPUnitTestExitException' with message 'exit() called in _error_handler() function' in /(PATH)/codeigniter/vendor/codeigniter/framework/system/core/Common.php:635
Stack trace:
> #0 /(PATH)/codeigniter/vendor/codeigniter/framework/system/core/Common.php(635): exit__(1)
> #1 /(PATH)/codeigniter/vendor/codeigniter/framework/system/core/Common.php(692): _error_handler(1, 'Call to undefin...', '/(PATH)...', 37)
> #2 [internal function]: _shutdown_handler()
> #3 {main}
>   thrown in /(PATH)/codeigniter/vendor/codeigniter/framework/system/core/Common.php on line 635

Can I use testrunner with ci-phpunit-test or is there other way to run phpunit on CLI automatically?

p.s.
Is it related to issue #95 ?

**Comment by tangix** [comment]
Don't know if this is applicable to your setup, but I had the same problem getting it to run in JetBrains PHPStorm. After much trial-and-error, the following command line works running remote tests on Debian 8. I have almost success with Atlassian Bamboo with the same line, but the output generated doesn't seem to work yet...

/usr/bin/php (PATH)/application/tests/phpunit.phar --bootstrap (PATH)/application/tests/Bootstrap.php --configuration (PATH)/application/tests/phpunit.xml

**Comment by kentasaito** [comment]
tangiz.
Your command line worked at my environment.
Now, I can run the phpunit from any path (not only application/tests). 
Thanks.

But my purpose is:
- Some process keep watching the application-code and test-code.
- When code has been modified, the process run tests then notify the result of test.
- Without IDEs.

So I wonder that can I use the 'piece/stagehand-testrunner' (or something like that) on 'CodeIgniter' project.

Sorry for less Information.

**Comment by tangix** [comment]
Glad to hear it is working.
We are currently evaluating Atlassian Bamboo to monitor our SVN repo, check-out, test and package our application.

**Comment by kenjis** [comment]
Please try:
~~~
$ ../../vendor/bin/testrunner phpunit --phpunit-config=phpunit.xml -a controllers --watch-dir=../controllers
~~~

**Comment by tangix** [comment]
Just for reference - I got this working with Atlassian Bamboo. The configuration in Bamboo was pretty straight-forward once you got a hang of how Bamboo creates the working directories.
![2016-04-29_08-43-34](https://cloud.githubusercontent.com/assets/1013635/14909687/befc1d50-0de6-11e6-9a9e-d5d80741ce8d.png)

**Comment by kenjis** [comment]
This would be better:
~~~
$ ../../vendor/bin/testrunner phpunit --phpunit-config=phpunit.xml -a --test-file-pattern=_test\.php models libraries controllers
~~~

**Comment by kentasaito** [comment]
kenjis.
Your command line works perfectly.
That's what I want!
Thank you very much!!

For reference, I recode what I did:
```
$ git diff
```
```diff
diff --git a/composer.json b/composer.json
index 0e5fe02..e0d29ca 100644
--- a/composer.json
+++ b/composer.json
@@ -3,6 +3,8 @@
                "codeigniter/framework": "3.0.2",
                "components/jquery": "1.12.1",
                "twbs/bootstrap": "v3.3.6",
-               "kenjis/ci-phpunit-test": "v0.12.0"
+               "kenjis/ci-phpunit-test": "v0.12.0",
+               "piece/stagehand-testrunner": "v4.2.0",
+               "phpunit/phpunit": "4.8.24"
        }
 }
```
```
$ composer update
$ ./vendor/bin/testrunner compile -p vendor/autoload.php
$ cd application/tests
$ ../../vendor/bin/testrunner phpunit --phpunit-config=phpunit.xml -am --test-file-pattern=_test\.php models libraries controllers
```
Then, the bubble message said:
> Test Passed: OK (19 tests, 24 assertions)

I love testrunner's -m(--notify) opiton.

**Comment by kenjis** [comment]
Good to hear.
