### ISSUE TITLE
CI_URI::__construct() must be instance of CI_Config

### ISSUE THREAD

**Issue by rslhdyt** [kenjis/ci-phpunit-test#116]
Help, i got this error when running phpunit 4.7.6

> A PHP Error was encountered
> 
> Severity:    4096
> Message:     Argument 1 passed to CI_URI::__construct() must be an instance of CI_Config, none given, called in /(PATH)/application/tests/_ci_phpunit_test/replacing/core/Common.php on line 111 and defined
> Filename:    /(PATH)/system/core/URI.php
> Line Number: 99

**Comment by tangix** [comment]
If you are including your own configuration file, make sure a proper $config is set for ENVIRONMENT = "testing"
I stumbled on this because the testing sets ENVIRONMENT = "testing" and I only checked for "production" or "development"

**Comment by rslhdyt** [comment]
@tangix I've configuration files corectly in application/config/testing/config.php and ENVIRONMENT set to 'testing' but still got error :(

**Comment by tangix** [comment]
And you are 100% sure all config files sets $config when in testing?

**Comment by ytetsuro** [comment]
prease CodeIgniter directory 

> git checkout remotes/origin/3.0-stable

**Comment by kenjis** [comment]
`CI_URI::__construct()` in 3.0 has no params: https://github.com/bcit-ci/CodeIgniter/blob/3.0-stable/system/core/URI.php#L99
But 3.1.0-dev has a param: https://github.com/bcit-ci/CodeIgniter/blob/develop/system/core/URI.php#L99

Do you really want to use CodeIgniter 3.1.0-dev (`develop` branch)?
If so, at least you should update `CodeIgniter.php`: https://github.com/bcit-ci/CodeIgniter/commit/2a34081c5e1b8a86d2d3f87c3da69b9d580d6027

ci-phpunit-test does not support 3.1.0-dev now.

**Comment by rslhdyt** [comment]
I don't realize my codeigniter version, now the phpunit test is working. Thanks for you all.
