### ISSUE TITLE
How to patch DB update?

### ISSUE THREAD

**Issue by tangix** [kenjis/ci-phpunit-test#117]
The db object in CI must be the most complex construction with all the drivers etc. For my tests I'd simply want to patch the update() method to not do anything on the database - I am using mysql. I need all other functions (select, get, where etc) to work as they normal do to make sure all validations are working. I have managed to patch other functions to return the mock data I want  but I simply can't grasp the update() function.

Looking at the sample app I see many good examples, but not one patching update(). 
Could anyone point me in the right direction or is this simply not possible.

Thanks,
/Mattias

**Comment by kenjis** [comment]
> I have managed to patch other functions to return the mock data I want but I simply can't grasp the update() function.

Would you please show me what you did? Sample code?

There is two ways you go:
1. Use PHPUnit Mock Object
2. Use Monkey Patching

**Comment by tangix** [comment]
OK, I got it sort of working. Will try to boil down a better example with some code.
