### ISSUE TITLE
Unable to connect to db

### ISSUE THREAD

**Issue by eliaspn** [kenjis/ci-phpunit-test#118]
Hello,
i've followed the instructions but when i perform 'phpunit' in /test folder I get the following error: 
`A PHP Error was encountered
Severity: WarningMessage:  mysqli::real_connect(): (HY000/2002): No such file or directoryFilename: /Applications/XAMPP/xamppfiles/htdocs/barth/api/system/database/drivers/mysqli/mysqli_driver.phpLine Number: 135`
[....]
Database error: A Database Error Occurred
    Unable to connect to your database server using the provided settings.
    Filename: tests/_ci_phpunit_test/CIPHPUnitTest.php
    Line Number: 77
`
I don't understand how is this connected with my own configuration files, what should i do?

**Comment by kenjis** [comment]
The error message just tells can't connect to your database.
Please make sure you can connect to your database with your browser.
Check your `config/database.php`.

And when you run phpunit, the CI's environment is always `testing`.
See https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#testing-environment
So if you have `config/testing/database.php`, you must set it up correctly.

**Comment by kenjis** [comment]
If you still have questions, feel free to create another issue.

**Comment by ezequielprieto** [comment]
HI @kenjis i was having the same issue with the lastest versions of your work (0.13.0), Codeigniter 3.1.2 and PHPUnit (5.7.5).
The app works fine in the browser, I have checked all the config files but I was still getting this error, I solved the issue changing the **hostname** in the _config/database.php_ from **localhost** to **127.0.0.1**

Thanks for the great work!

**Comment by kenjis** [comment]
@ezequielprieto Thanks for your info!

**Comment by gregormck** [comment]
I get the same issue when I install CI via Composer using your secure folder structure https://packagist.org/packages/kenjis/codeigniter-composer-installer

However, if I download CI and manually create the secure folder structure myself (including the htaccess rewrite) and then install ci-phpunit-test via Composer then phpunit works as expected i.e. no database connection issues in CIPHPUnitTest.php
