### ISSUE TITLE
How to set session via Test controller ?

### ISSUE THREAD

**Issue by devkiran** [kenjis/ci-phpunit-test#121]
Hi,

I am new to PHPunit test, i have been looking to set session in my test controller , but its not working.

I need to mock my following session variables

``` php
$this->session->set_userdata('session', ['name' => 'John', 'id' => 1]);
$this->session->set_userdata('house_id', 100);
```

**Comment by kenjis** [comment]
Can you give me sample code (a controller and a test class) ?

**Comment by devkiran** [comment]
Yeah,

The user need to login before accessing that controller. 

```php
<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Brands extends User_Controller {

  	function __construct() {
        parent::__construct();

        // Load model
        $this->load->model('brand_model');
    }

  	public function all() {
        $this->is_ajax_request();

        $user_id = $this->get_user_id();

        // Get brands
        $brands = $this->brand_model->get_all_brands(['user_id' => $user_id]);

        $this->template->build('brands', ['brands' => $brands]);
    }
}
```

Test class
```php
<?php

class Brands_test extends TestCase {

    public function test_index() {

        $this->request->setCallable(
            function($CI) {
                $this->setSession($CI);
            }
        );

        $output = $this->request('GET', 'brands/index');
        $this->assertContains('All Brands', $output);
    }
}

```

**Comment by kenjis** [comment]
Don't you need to mock getting Session data? Not `set_userdata()`, but `userdata()
The code in

**Comment by devkiran** [comment]
@kenjis 

Okay, but where can i set the session data while running test ? I am testing a page where user authentication is must. Do i have to login via browser and get those session in TestCase ?

**Comment by kenjis** [comment]
If you just want to set session data, you don't have to make a mock.
You can set session data with using `$this->request->setCallable()`.

See:
* https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/master/application/controllers/Sessions.php#L25
* https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/master/application/tests/controllers/Sessions_test.php#L26
