### ISSUE TITLE
Using a test database.

### ISSUE THREAD

**Issue by lesfleurs** [kenjis/ci-phpunit-test#122]
Maybe i am going about this all wrong and should mock out my models instead. Currently I have  two databases on my local server, one which is being used just for tests, i have the following code in testcase.php that switches to the test database before running any tests.

```
class TestCase extends CIPHPUnitTestCase
{
    protected $_class = 'TestCase';
    protected function setUp()
    {
        $this->resetInstance();
        $this->CI->db->db_select($db);
        $this->db = $this->CI->db;
        $this->CI->load->library('environment');
        $this->testEnvironment = $this->CI->environment;
        $this->users = $this->testEnvironment->setUpTestEnvironment($this->CI);
    }
}
```

```
class Login_test extends TestCase
{
    protected $_class = 'Login_test';
    public function test_login()
    {
        $loginresponse = $this->request('POST', 'main/login', array(
            'email' => 'johndoe@galaxy.al',
            'password' => 'YodelGrate',
            'submit' => true));
        $this->assertRedirect('profile');
        $this->assertNotNull($this->CI->session->userdata('user_id'));
    }
}
```

test environment library creates test users and other required test stubs, i have a test that verifies that the users and other objects are created and that works fine, my issue is when i try to simulate a test to login using one of the test users, it appears that the default database is being used instead of the test database and the login test fails. Using a user in the default database causes the login test to pass however. How do i ensure that the test database is used throughout when the tests are running?

**Comment by esetnik** [comment]
The way I did it is to use the codeigniter environment config to specify which db config to use for tests. Then I tell phpunit to set the environment to TEST

**Comment by lesfleurs** [comment]
Can you specify the environment setting on the command line?

**Comment by esetnik** [comment]
Yes you can but I just put `define('ENVIRONMENT', 'testing');` in my `tests/Bootstrap.php` because I wanted to ensure that it wasn't possible to execute tests on the wrong environment.

**Comment by esetnik** [comment]
Make sure you fully consider the implications of allowing a user-configurable environment setting during test runs. You need to ensure that it's impossible for test users to be inserted into a dev or worse production database.

**Comment by kenjis** [comment]
Your way is too complex.
ci-phpunit-test always runs under `testing` environment by default:
https://github.com/kenjis/ci-phpunit-test/blob/master/application/tests/Bootstrap.php#L59

Probably all you need is to write database config file for testing environment. That is `config/testing/database.php`.

**Comment by lesfleurs** [comment]
I went ahead and created a database config for the testing environment to solve the problem.
