### ISSUE TITLE
Bump new version?

### ISSUE THREAD

**Issue by appleboy** [kenjis/ci-phpunit-test#123]
It doesn't work for the latest version so I must download the dev version as the following

```
cd ${CURRENT}/ci && composer require phpunit/phpunit:~4.0 --dev
cd ${CURRENT}/ci && composer require kenjis/ci-phpunit-test:dev-master --dev --prefer-dist
cd ${CURRENT}/ci && php vendor/kenjis/ci-phpunit-test/install.php
cd ${CURRENT}/ci && git checkout remotes/origin/3.0-stable
output "Testing CodeIgniter php unit test."
cd ${CURRENT}/ci/application/tests && ../../vendor/bin/phpunit
```

https://github.com/appleboy/codeigniter-docker/blob/master/testing.sh#L22-L27

**Comment by kenjis** [comment]
What's your problem?

**Comment by appleboy** [comment]
@kenjis Sorry for my fault. I reinstall again and it is working now.

**Comment by kenjis** [comment]
@appleboy No problem. I would like to release new version in this week.

**Comment by kenjis** [comment]
@appleboy I released the new version.

**Comment by appleboy** [comment]
@kenjis 👍
