### ISSUE TITLE
CIPHPUnitTestExitException not found on exit()

### ISSUE THREAD

**Issue by bobc82** [kenjis/ci-phpunit-test#126]
Hi,
I'm learning about ci-phpunit-test (version 10.0) on CodeIgniter Testing Guide, but i have an issue on testing a class where is a PHP exit(); construct.
I enabled MonkeyPatching on Bootstrap.php
The controller that i'm testing is this:

```
class Dbfixture extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
        if(is_cli() === false)
        {
            exit();
        }
    }
...
```

And that's the test function:

```
class Dbfixture_test extends TestCase
{
    public function setUp()
    {
        $this->resetInstance();
        $this->obj = new Dbfixture();
    }
    public function tearDown()
    {
        parent::tearDown();
        set_is_cli(true);
    }
    public function test_When_not_running_under_CLI_Then_exit()
    {
        set_is_cli(false);
        $obj=new Dbfixture();
    }
...
```

The problem is when i call exit(), the program returns me not errors, neither exception thrown. I use Windows 10.
PS: when i try to insert exit__() instead of exit(), it runs fine!

**Comment by kenjis** [comment]
> The problem is when i call exit(), the program returns me not errors, neither exception thrown. I use Windows 10.

Does you phpunit just abort?

**Comment by bobc82** [comment]
Thank you for your answer!

The output of php phpunit.phar is:
![phpunit_output](https://cloud.githubusercontent.com/assets/17877470/16337417/992d4968-3a15-11e6-8b58-8f1c9d2ebf5c.png)

It seems that just abort...

**Comment by kenjis** [comment]
It seems there is a bug which does not work monkey patching on Windows.
I don't use Windows. So to investigate I need to set up PHP environment on Windows.

**Comment by bobc82** [comment]
I testing in linux too and here the controller Dbfixture_test runs fine! Thank you again!

**Comment by kenjis** [comment]
I've confirmed that on Windows 10 *ExitPatcher* does not work.
PHPUnit just dies.

**Comment by kenjis** [comment]
@bobc82 
I pushed the fix to `master` branch: https://github.com/kenjis/ci-phpunit-test/commit/554f03c3fe5017c02ed9952593771564b2b657b3
It will be included in the next release version.

**Comment by bobc82** [comment]
Thank you very much for this!
