### ISSUE TITLE
Add http_method PUT for CIPHPUnitTestRequest request() method

### ISSUE THREAD

**Issue by ivankristianto** [kenjis/ci-phpunit-test#128]
In CIPHPUnitTestSuperGlobal
I add
```
public function set_PUT($params)
	{
		if (is_array($params))
		{
			if ($_SERVER['REQUEST_METHOD'] === 'PUT')
			{
				$_POST = $params;
			}
		}
	}
```

And in CIPHPUnitTestRequest, public function request($http_method, $argv, $params = [])
I add:
`$this->superGlobal->set_PUT($params);`

Hope this help others that use PUT method

**Comment by kenjis** [comment]
`$this->request()` has supported `PUT` method already.
See <https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/master/application/tests/controllers/api/Rest_test_test.php#L78>.

**Comment by ivankristianto** [comment]
Thanks Kenji,
I got it working.

**Comment by kenjis** [comment]
No problem.
