### ISSUE TITLE
Tests for redirect()

### ISSUE THREAD

**Issue by kenjis** [kenjis/ci-phpunit-test#13]
*CI PHPUnit Test* does not care about `redirect()` now.
But as a sample, `MY_url_helper.php` is included: https://github.com/kenjis/ci-phpunit-test/blob/master/application/helpers/MY_url_helper.php#L89

The current `redirect()` in `MY_url_helper.php` does nothing but return. It does not stop phpunit, but difficult to know `redirect()` called.

How about changing it like this?
~~~php
	if (ENVIRONMENT !== 'testing')
	{
		exit;
	}
	else
	{
		while (ob_get_level() > 1)
		{
			ob_end_clean();
		}

		throw new PHPUnit_Framework_Exception('Redirect to ' . $uri, $code);
	}
~~~

**Comment by RodolfoSilva** [comment]
This is a good idea.

**Comment by rochefort** [comment]
I think there is no choice. The `exit` is no good way in CI.

**Comment by kenjis** [comment]
Thank you guys for your comments.

I changed:
https://github.com/kenjis/ci-phpunit-test/compare/a246c66d1ff23710d0dceb5373c7ac726518ff67...a1fb69abaaae394c93ffbbeb191ed944f06d2401

**Comment by kenjis** [comment]
v0.2.0 including this released.
