### ISSUE TITLE
Risky Test: Test code or tested code did not (only) close its own output buffers

### ISSUE THREAD

**Issue by bobc82** [kenjis/ci-phpunit-test#131]
Hi, i'm implementing some tests for a site.
In a particular test, this result occurred:

```
{
    "event": "test",
    "suite": "Example_V_test",
    "test": "Example_V_test::test_3",
    "status": "error",
    "time": 13.469105958939,
    "trace": [
        {
            "file": "\/opt\/lampp\/htdocs\/buy\/application\/tests\/phpunit.phar",
            "line": 569,
            "function": "main",
            "class": "PHPUnit_TextUI_Command",
            "type": "::"
        }
    ],
    "message": "Risky Test: Test code or tested code did not (only) close its own output buffers",
    "output": ""
}R                                                                 3 / 3 (100%)

Time: 25.76 seconds, Memory: 59.25MB

There was 1 risky test:

1) Example_V_test::test_3
Test code or tested code did not (only) close its own output buffers

/opt/lampp/htdocs/buy/application/tests/phpunit.phar:569

OK, but incomplete, skipped, or risky tests!
```

My question is this: how to find the line of code that cause this 'issue'?

**Comment by kenjis** [comment]
The issue is in `Example_V_test::test_3`.
You have to see the test code and its tested code carefully.
And check `ob_get_level()`.

**Comment by mjeffe** [comment]
I'm having the same Risky test issue when testing my controllers.

```
public function test_when_you_access_help_you_see_help_in_title() {
    $output = $this->request('GET', 'help');
    $this->assertContains('<title>Help</title>', $output);
}

```
Basically, any time I try to call `$this->request()` I get the 

> 1) Help_test::test_when_you_accest_help_you_see_help_in_title
> Test code or tested code did not (only) close its own output buffers

Any ideas why? Also, this is a pretty old thread, but the title fit. Should I open a new issue?

**Comment by mjeffe** [comment]
Interesting...  If I run with `--stderr` Then the tests pass just fine (all green). 

 It also seems to have helped take care of another issue I've been plagued with since installing `ci-phpunit-test`, the "headers already sent" issue. For example:
```
 A PHP Error was encountered

Severity:    Warning
Message:     Cannot modify header information - headers already sent by (output started at phar:///..<snip>.../application/tests/phpunit.phar/phpunit/Util/Printer.php:114)
```
Is running `phpunit` with `--stderr` really the right approach? Do I have something missconfigured to cause these issues? I've had no trouble testing my models, only when trying to use `$this->request()` for testing controllers.

**Comment by kenjis** [comment]
It is an issue about *output buffering*.
Do you use `ob_start()` in your code?
See <http://php.net/manual/en/function.ob-start.php>.

the "headers already sent" error is because you try to send HTTP header after PHPUnit outputs something.
If you use `header()`, it is better to use `$this->output->set_header()` in stead of `header()`.
See <https://github.com/kenjis/ci-app-for-ci-phpunit-test/commit/e5609c358cbf60d3fbc16efd21d6ab65f249c6e6>.

**Comment by mjeffe** [comment]
I'm certainly not using `ob_start()` anywhere. I don't think I'm calling header, but I'll dig a bit more through our code.

Is it possible any of this is due to my setting ENVIRONMENT = 'development'? The way our dev/test/prod system is set up would make it difficult to use the 'testing' environment.

**Comment by kenjis** [comment]
> Is it possible any of this is due to my setting ENVIRONMENT = 'development'? The way our dev/test/prod system is set up would make it difficult to use the 'testing' environment.

Maybe. 

`testing` is hard coded in <https://github.com/kenjis/ci-phpunit-test/blob/master/application/tests/Bootstrap.php#L59>. You need to edit it if you want to change.

**Comment by mjeffe** [comment]
Yeah, that's where I changed it to `development`. I just wasn't sure if `ci-phpunit-test` cared one way or the other, and if changing it in `Bootstrap.php` was throwing something off. I've got a solution for now (`--stderr`) that seems to work. 

Thanks for your feedback.

**Comment by eshleebien** [comment]
This is usually due to uncleaned output buffer made by ```ob_start()``` call. 
ob_start is stackable so make sure to flush/clean those depending on how many you started.

**Comment by maxpaynestory** [comment]
https://github.com/kenjis/ci-phpunit-test/blob/3f2ea5cde0ee5814aa9402a5291772495f9250e0/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php#L325

I guess this is the cause of the problem.

**Comment by timur-safarov** [comment]
Just do that -
In this file ci-phpunit-test/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php

//$controller = new $class; //commented this string in function createAndCallController

	protected function createAndCallController($class, $method, $params, $call_display = true)
	{

		ob_start();

		$this->callHook('pre_controller');

		// Run callablePreConstructor
		if ($this->callablePreConstructors !== [])
		{
			foreach ($this->callablePreConstructors as $callable)
			{
				$callable();
			}
		}

		// Create controller
		if (CIPHPUnitTest::wiredesignzHmvcInstalled())
		{
			new CI();
		}
		//$controller = new $class; //commented this string
		$CI =& get_instance();

		// Set CodeIgniter instance to TestCase
		$this->testCase->setCI($CI);

		// Set default response code 200
		set_status_header(200);
		// Run callable
		if ($this->callables !== [])
		{
			foreach ($this->callables as $callable)
			{
				$callable($CI);
			}
		}

		$this->callHook('post_controller_constructor');

		// Call controller method
		call_user_func_array([$controller, $method], $params);

		$this->callHook('post_controller');

		if ($call_display && $this->callHook('display_override') === false)
		{
			$CI->output->_display();
		}

		$output = ob_get_clean();

		if ($output == '')
		{
			$output = $CI->output->get_output();
		}

		return $output;
	}

**Comment by sparthan15** [comment]
> https://github.com/kenjis/ci-phpunit-test/blob/3f2ea5cde0ee5814aa9402a5291772495f9250e0/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php#L325
> 
> I guess this is the cause of the problem.

Dude !!! This solution work like a charm for me !! Thanks, i ve commented the 325 line  and its Work !!

**Comment by IVNtech** [comment]
In my case, I got to CLOSE all the tags with @endsection

like this
```
 @section
// here all the data and then...
 @endsection

```
