### ISSUE TITLE
Remote phpunit testing

### ISSUE THREAD

**Issue by bobc82** [kenjis/ci-phpunit-test#135]
Is there a way to do phpunit testing on a remote (server) machine?

**Comment by rochefort** [comment]
You can use travisci and circleci.

- [Building a PHP project - Travis CI](https://docs.travis-ci.com/user/languages/php)
- [Sample circle.yml file - CircleCI](https://circleci.com/docs/config-sample/)

**Comment by kenjis** [comment]
@bobc82 What do you exactly want to do?
phpunit is a just command. You could run it on your server if you put your source code (and phpunit).

**Comment by bobc82** [comment]
I think this is what I try, and i found here... https://github.com/VisualPHPUnit/VisualPHPUnit/tree/2.x#web-server-configuration
