### ISSUE TITLE
How to deal with $map data, $this->returnValueMap()

### ISSUE THREAD

**Issue by huanhuashengling** [kenjis/ci-phpunit-test#136]
How can i use this test tool to deal with [Phpunit document Example 9.6](https://phpunit.de/manual/current/zh_cn/test-doubles.html)

May be we need add code to getDouble function.

**Comment by kenjis** [comment]
This tool is kind of wrapper for PHPUnit. So you can use the example as it is.

`getDouble()` function is just short-cut. See <https://github.com/kenjis/ci-phpunit-test/blob/master/docs/FunctionAndClassReference.md#testcasegetdoubleclassname-params-enable_constructor--false>. If you like it, please use it. If not, you don't have to use it at all.

If your question is how to write the example with using `getDouble()`, yes, you probably have to add code to it.

**Comment by kenjis** [comment]
@huanhuashengling If you use the current master branch, you can return closure.

See https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/master/application/tests/_tests/CIPHPUnitTestDouble_test.php#L20

So you can change the return value of the mocked method dynamically.
