### ISSUE TITLE
CIPHPUnitTestAutoloader::load is taking a very long time

### ISSUE THREAD

**Issue by AlbinoDrought** [kenjis/ci-phpunit-test#141]
Hello,

I have written some simple tests, and I was confused as to why they were taking so long to run. At first I thought it was my VM, so I ran them locally, but it was the same thing.

After profiling with xdebug (and getting an >2GB dump), I found out it was because of the following line in CIPHPUnitTestAutoloader::load

```
	$this->loadApplicationClass($class);
```

If this line is removed and the method is changed to the following:

```
	public function load($class)
	{
		if ($this->cache)
		{
			if ($this->loadFromCache($class))
			{
				return;
			}
		}

		$this->loadCIPHPUnitTestAliasClass($class);
		$this->loadCIPHPUnitTestClass($class);
	}
```

The test run-time is reduced from over 30s (for 4 tests, 27 assertions) to 11 seconds. Memory usage is greatly reduced as well.

I am using the popular HMVC extension, and I think this may have something to do with it. https://bitbucket.org/wiredesignz/codeigniter-modular-extensions-hmvc/src

The main memory hog is the `RecursiveDirectoryIterator`, with about 222,572 calls (and >18s of self-time)

The test suite continues working without that line, but I am not sure what else it breaks.

**Comment by kenjis** [comment]
`loadApplicationClass()` loads your class file in your application. By default, it searches the following directories:

```php
			$this->dirs = [
				APPPATH.'models',
				APPPATH.'libraries',
				APPPATH.'controllers',
				APPPATH.'modules',
				APPPATH.'hooks',
			];
```

With that method, we can write test code like this:
```php
$foo = new Some_library();
```

> The test suite continues working without that line, but I am not sure what else it breaks.

I don't know what happened to you.
If you don't need to autoload your application classes (probably you don't), the autoloader also does not need seek some class files.
If you need to autoload your application classes, your tests must fail with Fatal error. Because you removed the autoloader.

**Comment by AlbinoDrought** [comment]
Ah, it seems to be conflicting with "RedbeanPHP", specifically [Models and FUSE](http://www.redbeanphp.com/index.php?p=/models).

RedbeanPHP is looking for models named "Model_[tablename]", which don't exist (it just calls `class_exists` normally, afaik). For a simple test method, it attempted to load a model 4 times. For more extensive ones (with DB relations), it is attempting to load more than 16 times.

I'm assuming this makes the above code slow since it is searching _every_ directory for the class, but it will never be found.

Because of this, I'll leave the above code commented out locally. I have an autoloader setup already for most classes, and for the others I use the built-in CI loader. I'm just happy that the tests are much faster now.

Thanks for the quick help!

**Comment by kenjis** [comment]
> I'm assuming this makes the above code slow since it is searching every directory for the class, but it will never be found.

It makes sense. And you have your own autoloader, yes, you don't need `loadApplicationClass()`.

Just FYI, we can customize search paths with `CIPHPUnitTest::init()` in `Bootstrap.php`:
https://github.com/kenjis/ci-phpunit-test/blob/master/application/tests/Bootstrap.php#L361-L373
