### ISSUE TITLE
First time user, having some problems

### ISSUE THREAD

**Issue by AmitMY** [kenjis/ci-phpunit-test#142]
I followed the installation guide.
Then ran `phpunit`.

Here are the first 4 errors of the result. There are many more, but I think they happen because of these:

> PHP Notice:  Trying to get property of non-object in D:\xampp\htdocs\Extended-CI\application\tests\_ci_phpunit_test\replacing\core\Common.php on line 267
> 
> Notice: Trying to get property of non-object in D:\xampp\htdocs\Extended-CI\application\tests\_ci_phpunit_test\replacing\core\Common.php on line 267
>
> PHP Warning:  Creating default object from empty value in D:\xampp\htdocs\Extended-CI\application\tests\_ci_phpunit_test\replacing\core\Common.php on line 268
> 
> Warning: Creating default object from empty value in D:\xampp\htdocs\Extended-CI\application\tests\_ci_phpunit_test\replacing\core\Common.php on line 268

I did not change my "system" folder, and am using CI 3.0.6 (I can upgrade if needed, no problem)

**Comment by kenjis** [comment]
It seems you don't have the CodeIgniter super object at the time.
https://github.com/kenjis/ci-phpunit-test/blob/master/application/tests/_ci_phpunit_test/replacing/core/Common.php#L267

It is often because of your test code.
Would you show me your test code with the error?

**Comment by AmitMY** [comment]
I would, but I don't have any test code.
Just out of the box, installed it, and tried to execute "phpunit"

**Comment by kenjis** [comment]
It's weird. You should see the results in <https://github.com/kenjis/ci-phpunit-test#how-to-run-tests>.

I have no clue.

**Comment by AmitMY** [comment]
Thanks
I didn't know what to do, so now I test using mocha
Maybe someday if this resolves itself I'll try again
