### ISSUE TITLE
Dependency error with nikic/php-parser

### ISSUE THREAD

**Issue by fahadbillah** [kenjis/ci-phpunit-test#145]
For some other packages composer installed nikic/php-parser v1.4.1 
Now kenjis/ci-phpunit-test's composer want to remove it (v2.1.0) 
But it creates error
Please help me out solving this issue

`composer require kenjis/ci-phpunit-test --dev`

> Using version ^0.12.2 for kenjis/ci-phpunit-test
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - don't install kenjis/ci-phpunit-test v0.12.2|remove nikic/php-parser v1.4.1
>     - don't install nikic/php-parser v1.4.1|don't install kenjis/ci-phpunit-test v0.12.2
>     - don't install kenjis/ci-phpunit-test v0.12.2|don't install nikic/php-parser v1.4.1
>     - Installation request for kenjis/ci-phpunit-test ^0.12.2 -> satisfiable by kenjis/ci-phpunit-test[v0.12.2].
>     - Installation request for nikic/php-parser == 1.4.1.0 -> satisfiable by nikic/php-parser[v1.4.1].
> 
> Installation failed, reverting ./composer.json to its original content.

**Comment by kenjis** [comment]
Sorry, but it is typical conflict. ci-phpunit-test needs v2.1.0 (in some reasons, it is included in ci-phpunit-test), but your other package needs v1.4.1.

But if you don't use *Monkey Patching* in ci-phpunit-test, php-parser  v2.1.0 is not needed.
You have two choices:

1. install ci-phpunit-test via the Zip file.
2. fork ci-phpunit-test and create your custom package, and just remove the line for php-parser in composer.json. https://github.com/kenjis/ci-phpunit-test/blob/master/composer.json#L25-L27
