### ISSUE TITLE
Unit Test to check user permissions

### ISSUE THREAD

**Issue by lancomm** [kenjis/ci-phpunit-test#149]
Trying to figure out how to write a unit test for a CI project.

User logs in and they have access to navigation items based on their permission that are set in the database.
ie 
```php
if ($this->common->check_user_permission("user_id", "add_client")){
    echo "<a>Add Client</a>"
}
```

**Comment by kenjis** [comment]
What do you want to test?
What is your unit in the case?

**Comment by kenjis** [comment]
If you still have the problem, feel free to reopen or create an issue.
