### ISSUE TITLE
Suggestion: quiet mode for file copy

### ISSUE THREAD

**Issue by REJack** [kenjis/ci-phpunit-test#150]
Hi @kenjis,

it would be great to get a quiet mode for the install process on file copy.

regards REJack

**Comment by kenjis** [comment]
Thanks for your comment.
Is it annoying?

**Comment by REJack** [comment]
If i use it on my local environment yes sometimes, on Travis-CI not so much 😄 

I've create often custom Libraries for CI3 and in this projects my testing bash scripts/.travis.yml downloads a fresh CI3 and installs ci-phpunit-test on every test run.

**Comment by kenjis** [comment]
@REJack 

I added *silent mode* in `dev-master`.

```
$ php vendor/kenjis/ci-phpunit-test/install.php -s
```

```
$ php vendor/kenjis/ci-phpunit-test/update.php -s
```

**Comment by REJack** [comment]
Thanks works great 👍

**Comment by kenjis** [comment]
You are welcome!
