### ISSUE TITLE
If code-coverage takes forever to complete with phpunit 5.5 or later - here is a solution

### ISSUE THREAD

**Issue by tangix** [kenjis/ci-phpunit-test#152]
I noticed that code coverage takes forever to complete after upgrading to phpunit 5.6.7 from 4.x.
Googling around I found the solution by adding an argument to the whitelist tag in phpunit.xml: 
`<whitelist addUncoveredFilesFromWhitelist="false">`
This only runs code coverage on stuff that you actually test and sped up my code coverage from 15 minutes to 5 seconds.
I haven't noticed any other side-effects from setting this. The tests runs just fine using Atlassian Bamboo for DevOps.

**Comment by kenjis** [comment]
I don't know why your coverage reporting takes forever.
But if you change `addUncoveredFilesFromWhitelist` to `false"`, your coverage % would also change.

**Comment by tangix** [comment]
Yes, it is true that coverage will change, but when filtering phpunit is said to to only analyze files that we actually test and not include the whole CI framework, libraries etc.

See the discussions here: http://stackoverflow.com/questions/25682860/phpunit-very-slow-when-coverage-html
and here: https://phpunit.de/manual/current/en/code-coverage-analysis.html#code-coverage-analysis.whitelisting-files
