### ISSUE TITLE
Error run tests with v0.13.0

### ISSUE THREAD

**Issue by monstrodopantano** [kenjis/ci-phpunit-test#153]
My steps [PHPUnit 5.5.4 and CodeIgniter 3.2]
- Clone you project
- Download Codeigniter and copy folder ci-phpunit-test
- Run test

`/var/www/ci-phpunit-test/application/tests$ phpunit
PHP TypeError:  Argument 1 passed to CI_URI::__construct() must be an instance of CI_Config, none given, called in /var/www/ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/core/Common.php on line 111 in /var/www/ci-phpunit-test/system/core/URI.php on line 99
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:569
PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:115
PHP   4. PHPUnit_TextUI_Command->handleArguments() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:126
PHP   5. PHPUnit_TextUI_Command->handleBootstrap() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:731
PHP   6. PHPUnit_Util_Fileloader::checkAndLoad() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:902
PHP   7. PHPUnit_Util_Fileloader::load() phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php:38
PHP   8. include_once() phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php:56
PHP   9. CIPHPUnitTest::init() /var/www/ci-phpunit-test/application/tests/Bootstrap.php:361
PHP  10. require() /var/www/ci-phpunit-test/application/tests/_ci_phpunit_test/CIPHPUnitTest.php:76
PHP  11. load_class() /var/www/ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/core/CodeIgniter.php:305
PHP  12. CI_URI->__construct() /var/www/ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/core/Common.php:111

TypeError: Argument 1 passed to CI_URI::__construct() must be an instance of CI_Config, none given, called in /var/www/ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/core/Common.php on line 111 in /var/www/ci-phpunit-test/system/core/URI.php on line 99

Call Stack:
    0.0006     504520   1. {main}() /usr/local/bin/phpunit:0
    0.0551    8887488   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:569
    0.0551    8887600   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:115
    0.0551    8887600   4. PHPUnit_TextUI_Command->handleArguments() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:126
    0.0554    8899168   5. PHPUnit_TextUI_Command->handleBootstrap() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:731
    0.0554    8899168   6. PHPUnit_Util_Fileloader::checkAndLoad() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:902
    0.0555    8899264   7. PHPUnit_Util_Fileloader::load() phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php:38
    0.0556    8922312   8. include_once('/var/www/ci-phpunit-test/application/tests/Bootstrap.php') phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php:56
    0.0558    8941704   9. CIPHPUnitTest::init() /var/www/ci-phpunit-test/application/tests/Bootstrap.php:361
    0.0593    9609392  10. require('/var/www/ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/core/CodeIgniter.php') /var/www/ci-phpunit-test/application/tests/_ci_phpunit_test/CIPHPUnitTest.php:76
    0.0612    9801096  11. load_class() /var/www/ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/core/CodeIgniter.php:305
    0.0615    9860952  12. CI_URI->__construct() /var/www/ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/core/Common.php:111

Variables in local scope (#12):
  $config = *uninitialized*
  $protocol = *uninitialized*
  $uri = *uninitialized*

An uncaught Exception was encountered

Type:        TypeError
Message:     Argument 1 passed to CI_URI::__construct() must be an instance of CI_Config, none given, called in /var/www/ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/core/Common.php on line 111
Filename:    /var/www/ci-phpunit-test/system/core/URI.php
Line Number: 99

Backtrace:
	File: /var/www/ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/core/Common.php
	Line: 111
	Function: __construct

	File: /var/www/ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/core/CodeIgniter.php
	Line: 305
	Function: load_class

	File: /var/www/ci-phpunit-test/application/tests/_ci_phpunit_test/CIPHPUnitTest.php
	Line: 76
	Function: require

	File: /var/www/ci-phpunit-test/application/tests/Bootstrap.php
	Line: 361
	Function: init

	File: phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php
	Line: 56
	Function: include_once

	File: phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php
	Line: 38
	Function: load

	File: phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php
	Line: 902
	Function: checkAndLoad

	File: phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php
	Line: 731
	Function: handleBootstrap

	File: phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php
	Line: 126
	Function: handleArguments

	File: phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php
	Line: 115
	Function: run

	File: /usr/local/bin/phpunit
	Line: 569
	Function: main`

**Comment by kenjis** [comment]
See #140
It is not a bug in ci-phpunit-test. Because it does not support CI 3.2 (develop).
