### ISSUE TITLE
PHP 7.1 features not working with MonkeyPatch

### ISSUE THREAD

**Issue by DakuTree** [kenjis/ci-phpunit-test#154]
Trying to run tests with MonkeyPatch enabled against code using some of the new PHP 7.1 features causes tests to fail & throw PhpParser syntax errors.

This seems to be caused by ci-phpunit-test using an older version of PHP-Parser (2.1.0) which doesn't support 7.1. Updating to [3.0.x](https://github.com/nikic/PHP-Parser/releases) should resolve this.

**Comment by kenjis** [comment]
Yes.

**Comment by kenjis** [comment]
But, it requires PHP 5.5 or newer.
https://github.com/nikic/PHP-Parser/blob/master/UPGRADE-3.0.md#php-version-requirements

ci-phpunit-test still supports PHP 5.4.

**Comment by kenjis** [comment]
@DakuTree I've updated `dev-master` to support PHP 7.1 new syntax.
Would you please try it?

**Comment by DakuTree** [comment]
That seems to have fixed the issue. Thanks :+1:
