### ISSUE TITLE
How to know what version of ci-phpunit-test I am using?

### ISSUE THREAD

**Issue by trungdq88** [kenjis/ci-phpunit-test#155]
I am not using composer or any package manager, is there a way to check current version of ci-phpunit-test?

**Comment by kenjis** [comment]
No.

**Comment by trungdq88** [comment]
Is there an upgrade change log for backward incompatible changes?

**Comment by kenjis** [comment]
See https://github.com/kenjis/ci-phpunit-test/blob/master/docs/ChangeLog.md

**Comment by trungdq88** [comment]
Thank you.
