### ISSUE TITLE
Cannot declare class [class name], because the name is already in use

### ISSUE THREAD

**Issue by WangHaoming** [kenjis/ci-phpunit-test#159]
when I write two controller with the same Class name, for example: controller/a/Wellcome.php and controller/b/Wellcome.
And I test these two controllers at the same time with phpunit, I get this error. But when I test them individually like this:
```
phpunit controller/Wellcome_a_test.php
```
it works fine!

**Comment by WangHaoming** [comment]
I think there is a bug when ci-phpunit-test trying to load controller class with the same name.

**Comment by kenjis** [comment]
It is not a bug. It is a specification in PHP.
See <https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#controller-with-name-collision>.
