### ISSUE TITLE
You can't use `$this->curl` at the moment

### ISSUE THREAD

**Issue by naufalraihan** [kenjis/ci-phpunit-test#160]
when i test, this comes up:

> There was 1 error:
> 
> 1) Welcome_test::test_submit_masuk_nopassword
> LogicException: CodeIgniter instance is not instantiated yet. You can't use `$this->curl` at the moment. Please fix your test code.
> 
> C:\xampp\htdocs\ci\application\tests\_ci_phpunit_test\CIPHPUnitTestNullCodeIgniter.php:18
> C:\xampp\htdocs\ci\application\libraries\Rest.php:78
> C:\xampp\htdocs\ci\application\tests\_ci_phpunit_test\functions.php:79
> C:\xampp\htdocs\ci\application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php:73
> C:\xampp\htdocs\ci\application\tests\controllers\Welcome_test.php:16
> 
> FAILURES!
> Tests: 1, Assertions: 0, Errors: 1.

what cause this error? thanks

**Comment by kenjis** [comment]
It means your test code is something wrong.
You try to use a controller, but it is not instantiated at the moment.

**Comment by kenjis** [comment]
If you still have this issue, feel free to reopen.
