### ISSUE TITLE
"Trying to get property of non-object"

### ISSUE THREAD

**Issue by JoshHighland** [kenjis/ci-phpunit-test#162]
Vanilla install - (CI 3.1.2, php7)

running "phpunit" inside "application/tests/" throws these errors:

Notice: Trying to get property of non-object in /Users/joshhighland/dev/testproject/application/tests/_ci_phpunit_test/replacing/core/
Common.php on line 273

Warning: Creating default object from empty value in /Users/joshhighland/dev/testproject/application/tests/_ci_phpunit_test/replacing/
core/Common.php on line 274

**Comment by kenjis** [comment]
I can't reproduce.

Installation:
```
$ curl -L https://github.com/bcit-ci/CodeIgniter/archive/3.1.2.zip -o CodeIgniter-3.1.2.zip
$ unzip CodeIgniter-3.1.2.zip
$ curl -L https://github.com/kenjis/ci-phpunit-test/archive/v0.13.0.zip -o ci-phpunit-test-0.13.0.zip
$ unzip ci-phpunit-test-0.13.0.zip
$ cp -r ci-phpunit-test-0.13.0/application/tests/ CodeIgniter-3.1.2/application/tests
$ cd CodeIgniter-3.1.2
$ curl -L https://phar.phpunit.de/phpunit.phar -o phpunit.phar
```

Running tests:
```
$ php phpunit.phar -c application/tests/
PHPUnit 5.7.4 by Sebastian Bergmann and contributors.

Error:         No code coverage driver is available

...                                                                 3 / 3 (100%)

Time: 152 ms, Memory: 10.00MB
```

```
$ php -v
PHP 7.0.5 (cli) (built: Mar 31 2016 06:38:53) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by JoshHighland** [comment]
Thanks. I think I figured out the issue. 

I guess it wasn't as vanilla as I thought. I had created "/application/config/development/" and "/application/config/production/".

It looks like ci-phpunit only works with "/application/config/testing/" ?

**Comment by kenjis** [comment]
@JoshHighland 
> It looks like ci-phpunit only works with "/application/config/testing/" ?

Yes, it always runs on `testing` environment.
