### ISSUE TITLE
ci-phpunit-test does not working with phpunit 6.0

### ISSUE THREAD

**Issue by lanlin** [kenjis/ci-phpunit-test#168]
Hi,
   Thanks for your great work!

   After upgrade the phpunit from 5.x to the latest version (6.0),
   ci-phpunit-test not working any   more.

   Is there a plan for support this phpunit version?

**Comment by kenjis** [comment]
ci-phpunit-test 0.13.0 does not support PHPUnit 6.0.

Please use `dev-master`.
ci-phpunit-test 0.14.0 will be compatible with PHPUnit 6.0.
0.14.0 will be released soon.

See <https://github.com/kenjis/ci-phpunit-test/blob/master/application/tests/_ci_phpunit_test/ChangeLog.md>.

**Comment by kenjis** [comment]
I've released v0.14.0. Enjoy!
