### ISSUE TITLE
Create a page for this project using GitHub Page.

### ISSUE THREAD

**Issue by RodolfoSilva** [kenjis/ci-phpunit-test#17]
What do you think about this?

**Comment by kenjis** [comment]
It would be nice, but I don't know how well. PR is welcome.

**Comment by kenjis** [comment]
I made single page by GitHub Automatic Page Generator.
http://kenjis.github.io/ci-phpunit-test/

**Comment by rochefort** [comment]
I did not know `GitHub Automatic Page Generator` :+1: .
I tried my project.

**Comment by kenjis** [comment]
I didn't , too.
It is very easy to convert README.md to single page site.

https://github.com/blog/1081-instantly-beautiful-project-pages
