### ISSUE TITLE
Why tests folder inside of application folder?

### ISSUE THREAD

**Issue by kodmanyagha** [kenjis/ci-phpunit-test#171]
Why tests folder inside of application folder? When upload to ftp this is time waste. Tests folder must be outside of application folder.

**Comment by kenjis** [comment]
Well, I don't have a strong opinion, but it is because tests for application. 
https://github.com/fmalk/codeigniter-phpunit also has `application/tests` folder.

Why tests folder must be outside of application folder?

**Comment by cyberhorse** [comment]
In our case, tests are a separate git repository all together. 
We tried sym-linking into application/tests with no success:

`PHP Warning:  require(/home/test/phpunit/system/core/Common.php): failed to open stream: No such file or directory in /home/test/phpunit/application/tests/_ci_phpunit_test/CIPHPUnitTest.php on line 48`

I run it from the application/tests dir, which is not in /home/test/

**Comment by iamtomcat** [comment]
Did anyone figure this one out to be able to move the tests folder outside of the application folder?

**Comment by luckydonald** [comment]
@iamtomcat 
Yes. See #211.

**Comment by stebogit** [comment]
@kenjis I agree the tests outside `application/` would keep thinks cleaner, also in production.
I think though the real burden are the 900+ files inside the `tests/_ci_phpunit_test` folder. In my opinion they should be located inside the `vendor` folder, where all your app "tools" are installed, which typically you don't upload to your repo.
Also, why not having all the files needed, i.e. also the `_ci_phpunit_test` folder, already installed via composer?

**Comment by tangix** [comment]
Just want to chime in here. I actually think the tests belong with the application and makes project administration easier for our developers since they only need to handle one repo in git.
In our continuous integration system we have scripts stripping out the tests directory when producing the artifact. 
Bottom line: we like that all test-related files are in one location, makes it easy to share among developers and easy to strip when building a release.
:-)

**Comment by kenjis** [comment]
@stebogit Yes, you are right. But to support users which does not use Composer, ci-phpunit-test has the `tests/_ci_phpunit_test`.

I recommend you use symlink for `_ci_phpunit_test` (if you do not use Windows) like this:
https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/master/application/tests/_ci_phpunit_test

The next release will be in this November.

**Comment by stebogit** [comment]
@kenjis so if you use composer you don't need to run
`$ php vendor/kenjis/ci-phpunit-test/install.php`?
I notice it seems like the same `_ci_phpunit_test` is actually inside the `vendor/kenjis/` folder, should I basically use that and remove the one inside `application/tests`?

I use MAC, but I don't know what a symlink is... 😞

**Comment by kenjis** [comment]
@stebogit 
Yes.

How to:
```
$ cd application/tests
$ rm -rf _ci_phpunit_test
$ ln -s ../../vendor/kenjis/ci-phpunit-test/application/tests/_ci_phpunit_test/ .
```

**Comment by stebogit** [comment]
Great! Thanks @kenjis, maybe you could add this step in the docs.

**Comment by kenjis** [comment]
Now you can specify custom test directory. See #362
