### ISSUE TITLE
PHP Fatal error:  Cannot redeclare autoloadfunctionci()

### ISSUE THREAD

**Issue by caisaroentoro** [kenjis/ci-phpunit-test#173]
adding this function to config.php: 

spl_autoload_register('autoloadfunctionci');

function autoloadfunctionci($class) {
    if (strpos($class, 'CI_') !== 0) {
        include_once( APPPATH . 'core/' . $class . '.php' );
    }
}

resulting error: 
A PHP Error was encountered

Severity:    Compile Error
Message:     Cannot redeclare autoloadfunctionci() (previously declared in D:\web\instapost\application\config\config.php:6)
Filename:    D:\web\instapost\application\config\config.php
Line Number: 10

**Comment by kenjis** [comment]
Probably the `config.php` is loaded multiple times. When you run via your web browser, CI runs in single process. But in phpunit, you run CI multiple times in a single process.

In that case, add the `if` statement like in `Common.php`:
```php
if ( ! function_exists('autoloadfunctionci'))
{
    ...
}
```

**Comment by caisaroentoro** [comment]
Where should I put this code
```
if ( ! function_exists('autoloadfunctionci'))
{
}
```
in `Common.php`

**Comment by kenjis** [comment]
No, no. Not in `Common.php`. I mean in `config.php` like this:
```php
if ( ! function_exists('autoloadfunctionci'))
{
    function autoloadfunctionci($class) {
        if (strpos($class, 'CI_') !== 0) {
            include_once( APPPATH . 'core/' . $class . '.php' );
        }
    }
}
```

**Comment by caisaroentoro** [comment]
Thank you, it's working now

**Comment by kenjis** [comment]
No problem.

**Comment by wawire** [comment]
spl_autoload_register(function ($class) {
    if (substr($class, 0, 3) !== 'CI_') {
        if (file_exists($file = APPPATH . 'libraries/' . $class . '.php')) {
            include $file;
        }
    }
