### ISSUE TITLE
'PHPUnit_Framework_TestCase' not found

### ISSUE THREAD

**Issue by christiandr1** [kenjis/ci-phpunit-test#174]
When I run phpunit on console it's well, but when I try to run it by PHPStorm I get the next error.

`C:\xampp\php\php.exe C:\bin\phpunit.phar --no-configuration C:\xampp\htdocs\CodeIgniter\application\tests\ --teamcity

Testing started at 5:21 PM ...

PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in C:\xampp\htdocs\CodeIgniter\application\tests\_ci_phpunit_test\patcher\third_party\PHP-Parser-2.1.1\test\PhpParser\AutoloaderTest.php on line 10

PHP Stack trace:
PHP   1. {main}() C:\bin\phpunit.phar:0
PHP   2. PHPUnit\TextUI\Command::main() C:\bin\phpunit.phar:465
PHP   3. PHPUnit\TextUI\Command->run() phar://C:/bin/phpunit.phar/phpunit/TextUI/Command.php:136
PHP   4. PHPUnit\Runner\BaseTestRunner->getTest() phar://C:/bin/phpunit.phar/phpunit/TextUI/Command.php:159
PHP   5. PHPUnit\Framework\TestSuite->addTestFiles() phar://C:/bin/phpunit.phar/phpunit/Runner/BaseTestRunner.php:65
PHP   6. PHPUnit\Framework\TestSuite->addTestFile() phar://C:/bin/phpunit.phar/phpunit/Framework/TestSuite.php:400
PHP   7. PHPUnit\Util\Fileloader::checkAndLoad() phar://C:/bin/phpunit.phar/phpunit/Framework/TestSuite.php:327
PHP   8. PHPUnit\Util\Fileloader::load() phar://C:/bin/phpunit.phar/phpunit/Util/Fileloader.php:39
PHP   9. include_once() phar://C:/bin/phpunit.phar/phpunit/Util/Fileloader.php:55
`

**Comment by kenjis** [comment]
I don't know how to use it in PhpStorm. But why do you add `--no-configuration` option?

**Comment by christiandr1** [comment]
`--no-configuration` is generated by IDE PhpStorm :(

**Comment by tangix** [comment]
Test using "Defined in configuration file" option in PHPStorm and set Custom Directory to the tests directory.
Works for me in PHPStorm 2016.3.3

**Comment by christiandr1** [comment]
yes, I do it, but now a get the next error:
`Class 'PhpParser\NodeAbstract' not found`

**Comment by tangix** [comment]
OK, I don't know enough to troubleshoot this, but I can share my setup.
First off - I am using PHPunit 5.6.7 I had problems with newer 5.7 versions. I renamed it to be phpunit.phar (removing the -5.6 that confused PHPStorm). Also, I am not using the latest version of kenjis' testing framework (I don't know how to check which version I'm using). Downloaded about two months ago.

The Run/Test project setting is pure standard with the setting "Defined in configuration file" selected and using the tests directory for working directory.

I don't know if this will help you get it working or not. Having a working test library is really valuable so I wish you all the best.

**Comment by christiandr1** [comment]
I, am using PHP version 7.1 and the lastest ci_phpunit_test:

`A PHP Error was encountered`

`Severity:    Error`
`Message:     Class 'PhpParser\NodeAbstract' not found`
`Filename:    C:\xampp\htdocs\CodeIgniter\application\tests\_ci_phpunit_test\patcher\third_party\PHP-Parser-2.1.1\test\PhpParser\NodeAbstractTest.php`
`Line Number: 5`

**Comment by tangix** [comment]
OK, not much I can help with then. Hopefully someone else will be able to find the problem.

**Comment by christiandr1** [comment]
Hey thanks, now I found the solution for this issue using PhpStorm, but it's run well when I specify a class for test.

**Comment by kenjis** [comment]
I configured like this:
![170318-0001](https://cloud.githubusercontent.com/assets/87955/24071684/6ff4d844-0c1b-11e7-8a2d-627e46ef8ad5.png)

And I was able to run phpunit, but `Test framework quit unexpectedly`:
![170318-0002](https://cloud.githubusercontent.com/assets/87955/24071685/72a8705a-0c1b-11e7-96e0-6af2d4b0b285.png)

```
/usr/local/Cellar/php70/7.0.5/bin/php /private/var/folders/ts/j0ms4n2x52l3wg363x_g623h0000gn/T/ide-phpunit.php --configuration /Users/kenji/work/codeigniter/ci-app-for-ci-phpunit-test/application/tests/phpunit.xml
Testing started at 20:40 ...
#!/usr/bin/env php
PHPUnit 6.0.6 by Sebastian Bergmann and contributors.

...............................................................  63 / 207 ( 30%)
............................................................... 126 / 207 ( 60%)
............................................................... 189 / 207 ( 91%)
..................                                              207 / 207 (100%)

Time: 17.97 seconds, Memory: 40.50MB

OK (207 tests, 309 assertions)

Generating code coverage report in Clover XML format ... done

Generating code coverage report in HTML format ... done

Process finished with exit code 0
```
