### ISSUE TITLE
Moving tests folder out of application folder

### ISSUE THREAD

**Issue by MasonFI** [kenjis/ci-phpunit-test#175]
Edit: Modified my question, code should be ok. Problem seems to be that Monkey Patching is not working, so Upload test uses Core Upload library, not the one that came with this library.

I moved /application/tests to /tests. Monkey patchin seems to be not working. Is the Bootstrap.php only place where modifications are needed, or are there some other files also?

**Comment by MasonFI** [comment]
Update: Monkey Patching seems to work because exit exceptions are converted. What am I missing here? The example testing app has no specific configuration for monkey patching the upload -library?

tmp folder contains cache/src/tests/_ci_phpunit_test/replacing/core and cache/src/tests/_ci_phpunit_test/replacing/helpers but no cache/src/tests/_ci_phpunit_test/replacing/libraries. Is that ok?

**Comment by kenjis** [comment]
What's your exact problem? How to reproduce it?

**Comment by MasonFI** [comment]
Solved it by installing this library again, so that the tests folder is inside application. works now.
