### ISSUE TITLE
How to pass credentials when using basic authentication

### ISSUE THREAD

**Issue by MasonFI** [kenjis/ci-phpunit-test#177]
Im trying to test my CI Rest Server which has authentication on.

Auth source is library and I have a custom class + function which checks if credentials are ok. So basically its basic authentication.

How do I write tests for these kind of situations? There is example for Ion Auth, but not for basic auth...

**Comment by kenjis** [comment]
How about setting `$_SERVER` in your test code?

```php
$_SERVER['PHP_AUTH_USER'] = 'admin':
$_SERVER['PHP_AUTH_PW']   = 'passwd':
```

**Comment by MasonFI** [comment]
Yes those did work, thanks!
