### ISSUE TITLE
Session in constructor

### ISSUE THREAD

**Issue by paulzhen** [kenjis/ci-phpunit-test#183]
Hello I am new in ci phpunit test,

Could you help me to find out how to set session in ci-phpunit-test in function __construct variable?

Thank you a lot.

**Comment by kenjis** [comment]
Could you show me sample production code and its test code?
I don't understand what you want to do.

**Comment by paulzhen** [comment]
class Sessions extends CI_Controller
{
	public function __construct()
	{
		parent::__construct();
		$this->load->library('session');
		echo $this->session->name;
	}
}

class Sessions_test extends TestCase
{
	public function test_logged_in()
	{
		$this->request->setCallable(
			function ($CI) {
				$CI->session->name = 'Kenji';
				$CI->session->age = '23';
				$CI->session->id = 'kenjis';
			}
		);
		$output = $this->request('GET', 'sessions/logged_in');
		$expected = 'Kenji';
		$this->assertEquals($expected, $output);
	}
}

This will return false.

How could I create unit test for class Sessions_test if my session manipulation in constructor?

Thanks @kenjis

**Comment by kenjis** [comment]
You can't use `setCallable()`, because the code will be called after the controller instantiation.
Use `setCallablePreConstructor()` and `load_class_instance()`instead.

See <https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#inject-mocks-into-controller-constructors>.

**Comment by paulzhen** [comment]
Appologize me for my unknown of setting setCallablePreConstructor().
How could I set session of name, age, id as shown above question with $this->getDouble.
----------------------------------------------------------------------
Example
At the Test code:
		$this->request->setCallablePreConstructor(
			function () {
				// Get mock object
				$auth = $this->getDouble(
					'Ion_auth', ['logged_in' => TRUE]
				);
				// Inject mock object
				load_class_instance('ion_auth', $auth);
			}
		);
At the production code :
		$this->ion_auth->logged_in(); will give value of TRUE
-------------------------------------------------------------------------
As I wish to have in production code:
		$this->session->name or $_SESSION['name'] will give value of Kenji
		$this->session->age or $_SESSION['age'] will give value of 23
		$this->session->id or $_SESSION['id'] will give value of kenjis

How could I have it on my Test code?

Thanks @kenjis

**Comment by kenjis** [comment]
How about this?
```php
	public function test_logged_in()
	{
		$this->request->setCallablePreConstructor(
			function () {
				$session = new MY_Session();
				$session->name = 'Kenji';
				$session->age = '23';
				$session->id = 'kenjis';

				load_class_instance('session', $session);
			}
		);
		$output = $this->request('GET', 'sessions/logged_in');
		$expected = 'Kenji';
		$this->assertEquals($expected, $output);
	}
```

**Comment by daycry** [comment]
Hello,

If I use this code PHPUnit return an error that class MY_Session doen't exists.

I try to load the class in the controller test but I get this message:

LogicException: CodeIgniter instance is not instantiated yet. You can't use `$this->output` at the moment. Please fix your test code.

My code is:

`public function setUp()
    {
        $this->_doctrine = $this->newLibrary( 'doctrine' );
        //$this->request->enableHooks();
    }

public function test_change_language()
{   
    $this->request->setCallablePreConstructor(
        function () {
            $session = new MY_Session();
            $session->logged_in = TRUE;
            $session->uUsS = 'username';
            $session->rol = 'Rol';

            load_class_instance('session', $session);
        }
    );
    $this->ajaxRequest('POST', 'user/setLanguage', [ 'language' => 'ca' ] );
}`

I haven't assertion because I try to log a text with session values in my program, later I will add an assertion for complete the test.

Can you help me?

Thanks

**Comment by daycry** [comment]
My problem is solved.

Thanks!
