### ISSUE TITLE
Cannot redeclare class API in /var/www/html/application/libraries/Api.php

### ISSUE THREAD

**Issue by ncminh** [kenjis/ci-phpunit-test#185]
Hi,
I have a class call API (not extend from any other class) declared and put in **application/libraries** folder. And when I run phpunit globally (I have phpunit installed globally on my machine) in _/var/www/html/application/tests_ , I got the error like the title, and the Fatal Error message like below:
**Fatal error: Uncaught exception 'CIPHPUnitTestExitException' with message 'exit() called in _error_handler() function' in /var/www/html/system/core/Common.php on line 631**
I spent two days for this but I still cannot address this issue.I found the issue #173 somehow like mine but in that case, the issue is from function call, and in my case it's a class. I have my class loaded in autoload.php file.
 Please help me with this, thanks a lot.

**Comment by kenjis** [comment]
`Cannot redeclare class API` means you load the class file more than once.
If you have code like `require 'Api.php'`, you probably have to change it to `require_once 'Api.php'`.

**Comment by ncminh** [comment]
Thank you @kenjis , I used **$autoload['libraries'] = array('api')** in my application/config/autoload.php, after changing the autoload.php file to _require_once APPPATH . '/libraries/API.php'_ , it works perfectly. ^_^

**Comment by kenjis** [comment]
@ncminh No problem.

When you run tests, you run your CodeIgniter many times in a single process.
It is the one of the biggest difference between accessing CI via web and running tests.
