### ISSUE TITLE
Exception: Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by ODelibalta** [kenjis/ci-phpunit-test#187]
Hello all, 

I am on a fresh install and copied everything to tests folder under application. I ran the phpunit inside the tests folder and I got the following 
```
There were 3 errors:

1) Welcome_test::test_index
Exception: Serialization of 'Closure' is not allowed

2) Welcome_test::test_method_404
Exception: Serialization of 'Closure' is not allowed

3) Welcome_test::test_APPPATH
Exception: Serialization of 'Closure' is not allowed

```
I need help solving this issue please.

**Comment by ODelibalta** [comment]
I've fixed my issue by changing backglobals to false in the phpunit config xml file. Can anyone provide input as to why this change happens to be the fix? Thank you

**Comment by kenjis** [comment]
If you have an global object with closures, PHPUnit tries to back it up (serialize it), but PHP can't serialize closures. So the exception will be thrown.
