### ISSUE TITLE
How to write test authorization

### ISSUE THREAD

**Issue by prefect1** [kenjis/ci-phpunit-test#190]
Hello, faced with the problem of writing a test for user authorization. Example of authorization system: http://php.net/manual/en/features.http-auth.php. How to send the correct parameters to the header for authorization ??
PHPUnit 5.7.21 version 
Ci3 3.1.5. version 
ci_phpunit-test 0.14.0 version 
php 5.6.30  version

**Comment by kenjis** [comment]
How about just setting `$_SERVER['PHP_AUTH_USER']` in your test code?

**Comment by kenjis** [comment]
If you still have the problem, feel free to reopen or create an issue.
