### ISSUE TITLE
PHP Fatal error:  Class 'TestCase' not found in

### ISSUE THREAD

**Issue by HK321** [kenjis/ci-phpunit-test#191]
I have installed via composer and according to the instructions but I am getting this error. My phpunit is 6.2.3

**Comment by joel-depiltech** [comment]
Hello @HK321,
Did you enable 'composer_autoload' in your config file ?

**Comment by HK321** [comment]
no can you please tell me the procedure?

**Comment by joel-depiltech** [comment]
You have to set a value to `$config['composer_autoload']` in your file application/config/config.php

**Comment by HK321** [comment]
Thank you fixed it .
