### ISSUE TITLE
Post array?

### ISSUE THREAD

**Issue by purdy** [kenjis/ci-phpunit-test#197]
Is there a way to send an array through a POST request? I've tried:
```
    $post_data = [
      'categories[]' => '324',
      # ...
    ];
    $output = $this->request('POST', ['CONTROLLER', 'RUNMODE'], $post_data);
```
And:
```
    $post_data = [
      'categories[0]' => '324',
```

And:
```
    $post_data = [
      'categories' => ['324'],
```

The end result is that I either get errors or CodeIgniter doesn't see the array value in the runmode processing.

Thanks!

**Comment by kenjis** [comment]
@purdy I wrote a test: https://github.com/kenjis/ci-app-for-ci-phpunit-test/commit/6ca558b8a8dc0721b378fd6ce7b4b859a8084b3b

I think the last one should work. But I don't know why it does not work for you.

**Comment by kenjis** [comment]
If you still have the problem, feel free to reopen or create an issue.
