### ISSUE TITLE
Fatal error: Call to undefined method Welcome_test::request()

### ISSUE THREAD

**Issue by satishkhatri** [kenjis/ci-phpunit-test#198]
Hi Kenji,

I am trying to implement your phpunit test and trying to execute you expmple code welcome_test.php. I am getting "Fatal error: Call to undefined method Welcome_test::request()" ,my codignitor version is 3.0. Please look into and give me you view.

Satish

**Comment by kenjis** [comment]
How did you install ci-phpunit-test?

**Comment by satishkhatri** [comment]
Hi,

case 1
I downloaded ci-phpunit-test-0.15.0 and put into project/application/tests/ci-phpunit-test-0.15.0
case 2
I download through composer which reside in vendor/kenjis
In both cases, it not working...

**Comment by kenjis** [comment]
cd project
phpunit -c application/tests

**Comment by awaistariq** [comment]
I am having same issue:

mac-atariq:tests atariq$ phpunit models

```
PHPUnit 3.6.0 by Sebastian Bergmann.

PHP Fatal error:  Uncaught Error: Call to undefined method Application_Session_Model_Test::newModel() in /Applications/XAMPP/xamppfiles/htdocs/OPA/application/tests/models/Application_Session_Model_Test.php:15
Stack trace:
#0 /Applications/XAMPP/xamppfiles/lib/php/PHPUnit/Framework/TestCase.php(777): Application_Session_Model_Test->setUp()
#1 /Applications/XAMPP/xamppfiles/lib/php/PHPUnit/Framework/TestResult.php(649): PHPUnit_Framework_TestCase->runBare()
#2 /Applications/XAMPP/xamppfiles/lib/php/PHPUnit/Framework/TestCase.php(727): PHPUnit_Framework_TestResult->run(Object(Application_Session_Model_Test))
#3 /Applications/XAMPP/xamppfiles/lib/php/PHPUnit/Framework/TestSuite.php(772): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#4 /Applications/XAMPP/xamppfiles/lib/php/PHPUnit/Framework/TestSuite.php(745): PHPUnit_Framework_TestSuite->runTest(Object(Application_Session_Model_Test), Object(PHPUnit_Framework_TestResult))
#5 /Applications/XAMPP/xamppfiles/lib/php/PHPUnit/Framework/TestSuite.php(704): PHP in /Applications/XAMPP/xamppfiles/htdocs/OPA/application/tests/models/Application_Session_Model_Test.php on line 15

Fatal error: Uncaught Error: Call to undefined method Application_Session_Model_Test::newModel() in /Applications/XAMPP/xamppfiles/htdocs/OPA/application/tests/models/Application_Session_Model_Test.php on line 15

Error: Call to undefined method Application_Session_Model_Test::newModel() in /Applications/XAMPP/xamppfiles/htdocs/OPA/application/tests/models/Application_Session_Model_Test.php on line 15

Call Stack:
    0.0002     353304   1. {main}() /Applications/XAMPP/xamppfiles/bin/phpunit:0
    0.0027     560256   2. PHPUnit_TextUI_Command::main() /Applications/XAMPP/xamppfiles/bin/phpunit:46
    0.0027     560352   3. PHPUnit_TextUI_Command->run() /Applications/XAMPP/xamppfiles/lib/php/PHPUnit/TextUI/Command.php:126
    0.0480    1473832   4. PHPUnit_TextUI_TestRunner->doRun() /Applications/XAMPP/xamppfiles/lib/php/PHPUnit/TextUI/Command.php:188
    0.0665    1650600   5. PHPUnit_Framework_TestSuite->run() /Applications/XAMPP/xamppfiles/lib/php/PHPUnit/TextUI/TestRunner.php:317
    0.0666    1650600   6. PHPUnit_Framework_TestSuite->run() /Applications/XAMPP/xamppfiles/lib/php/PHPUnit/Framework/TestSuite.php:704
    0.0666    1650600   7. PHPUnit_Framework_TestSuite->runTest() /Applications/XAMPP/xamppfiles/lib/php/PHPUnit/Framework/TestSuite.php:745
    0.0667    1650600   8. Application_Session_Model_Test->run() /Applications/XAMPP/xamppfiles/lib/php/PHPUnit/Framework/TestSuite.php:772
    0.0667    1650600   9. PHPUnit_Framework_TestResult->run() /Applications/XAMPP/xamppfiles/lib/php/PHPUnit/Framework/TestCase.php:727
    0.0823    1680184  10. Application_Session_Model_Test->runBare() /Applications/XAMPP/xamppfiles/lib/php/PHPUnit/Framework/TestResult.php:649
    0.0866    1758328  11. Application_Session_Model_Test->setUp() /Applications/XAMPP/xamppfiles/lib/php/PHPUnit/Framework/TestCase.php:777

```


I have installed by downlaoding the zip and placing it in application/tests/....

**Comment by kenjis** [comment]
> PHPUnit 3.6.0

I'm not sure, but your PHPUnit seems to be too old.

**Comment by awaistariq** [comment]
I am using phpstorm and here is what pref is saying:
![screen shot 2017-12-03 at 11 47 51 am](https://user-images.githubusercontent.com/3714825/33523775-e3941c62-d81f-11e7-86ce-51a7ca99c4f7.png)

**Comment by kenjis** [comment]
@awaistariq 

But  your output says:
> PHPUnit 3.6.0 by Sebastian Bergmann.

**Comment by awaistariq** [comment]
I figured this out, phpunit was refereing to xampp old version. Now its is pointing to latest..

mac-atariq:OPA atariq$ phpunit --version
PHPUnit 6.5.2 by Sebastian Bergmann and contributors.

However I am still getting errors like:

Class 'TestCase' not found in /Applications/XAMPP/xamppfiles/htdocs/OPA/application/tests/models/Application_Session_Model_Test.php on line 9

**Comment by awaistariq** [comment]
If I try to do testing using Phpstorm run tests with phpunit.xml as configuration file...

/usr/local/Cellar/php71/7.1.11_22/bin/php /Applications/XAMPP/xamppfiles/htdocs/OPA/vendor/phpunit/phpunit/phpunit --configuration /Applications/XAMPP/xamppfiles/htdocs/OPA/application/tests/phpunit.xml --teamcity
Testing started at 3:16 PM ...
Failed loading /usr/local/opt/php71-xdebug/xdebug.so:  dlopen(/usr/local/opt/php71-xdebug/xdebug.so, 9): image not found

Warning: require(/Applications/XAMPP/xamppfiles/htdocs/OPA/application/tests/_ci_phpunit_test/CIPHPUnitTest.php): failed to open stream: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/OPA/application/tests/Bootstrap.php on line 360

Fatal error: require(): Failed opening required '/Applications/XAMPP/xamppfiles/htdocs/OPA/application/tests/_ci_phpunit_test/CIPHPUnitTest.php' (include_path='.:') in /Applications/XAMPP/xamppfiles/htdocs/OPA/application/tests/Bootstrap.php on line 360
PHP Warning:  require(/Applications/XAMPP/xamppfiles/htdocs/OPA/application/tests/_ci_phpunit_test/CIPHPUnitTest.php): failed to open stream: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/OPA/application/tests/Bootstrap.php on line 360
PHP Fatal error:  require(): Failed opening required '/Applications/XAMPP/xamppfiles/htdocs/OPA/application/tests/_ci_phpunit_test/CIPHPUnitTest.php' (include_path='.:') in /Applications/XAMPP/xamppfiles/htdocs/OPA/application/tests/Bootstrap.php on line 360

Process finished with exit code 255

**Comment by awaistariq** [comment]
The problem was there were a lot of files missing in ci_phpunit_test folder. After adding them manually it worked fine. However, in config.php I have 
`function __autoload($class)
{
    if (substr($class, 0, 3) !== 'CI_') {
        if (file_exists($file = APPPATH . 'core/' . $class . '.php')) {
            include $file;
        }
    }
}` to load custom base controller file. If I add this piece of code the test fails to execute otherwise runs fine. Can you help me handle this situation?

**Comment by kenjis** [comment]
@awaistariq 
`__autoload()` can set only one autoloader. So if you set it, autoloader in ci-phpunit-test does not work.

It has been depreciated as of PHP 7.2.0.
http://php.net/manual/en/function.autoload.php

Use `spl_autoload_register` instead.
http://php.net/manual/en/function.spl-autoload-register.php

**Comment by duytran31187** [comment]
Hi
my projects have config:
$application_folder = '../../app';
$system_path          = '../../sys';
then I use command: php vendor/kenjis/ci-phpunit-test/update.php [-a app and -p public_html.
my system folder is 'sys' not 'system' how can i pass it to install command ?

I got these message when running: phpunit . : 
1. Use of undefined constant UTF8_ENABLED.
2.  Call to undefined function current_url().

How to fix it ? 
Thanks

**Comment by Abonia1** [comment]
I get the same error as follow while i try to test my model:
vendor/bin/phpunit application/tests/models/MyModelAdminTest.php
PHPUnit 8.2.3 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 99 ms, Memory: 4.00 MB

There was 1 error:

1) MyModelAdminTest::test_reservation_all_data
Error: Call to undefined method MyModelAdminTest::resetInstance()


ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
