### ISSUE TITLE
Not working if use environment config folder

### ISSUE THREAD

**Issue by igorlebedev** [kenjis/ci-phpunit-test#2]
Hi, found a bug - module won't load if some app configs are movet by environment folder, for example - I move $config['log_threshold'] from application/config/config.php to application/config/development/config.php and to application/config/development/config.php and terminal returnet error " Undefined index: log_threshold". Same situation is with database.php config file

**Comment by kenjis** [comment]
Thank you for your report.

First of all, *ci-phpunit-test* fixes environment `testing`.
https://github.com/kenjis/ci-phpunit-test/blob/master/application/tests/Bootstrap.php#L56

So `application/config/development/config.php` and `application/config/development/config.php` are not loaded at all.

`$config['log_threshold']` should be in `config/config.php` or `config/testing/config.php`.

**Comment by igorlebedev** [comment]
Ah, I see. Thanks for quick answer!
