### ISSUE TITLE
How using hooks in tests?

### ISSUE THREAD

**Issue by RodolfoSilva** [kenjis/ci-phpunit-test#20]
We have to implement support hooks for unit tests.

http://www.codeigniter.com/user_guide/general/hooks.html

**Comment by kenjis** [comment]
If we do *unit* tests, we should test only a hook class.
This is my test case: https://github.com/kenjis/codeigniter-tettei-apps/blob/develop/application/tests/hooks/Convert_encoding_test.php#L13-27
The hook converts character encoding of `$_POST` on some conditions at `pre_system`.

Do you want to do functional tests including hooks? If so, we have to implement something to support it. 

Anyway, first of all, what do you want to test?

**Comment by RodolfoSilva** [comment]
I have one library for check it is authorized call method, and this call in post_controller_constructor.

**Comment by kenjis** [comment]
If I were you, I write tests only for the library, and write controller tests (hook is just ignored). I think it is enough.

But do you want controller tests to call the hook?

**Comment by RodolfoSilva** [comment]
I want to be sure that the hook is working. 
But I'm going to follow your suggestion that also works.

**Comment by kenjis** [comment]
> I want to be sure that the hook is working. 

If your config for hooks is right, it must be working. It is CodeIgniter's specification.
We don't have to test if we trust CodeIgniter.

And I also test my application with Selenium for acceptance test. It probably test hooks are working or not.

I'm not sure we need support testing with hooks. I ignored hooks, because

1. It is not needed for *unit* testing
2. too many hook points, so I was not sure how to implement

But if you really want to do it, you can add code to call hooks to `request()` method.

**Comment by kenjis** [comment]
See  #23

**Comment by RodolfoSilva** [comment]
Improved now with #23

**Comment by kenjis** [comment]
I found a hack to add autoloader for controllers in `pre_system` hook.

> 3 . Using an autoload function with hooks (the slow and right way)
http://avenir.ro/codeigniter-tutorials/no-more-my_controller-how-you-can-create-more-than-one-base-controller/

In this case, we need to call `pre_system` before executing controllers.

**Comment by kenjis** [comment]
I added docs on hooks in current ci-phpunit-test:
https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#hooks

**Comment by kenjis** [comment]
I think the current specification is good enough. So I'm planning to close the issue.
If anyone has any opinion about it, please post.
