### ISSUE TITLE
How can I test a file upload?

### ISSUE THREAD

**Issue by fikoborquez** [kenjis/ci-phpunit-test#200]
Can anybody give me an example? Thanks :)

**Comment by kenjis** [comment]
See <https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/master/application/tests/controllers/Upload_test.php>.

**Comment by fikoborquez** [comment]
Excelent!, thanks a lot :)

**Comment by MasonFI** [comment]
When testing file upload, you need monkey patching enabled, right?

But when using php 7.1 syntax, it doesnt seem to work. Tests throw "Fatal error: A void function must not return a value in" error. Function is defined to return void value, but no value is returned at any point in function. 

Does anyone else have this problem?

**Comment by kenjis** [comment]
> When testing file upload, you need monkey patching enabled, right?

No.
