### ISSUE TITLE
Is v0.15.0 compatible with PHPUnit 5.7.21?

### ISSUE THREAD

**Issue by bigweld86** [kenjis/ci-phpunit-test#201]
I'm using PHPUnit 5.7.21 with PHP5.6.31 and haven't been able to run tests. When executing I'm getting the following messages: 

PHP Warning:  require(/var/www/docs/myapp/application/tests/third_party/PHP-Parser-3.0.3/lib/bootstrap.php): failed to open stream: No such file or directory in /var/www/docs/myapp/application/tests/Bootstrap.php on line 25
PHP Fatal error:  require(): Failed opening required '/var/www/docs/myapp/application/tests/third_party/PHP-Parser-3.0.3/lib/bootstrap.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/docs/myapp/application/tests/Bootstrap.php on line 25

I don't have composer and cannot install it since am not the server admin, so I followed the instructions to set ci-phpunit-test manually.

Am I missing anything?

Thanks

**Comment by bigweld86** [comment]
So I was able to 'fix' this (although not sure if that's the right way) by modifying the paths in /tests/Bootstrap.php to:

```
// If you don't use Composer
else {
        if (version_compare(PHP_VERSION, '5.5.0', '>=')) {
                // Use PHP-Parser 3.x
                //require __DIR__ . '/third_party/PHP-Parser-3.0.3/lib/bootstrap.php';
                require __DIR__ . '/_ci_phpunit_test/patcher/third_party/PHP-Parser-3.0.3/lib/boo$
                //require __DIR__ . '/3.x/MonkeyPatchManager.php';
                require __DIR__ . '/_ci_phpunit_test/patcher/3.x/MonkeyPatchManager.php';
        } else {
                // Use PHP-Parser 2.x
                require __DIR__ . '/third_party/PHP-Parser-2.1.1/lib/bootstrap.php';
                require __DIR__ . '/2.x/MonkeyPatchManager.php';
        }
}

require __DIR__ . '/_ci_phpunit_test/patcher/IncludeStream.php';
require __DIR__ . '/_ci_phpunit_test/patcher/PathChecker.php';
require __DIR__ . '/_ci_phpunit_test/patcher/MonkeyPatch.php';
require __DIR__ . '/_ci_phpunit_test/patcher/Cache.php';
require __DIR__ . '/_ci_phpunit_test/patcher/InvocationVerifier.php';

require __DIR__ . '/_ci_phpunit_test/patcher/functions/exit__.php';
```

But now when trying to run a test I'm getting:

PHP Fatal error:  Class 'TestCase' not found in /var/www/docs/myapp/application/tests/libraries/Calculator_test.php on line 14

**Comment by kenjis** [comment]
See https://github.com/kenjis/ci-phpunit-test/blob/v0.15.0/application/tests/Bootstrap.php
It seems you changed the file, because the line 25 is comments:
https://github.com/kenjis/ci-phpunit-test/blob/v0.15.0/application/tests/Bootstrap.php#L25

**Comment by bigweld86** [comment]
Yes, I had to change because the original file wasn't working

**Comment by kenjis** [comment]
> Is v0.15.0 compatible with PHPUnit 5.7.21?

Yes.

**Comment by kenjis** [comment]
> PHP Warning: require(/var/www/docs/myapp/application/tests/third_party/PHP-Parser-3.0.3/lib/bootstrap.php): failed to open stream: No such file or directory in /var/www/docs/myapp/application/tests/Bootstrap.php on line 25

There is no `/var/www/docs/myapp/application/tests/third_party/PHP-Parser-3.0.3/lib/bootstrap.php`. So your code does not work.

This is NOT ci-phpunit-test bug.

**Comment by bigweld86** [comment]
For some reason the unzipped Bootstrap.php was corrupted so it wasn't the same file. I downloaded it again and got the right one.
Thanks

**Comment by kenjis** [comment]
No problem.
