### ISSUE TITLE
Problems loading Encrypt library

### ISSUE THREAD

**Issue by jperezb** [kenjis/ci-phpunit-test#206]
Hi, I have problems loading the Encrypt library in a controller function. When I run the test I can print anything before the loading line but if I want to print after the line it doesn't print.

Please help!

**Comment by kenjis** [comment]
Would you please show me sample code?

**Comment by jperezb** [comment]
I found the problema and was mine. I use XAMPP for macOS with PHP 5.6, but PHPUnit was using PHP7 installed by Homebrew.
I printed a die with phpinfo() and show me the problem with the deprecated function in PHP7 mcrypt_get_iv_size.

Thanks for all!
