### ISSUE TITLE
How to test a redirect with dynamic parameters

### ISSUE THREAD

**Issue by jperezb** [kenjis/ci-phpunit-test#209]
Hi, I want to test a redirect but the parameters in the URL are dynamics (encrypted). For example:

URL: "profesor/pruebas/V1FLcGp3UHdzcGdUQzl=="
where "V1FLcGp3UHdzcGdUQzl==" are dynamic.

How can I do that?

Thanks!

**Comment by kenjis** [comment]
You can't test random output.

But if you can inject a mock object which generates the random output,
you can fix the redirect URL.

See <https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#request-and-use-mocks>.

**Comment by jperezb** [comment]
Thanks for your answer. What do you think about using assertResponseCode(302)??

**Comment by kenjis** [comment]
@jperezb If you want to check just a redirection occurs, it is okay.
If you want to check the part `profesor/pruebas/` in the URL, it is not enough.

When you have more than two cases of redirections in the request,
probably it is better to check the URL.

**Comment by jperezb** [comment]
Thanks!
