### ISSUE TITLE
What's the difference between callControllerMethod and requestUri?

### ISSUE THREAD

**Issue by RodolfoSilva** [kenjis/ci-phpunit-test#21]
I see duplicates codes in CIPHPUnitTest.php, it's correct? 
@kejins, how about this?

**Comment by kenjis** [comment]
`callControllerMethod` calls a controller class method directly. It does not use "routing".
`requestUri` first gets a route, and call a controller class method.

See https://github.com/kenjis/ci-phpunit-test/blob/master/docs/FunctionAndClassReference.md#testcaserequestmethod-argv-params---callable--null
If the argument $argv is an array, we call `callControllerMethod`.
If the argument $argv is an string, we call `requestUri`.

**Comment by kenjis** [comment]
Generally speaking, duplicates codes are not good.

They are refactored: https://github.com/kenjis/ci-phpunit-test/blob/master/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php
