### ISSUE TITLE
How to mock method in the tested controller?

### ISSUE THREAD

**Issue by apyatkov** [kenjis/ci-phpunit-test#210]
Hello,

I'm still exploring all the functionality of ci-phpunit-test for writing unit tests and I'm struggling to mock methods in the controller I'm testing.  So any advices or tips will be appreciated.

Structure of my Controller:
```php
<?php

class PortalControllerBase extends CI_Controller
{
    public function index()
    {
        if ($this->session->condition) {
            $this->view('error');
            return;
        }
        # Mode conditions
    }

    public function view($page)
    {
        $data = [];
        $this->load->view($page, $data);
    }
}

class PortalController extends PortalControllerBase
{
}
```

My test:

```php
<?php
 
class TestPortalController extends TestCase
{
    public function setUp()
    {
        $this->obj = $this->newController('PortalController');
        $this->obj->logger = $this->getDouble(
            'logger', ['info' => true, 'error' => true, 'debug' => true]
        );
    }

    public function test_index()
    {
        $output = $this->obj->index();
        print_r($output);
    }
}
```

When I execute my test I can see errors coming from PortalController->view() method.
**How can I mock PortalController->view()?** I want to check if this method is being called and with what parameters but not execute it.
My goal is to write unit tests per method and mock as much as possible so nothing outside this method is being executed or tested.

I've tried using Monkey patching at different places:
```php
MonkeyPatch::patchMethod('PortalController', ['view' => true]);
```
but with no success

**Comment by apyatkov** [comment]
I've got it working with **phpunit** approach in combination with **ci-phpunit-test** to instantiate the test class. "PortalController" couldn't be instantiated properly by using just **phpunit**.

```php

<?php

class TestPortalController extends TestCase
{
    public function test_hotspot_is_false()
    {
        $mock = $this->getMockBuilder('PortalController')
                     ->disableOriginalConstructor()
                     ->setMethods(array('view'))
                     ->getMock();

        $mock->logger = $this->getMockBuilder('stdClass')
                             ->setMethods(array('error'))
                             ->getMock();

        $mock->session = $this->getMockBuilder('stdClass')
                              ->setMethods(array('set_flashdata'))
                              ->getMock();
        $mock->session->condition = true;

        $mock->expects($this->once())
        ->method('view')
        ->with('error');

        $mock->index();
    }
}

```

Not sure if this can be done entirely by using **ci-phpunit-test** functionality.

**Comment by kenjis** [comment]
@apyatkov ci-phpunit-test is kind of wrapper for PHPUnit.
Almost all PHPUnit functionality works with ci-phpunit-test.

If you want to mock method in the tested controller, you must create a mock of the controller.
Your approach is fine.

ci-phpunit-test does not provide mocking functionality, but just provides a short-cut to PHPUnit getMockBuilder. See <https://github.com/kenjis/ci-phpunit-test/blob/master/docs/FunctionAndClassReference.md#testcasegetdoubleclassname-params-constructor_params--false>.

**Comment by apyatkov** [comment]
Thank you, @kenjis 

I think I'm on the right track now. Just need more time to uncover all the secrets
