### ISSUE TITLE
How to replace session_set_cookie_params 

### ISSUE THREAD

**Issue by luckydonald** [kenjis/ci-phpunit-test#214]
Heya. 
On [Session/Session.php:296](https://github.com/bcit-ci/CodeIgniter/blob/211d23d31bd33d857377bdb13abdc104772164ff/system/libraries/Session/Session.php#L296) CodeIgniter sets the `HttpOnly` attribute on session cookies to `TRUE`, which [breaks](https://stackoverflow.com/a/21811292/3423324)  browser based cookie creation in Selenium tests.

So I could imagine to work around that like the following:
```php
$new_session_set_cookie_params  = function ($lifetime, $path = null, $domain = null, $secure = false, $httponly = false) {
	session_set_cookie_params($lifetime, $path, $domain, $secure, FALSE);
}
MonkeyPatch::patchFunction('session_set_cookie_params', $new_session_set_cookie_params);
```
However, that does not work.

How can I force `HttpOnly` to be always false on created cookies?

**Comment by kenjis** [comment]
Do you use ci-phpunit-test with Selenium?

**Comment by luckydonald** [comment]
I try at least, as the monkeypatching looks like the right tool

**Comment by kenjis** [comment]
I think you could do it with monkey patching. 

But you have to patch your code on the process in Web server. In other words, you have to integrate your CodeIgniter with the the Monkey patching library. And turn monkey patching on only when you run testing.
