### ISSUE TITLE
Setting environment variables via `phpunit.xml`

### ISSUE THREAD

**Issue by stebogit** [kenjis/ci-phpunit-test#215]
It seems I can not set variables using the `phpunit.xml` file as described [here](https://phpunit.de/manual/current/en/appendixes.configuration.html#appendixes.configuration.php-ini-constants-variables).

I trided this:
```xml
<phpunit>
    <!-- ... -->
    <php>
        <define name="foo" value="define"/>
	<ini name="foo" value="ini"/>
	<const name="foo" value="const"/>
	<var name="foo" value="var"/>
	<env name="foo" value="env"/>
	<post name="foo" value="post"/>
	<get name="foo" value="get"/>
	<cookie name="foo" value="cookie"/>
	<server name="foo" value="server"/>
	<files name="foo" value="files"/>
	<request name="foo" value="request"/>
    </php>
</phpunit>
```
but I can't find the `foo` variable anywhere when tests are running, like with `getenv()` or inside the `$_ENV`, `$_SERVER`, or `$_GLOBALS` arrays. I don't have any other clue where to look for it.

I've never done this before so I don't know if I'm doing something wrong or this feature is just not supported by `ci-phpunit-test`.
Is the [CI way](https://www.codeigniter.com/user_guide/libraries/config.html#environments) the only method to set environment variables? I'd prefer to use the PUPUnit way so the code is less framework specific.

**Comment by kenjis** [comment]
@stebogit 
I don't know why you can't get the variables.
It seems you are doing right.

I tried to set `$_GET['foo']` with phpunit.xml, and had no problem.

https://github.com/kenjis/ci-app-for-ci-phpunit-test

```diff
--- a/application/tests/controllers/Super_global_test.php
+++ b/application/tests/controllers/Super_global_test.php
@@ -2,6 +2,11 @@
 
 class Super_global_test extends TestCase
 {
+ public function test_phpunit_get()
+ {
+     var_dump($_GET); exit;
+ }
+
    public function test_index_with_get_params()
    {
        $output = $this->request(
diff --git a/application/tests/phpunit.xml b/application/tests/phpunit.xml
index d721500..e994dc6 100644
--- a/application/tests/phpunit.xml
+++ b/application/tests/phpunit.xml
@@ -8,6 +8,9 @@
            <exclude>./_ci_phpunit_test/</exclude>
        </testsuite>
    </testsuites>
+ <php>
+     <get name="foo" value="get"/>
+ </php>
    <filter>
        <whitelist>
            <directory suffix=".php">./_ci_phpunit_test</directory>
```

I got the following:
```
Starting test 'Super_global_test::test_phpunit_get'.
.../ci-app-for-ci-phpunit-test/application/tests/controllers/Super_global_test.php:7:
array(1) {
  'foo' =>
  string(3) "get"
}
```

**Comment by fikoborquez** [comment]
Did you try to set the phpunit --configuration parameter to use your .xml file? Maybe you're writing in a wrong xml file.

**Comment by stebogit** [comment]
@fikoborquez I'm using the file in `/application/tests/phpunit.xml`, is there another one?

Anyway, I tried this cause I need to set some private keys/data, normally set using a `.env` file (I actually use the `.htaccess` one), also in some tests. One of the benefit of this solution is being able to easily/safely ignoring it when pushing to your public repo. I can't use the `phpunit.xml` file to set private variables anyway since I need to push it as part of the testing environment (right?).
The `.htaccess` solution doesn't seem to work while testing and in my understanding nether [dotenv](https://github.com/vlucas/phpdotenv).

What would be a clean solution to this issue? Would there be like maybe a "partial" xml file you could load in addition to the standard one to include private settings?

**Comment by kenjis** [comment]
@stebogit
You can use dotenv with testing.
Just add some code to load dotenv in your `application/tests/Bootstrap.php`.

I use `DotEnv.php` of CodeIgniter4, and put the following code in the top of  `application/tests/Bootstrap.php`.

```php
require __DIR__.'/DotEnv.php';
$env = new DotEnv(__DIR__.'/../..');
$env->load();
unset($env);
```

**Comment by witrin** [comment]
Same problem here. I'm not sure if this is some how related  to Docker but in fact it doesn't work.

**Comment by dikirill** [comment]
FYI. PHPUnit doesn't (by default) overwrite env variables that are already set. You can use the force="true" option to force this (requires PHPUnit v6.3 - sebastianbergmann/phpunit#2723)
`<env name="foo" value="env" force="true"/>`
