### ISSUE TITLE
Dependency injection for controllers

### ISSUE THREAD

**Issue by stebogit** [kenjis/ci-phpunit-test#217]
Hi @kenjis,
I needed to test a controller which uses an object that includes an HTTP Client, for which I need to control the response for the test, so I needed to mock the object and pass it to the Controller.
After some reading I found out it's possible to instantiate the Controller using
```php
$this->newController('MyController')
``` 
and then call directly the desired method.

However for some reason it is not possible, as far as I know, to pass parameters to the constructor so I created this simple method (which is just a copy of the original one):

```php
public function newControllerWithParams($classname, $params)
{
    reset_instance();
    $controller = new $classname($params);
    $this->CI =& get_instance();
    return $controller;
}
```

Is there already any other method that I should actually use to do what I need to do?
If not, would it be worth it adding an optional `$params` to the existing `$this->newController()`?

**Comment by kenjis** [comment]
@stebogit 

How do you pass params to your controller constructor in CodeIginter?

> I needed to test a controller which uses an object that includes an HTTP Client, for which I need to control the response for the test, so I needed to mock the object and pass it to the Controller.

As far as I know there is no way to pass params to controller constructor in CodeIgniter.
So `$this->newController()` has no way to pass params to the constructor.

How about creating a mock object and just inject it after instantiation of the controller?

```
$mock = ...create mock...
$controller = $this->newController('MyController')
$controller->client = $mock;
```

**Comment by stebogit** [comment]
Well, I simply implement the controller constructor like this:
```php
protected $client;
protected $anotherObject;

public function __construct(array $resources = null)
{
    parent::__construct();

    if (ENVIRONMENT === 'testing') {
        // allow injection for test
        if (isset($resources['client'])) {
            $this->client = $resources['client'];
        }
        if (isset($resources['object'])) {
            $this->anotherObject = $resources['object'];
        }
    }
}
```

To be able to set the `client` like you suggested (`$controller->client = $mock;`) the `client` attribute (or it's setter method) should be public, which I don't think is appropriate in this case.

**Comment by kenjis** [comment]
In that case, you could use `ReflectionHelper::setPrivateProperty()`.
See <https://github.com/kenjis/ci-phpunit-test/blob/master/docs/FunctionAndClassReference.md#reflectionhelpersetprivatepropertyobj-property-value>.
