### ISSUE TITLE
Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by Cipa** [kenjis/ci-phpunit-test#218]
When generating the HTML report I get

A PHP Error was encountered

Severity:    Warning
Message:     count(): Parameter must be an array or an object that implements Countable
Filename:    /Users/mine/Projects/pro/pm/application/vendor/phpunit/php-code-coverage/src/Report/Html/Renderer/File.php
Line Number: 307

Backtrace:
	File: /Users/mine/Projects/pro/pm/application/vendor/phpunit/php-code-coverage/src/Report/Html/Renderer/File.php
	Line: 307
	Function: count

	File: /Users/mine/Projects/pro/pm/application/vendor/phpunit/php-code-coverage/src/Report/Html/Renderer/File.php
	Line: 61
	Function: renderSource

	File: /Users/mine/Projects/pro/pm/application/vendor/phpunit/php-code-coverage/src/Report/Html/Facade.php
	Line: 117
	Function: render

	File: /Users/mine/Projects/pro/pm/application/vendor/phpunit/phpunit/src/TextUI/TestRunner.php
	Line: 578
	Function: process

	File: /Users/mine/Projects/pro/pm/application/vendor/phpunit/phpunit/src/TextUI/Command.php
	Line: 186
	Function: doRun

	File: /Users/mine/Projects/pro/pm/application/vendor/phpunit/phpunit/src/TextUI/Command.php
	Line: 116
	Function: run

	File: /Users/mine/Projects/pro/pm/application/vendor/phpunit/phpunit/phpunit
	Line: 52
	Function: main

**Comment by DakuTree** [comment]
Noticing this as well after updating to PHP 7.2.

**Comment by kenjis** [comment]
This? https://github.com/sebastianbergmann/php-code-coverage/issues/551

**Comment by DakuTree** [comment]
Yeah seems to be the same issue.

Updating to the latest version of PHPUnit appears to fix the code-coverage bug, but still seems to the same issue with CIPHPUnitTestDouble.

```
A PHP Error was encountered
Severity:    Warning
Message:     count(): Parameter must be an array or an object that implements Countable
Filename:    /home/travis/build/DakuTree/manga-tracker/application/tests/_ci_phpunit_test/CIPHPUnitTestDouble.php
Line Number: 80
Backtrace:
	File: /home/travis/build/DakuTree/manga-tracker/application/tests/_ci_phpunit_test/CIPHPUnitTestDouble.php
	Line: 80
	Function: _error_handler
	File: /home/travis/build/DakuTree/manga-tracker/application/tests/_ci_phpunit_test/CIPHPUnitTestDouble.php
	Line: 175
	Function: _verify
	File: /home/travis/build/DakuTree/manga-tracker/application/tests/_ci_phpunit_test/CIPHPUnitTestCase.php
	Line: 276
	Function: verifyInvokedOnce
	File: /home/travis/build/DakuTree/manga-tracker/application/tests/libraries/MY_Form_validation_test.php
	Line: 65
	Function: verifyInvokedOnce
	File: /home/travis/build/DakuTree/manga-tracker/vendor/phpunit/phpunit/src/Framework/TestCase.php
	Line: 1071
	Function: invokeArgs
	File: /home/travis/build/DakuTree/manga-tracker/vendor/phpunit/phpunit/src/Framework/TestCase.php
	Line: 939
	Function: runTest
	File: /home/travis/build/DakuTree/manga-tracker/vendor/phpunit/phpunit/src/Framework/TestResult.php
	Line: 698
	Function: runBare
	File: /home/travis/build/DakuTree/manga-tracker/vendor/phpunit/phpunit/src/Framework/TestCase.php
	Line: 894
	Function: run
	File: /home/travis/build/DakuTree/manga-tracker/vendor/phpunit/phpunit/src/Framework/TestSuite.php
	Line: 755
	Function: run
	File: /home/travis/build/DakuTree/manga-tracker/vendor/phpunit/phpunit/src/Framework/TestSuite.php
	Line: 755
	Function: run
	File: /home/travis/build/DakuTree/manga-tracker/vendor/phpunit/phpunit/src/Framework/TestSuite.php
	Line: 755
	Function: run
	File: /home/travis/build/DakuTree/manga-tracker/vendor/phpunit/phpunit/src/TextUI/TestRunner.php
	Line: 546
	Function: run
	File: /home/travis/build/DakuTree/manga-tracker/vendor/phpunit/phpunit/src/TextUI/Command.php
	Line: 195
	Function: doRun
	File: /home/travis/build/DakuTree/manga-tracker/vendor/phpunit/phpunit/src/TextUI/Command.php
	Line: 148
	Function: run
	File: /home/travis/build/DakuTree/manga-tracker/vendor/phpunit/phpunit/phpunit
	Line: 53
	Function: main
```
Full log: https://travis-ci.org/DakuTree/manga-tracker/builds/316100640

**Comment by kenjis** [comment]
@Cipa I got the same error with PHP 7.2.
I updated PHPUnit to v6.1, and the error disappears.

**Comment by kenjis** [comment]
@DakuTree I have no error with PHP 7.2 and PHPUnit 6.1.
See <https://travis-ci.org/kenjis/ci-phpunit-test/jobs/328695294>.

**Comment by DakuTree** [comment]
@kenjis The issue I was having was actually due to using v0.15.0 which doesn't seem to work on PHP7.2 (namely due to missing e4c957c3efc7d12966075fd0b68148628bf6fd74).  
Had to force composer to grab the latest commit to make it work.

**Comment by kenjis** [comment]
@DakuTree Sorry and yes, v0.15.0 does not work on PHP 7.2.
Would you please use `1.0.x@dev` (=`dev-master`) for some time?
I would like to release next version after checking CodeIgniter 3.1.7.

**Comment by pnbpss** [comment]
I updated PHPUnit from 5.7.27 to 6.5.9, the warning is disappeared.
