### ISSUE TITLE
Cannot redeclare __autoload() (previously declared in /var/www/html/app/application/config/config.php:511)

### ISSUE THREAD

**Issue by harrisworld** [kenjis/ci-phpunit-test#219]
Hello,

I am having problem configuring the ci-phpunit-test with PHPUnit and CodeIgniter 3. I have downloaded the ci-phpunit-test for CodeIgniter 3.x and have copied the application/tests folder into my application folder in CodeIgniter project.
When i open console, phpunit-> hit enter, i am getting the below error messages.

Do we need to do any configurations....

Error:         No code coverage driver is available

PHP Fatal error:  Cannot redeclare __autoload() (previously declared in /var/www/html/app/application/config/config.php:511) in /var/www/html/app/application/config/config.php on line 517

Fatal error: Cannot redeclare __autoload() (previously declared in /var/www/html/app/application/config/config.php:511) in /var/www/html/app/application/config/config.php on line 517

A PHP Error was encountered

Severity:    Compile Error
Message:     Cannot redeclare __autoload() (previously declared in /var/www/html/app/application/config/config.php:511)
Filename:    /var/www/html/app/application/config/config.php
Line Number: 517

**Comment by kenjis** [comment]
Would you show me your `application/config/config.php` around line 511 and line 517?

**Comment by kenjis** [comment]
You  cannot redeclare `__autoload()`, it is PHP specification.
