### ISSUE TITLE
Setting mongodb as database

### ISSUE THREAD

**Issue by tato469** [kenjis/ci-phpunit-test#221]
I am trying to set mongodb as database instead mysql. 
I have my test model loading my mongo library (It works in normal models):

    class Candidate_model_test extends TestCase
    {
    	public static function setUpBeforeClass()
    	{
    		parent::setUpBeforeClass();
    		
    		$CI =& get_instance();
    		$CI->load->library('Seeder');
    		$CI->load->library('Mongo_db');
    
    		$CI->seeder->call('CandidateSeeder');
    	}
    	public function setUp()
    	{
    		$this->obj = $this->newModel('Candidate_model');
    	}
    }

My problem is that I am having the following error:

  ` PHP Fatal error:  Class 'MongoDB\Driver\WriteConcern' not found in 
  /Users/fernando/Desktop/codeigniter/application/tests/_ci_phpunit_test/replacing/core/Loader.php on line 1346`

`Fatal error: Class 'MongoDB\Driver\WriteConcern' not found in /Users/fernando/Desktop/codeigniter/application/tests/_ci_phpunit_test/replacing/core/Loader.php on line 1346`

`A PHP Error was encountered`

`Severity:    Error
Message:     Class 'MongoDB\Driver\WriteConcern' not found
Filename:    /Users/fernando/Desktop/codeigniter/application/tests/_ci_phpunit_test/replacing/core/Loader.php
Line Number: 1346`

**I think it fails because it is not including the vendor autoload file, where should I add it?**

I tried to add `include_once APPPATH .'vendor/autoload.php';` (my vendor is inside application folder) in `application/tests/_ci_phpunit_test/autoloader.php` but nothing happens.

    /****** autoloader.php ********/
    
    <?php
    /**
     * Part of ci-phpunit-test
     *
     * @author     Kenji Suzuki <https://github.com/kenjis>
     * @license    MIT License
     * @copyright  2015 Kenji Suzuki
     * @link       https://github.com/kenjis/ci-phpunit-test
     */
    
    
    
    // Autoloader for ci-phpunit-test
    require __DIR__ . '/CIPHPUnitTestAutoloader.php';
    require __DIR__ . '/CIPHPUnitTestFileCache.php';
    $cache = new CIPHPUnitTestFileCache(
    	__DIR__ . '/tmp/cache/autoload.php'
    );
    $autoload_dirs = CIPHPUnitTest::getAutoloadDirs();
    $autoloader = new CIPHPUnitTestAutoloader($cache, $autoload_dirs);
    spl_autoload_register([$autoloader, 'load']);
    
    // Register CodeIgniter's tests/mocks/autoloader.php
    define('SYSTEM_PATH', BASEPATH);
    require APPPATH .'tests/mocks/autoloader.php';
    spl_autoload_register('autoload');
    
    include_once APPPATH .'vendor/autoload.php';  /*** Trying to add composer libraries

**Comment by kenjis** [comment]
Don't use `$this->newModel()` in your case, because it resets the CI instance.

**Comment by kenjis** [comment]
If you still have this problem, feel free to reopen.
