### ISSUE TITLE
Conflict with phpdocumentor

### ISSUE THREAD

**Issue by zia** [kenjis/ci-phpunit-test#222]
I can't install phdocumentor v2 and ci-phpunit-test alongside. When I try to install ci-phpunit-test with existing phpdocumentor it gives me error like this,
"Problem 1
    - Installation request for kenjis/ci-phpunit-test ^0.15.0 -> satisfiable by kenjis/ci-phpunit-test[v0.15.0].
    - Conclusion: remove nikic/php-parser v1.4.1
    - Conclusion: don't install nikic/php-parser v1.4.1
    - kenjis/ci-phpunit-test v0.15.0 requires nikic/php-parser ^2.1|^3.0 -> satisfiable by nikic/php-parser[v2.1.0, v2.1.1, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.1.0, v3.1.1, v3.1.2, v3.1.3]......"
If i put the require-dev code on top of phpdocumentor(in composer.json), somehow it installs and works but the phpdocumentor stops working.

**Comment by kenjis** [comment]
It says `remove nikic/php-parser v1.4.1`.

See <https://github.com/phpDocumentor/phpDocumentor2/issues/1818#issuecomment-273463356>.
It seems you should install phpdocumentator using the PHAR.
