### ISSUE TITLE
mocking helper methods?

### ISSUE THREAD

**Issue by ghost** [kenjis/ci-phpunit-test#226]
Great book for unit testing Kenji!

I am following along your book: 7.3 Mocking Models

I want to create a pure unit test for controller where I mock all dependencies. You show clearly how to mock objects and models etc etc, but I was confused how to go about mocking a single CodeIgniter helper function.

My CI helper method (obv not in a class so no object to mock) returns an array of strings that populate an html select for year, month and date

I was able to mock it and hard code return values using
Chapter 8.6 Monkey Patching
you discuss "patching functions" and your example overrides glob() php function.
I was able to use the same procedure in book to override my custom CI helper function named: date_select_options()

Question #1)
Is there a quicker way other than using Monkey Patching to mock a SINGLE CI HELPER FUNCTION that does not belong to a class? It does slow down app and I like to leave Monkey Patching commented out in Bootstrap file if possible.

Question #2)
If I were to NOT mock this date_select_options() function in helper file, would this then NOT be considered UNIT Testing? Do I have to mock this to achieve "unit testing"

ALSO I noticed an old question I had the same problem with and I think I know what the problem is:
https://github.com/kenjis/ci-phpunit-test/issues/89

He has authentication going on in MY_Controller so that is why he is getting NULL for this $this->request()

I had same issue and had to add:
if ($this->input->is_cli_request() !== true)
    $this->authenticate();
In MY_Controller constructor()

Thanks,
I love your book and learned so much. Please reply back

**Comment by kenjis** [comment]
@not-good-enough Thank you.

Q1:
I know one way.

First, you add `Php_func` library:
```php
class Php_func
{
    public function __call($function_name, $args)
    {
        return call_user_func_array($function_name, $args);
    }
}
```

Next, change your code using the library: `$this->php_func->date_select_options()`

Next, you can create a mock for the library.
