### ISSUE TITLE
Testing response codes

### ISSUE THREAD

**Issue by fieldhof** [kenjis/ci-phpunit-test#228]
I'm using codeigniter-restserver in combination with ci-phpunit-test. In my code I throw the custom `NotFoundException` when something is not found, for example a player. 

```php
class RestException extends Exception
{
    public function __construct(string $message = "", int $code = 0, \Throwable $previous = null)
    {
        parent::__construct($message, $code, $previous);
    }
}

class NotFoundException extends RestException
{
    public function __construct($message)
    {
        parent::__construct($message, Api_Controller::HTTP_NOT_FOUND);
    }
}
```

I've just created the `RestException` class to check if the thrown `Exception` is of instance `RestException`. This exception will be caught in `REST_Controller::remap()`

```php
        try {
            call_user_func_array([$this, $controller_method], $arguments);
        } catch (Exception $ex) {
            if ($this->config->item('rest_handle_exceptions') === false) {
                throw $ex;
            }

            // If the method doesn't exist, then the error will be caught and an error response shown
            $_error = &load_class('Exceptions', 'core');
            $_error->show_exception($ex);
        }
```

I have rest_handle_exception set to true so it shows the exception. By default codeigniter will return a HTML page to the user, but as it is a REST server I'm trying to create I want to return JSON and the response codes set to custom ones, i.e. 404 when a player isn't found. To overcome this I've overriden  `CI_Exceptions::show_exception($exception)` (Created `MY_Exception` class and overriden them):

```php
    public function show_exception($exception)
    {
        if ($exception instanceof RestException) {
            http_response_code($exception->getCode());
            echo json_encode([
                'status' => false,
                'message' => $exception->getMessage()
            ]);
        } else {
            echo json_encode([
                'status' => false,
                'message' => $exception->getMessage()
            ]);
        }
    }
```

When I wan't to test if I retrieve a 404 when I request a certain player that doesn't exist I have the following test:
```php
$output = $this->request('GET', 'players/0');
```

But when I execute this test it throws the exception instead of resulting in a 404 with a json object explaining what went wrong. 

```
NotFoundException: Player[0] not found

.../sources/application/models/Playermodel.php:38
.../sources/application/controllers/Players.php:46
.../sources/application/libraries/REST_Controller.php:706
.../sources/application/core/MY_Controller.php:46
.../sources/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php:348
.../sources/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php:282
.../sources/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php:151
.../sources/application/tests/_ci_phpunit_test/CIPHPUnitTestCase.php:183
.../sources/application/tests/controllers/Players_test.php:34
.../sources/vendor/phpunit/phpunit/phpunit:53
```

Is there some setting i'm missing?

**Comment by kenjis** [comment]
@fieldhof It seems this is a problem in your code.
Check the code in MY_Controller.php:23 and Players.php:18.
What does throw UnauthorizedException?

**Comment by fieldhof** [comment]
When a player is not found a NotFoundException is thrown. This is done in a controller which extends from REST_Controller. I see that i've attached the wrong piece of log. Please ignore the part about the UnauthorizedException. This part is the correct one.

```1) Players_test::test_player_get
NotFoundException: Player[0] not found

.../sources/application/models/Playermodel.php:38
.../sources/application/controllers/Players.php:46
.../sources/application/libraries/REST_Controller.php:706
.../sources/application/core/MY_Controller.php:46
.../sources/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php:348
.../sources/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php:282
.../sources/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php:151
.../sources/application/tests/_ci_phpunit_test/CIPHPUnitTestCase.php:183
.../sources/application/tests/controllers/Players_test.php:34
.../sources/vendor/phpunit/phpunit/phpunit:53
```

I expected that with the extension of `CI_Exceptions::show_exception($exception)` shown above the Notfoundexception would be 'printed' but phpunit sees that the UnauthorizedException is thrown, instead of seeing a response code of 401 being returned.

**Comment by luckydonald** [comment]
Because the codeigniter's error processing happens when the code terminates.
If the code is done, and there still is a uncatched Exception, it will displays it.

However, I'm not sure if that still happens in unit tests, as PHPUnit keeps running other tests and thus the PHP script doesn't terminate.

**Comment by kenjis** [comment]
If you still have this problem, feel free to reopen.
