### ISSUE TITLE
Problem is testing whole project at a time

### ISSUE THREAD

**Issue by sagrpoudel** [kenjis/ci-phpunit-test#231]
Fatal error: Call to undefined function PhpParser\canonicalize() in F:\xampp\htdocs\tdd-ci\application\tests\_ci_phpunit_test\patcher\third_party\PHP-Parser-2.1.1\test\PhpParser\CodeTestAbstract.php on line 17

A PHP Error was encountered

Severity:    Error
Message:     Call to undefined function PhpParser\canonicalize()
Filename:    F:\xampp\htdocs\tdd-ci\application\tests\_ci_phpunit_test\patcher\third_party\PHP-Parser-2.1.1\test\PhpParser\CodeTestAbstract.php
Line Number: 17

Backtrace:

PHP Fatal error:  Call to undefined function PhpParser\canonicalize() in F:\xampp\htdocs\tdd-ci\application\tests\_ci_phpunit_test\patcher\third_party\PHP-Parser-2.1.1\test\PhpParser\CodeTestAbstract.php on line 17
Done.

**Testing a particular test file works good. But while testing whole project, above error shows in output panel"**

**Comment by kenjis** [comment]
@sagrpoudel 

> Fatal error: Call to undefined function PhpParser\canonicalize() in F:\xampp\htdocs\tdd-ci\application\tests_ci_phpunit_test\patcher\third_party\PHP-Parser-2.1.1\test\PhpParser\CodeTestAbstract.php on line 17

It seems that is a test for PHP-Parser. I don't know why the test runs.

**Comment by luckydonald** [comment]
@sagrpoudel  How does your `phpunit.xml` look like?

There might be a condition running everything matching `*.php`?

Maybe adding 
```xml
<exclude>.\tests_ci_phpunit_test\patcher\third_party\PHP-Parser-2.1.1\</exclude>
```
could exclude them from test?
