### ISSUE TITLE
PHP Error each() deprecated in PHP 7.x

### ISSUE THREAD

**Issue by joelcollyer** [kenjis/ci-phpunit-test#238]
Encountered this little error today after our development environment was upgraded to the latest version of PHP 7:
```
A PHP Error was encountered

Severity:    8192
Message:     The each() function is deprecated. This message will be suppressed on further calls
Filename:    PATH/TO/PROJECT/application/tests/_ci_phpunit_test/patcher/3.x/Patcher/FunctionPatcher.php
Line Number: 169
```

**Comment by kenjis** [comment]
Please update ci-phpunit-test to v0.16.0.

**Comment by joelcollyer** [comment]
Whoops! I missed the new release. Updating the library resolved the issue. Thank you; and sorry for the mistake!
