### ISSUE TITLE
I can't run tests

### ISSUE THREAD

**Issue by felipe86hs** [kenjis/ci-phpunit-test#24]
Hi!, I installed phpunit test, I followed the instructions but I got this error.

~~~
felipe@Lenovo-Y50-70:/application/tests$ ../../vendor/bin/phpunit --debug
PHP Fatal error:  Call to a member function item() on null in /system/core/Utf8.php on line 48
PHP Stack trace:
PHP   1. {main}() /vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /vendor/phpunit/phpunit/phpunit:36
PHP   3. PHPUnit_TextUI_Command->run() /vendor/phpunit/phpunit/src/TextUI/Command.php:101
PHP   4. PHPUnit_TextUI_Command->handleArguments() /vendor/phpunit/phpunit/src/TextUI/Command.php:111
PHP   5. PHPUnit_TextUI_Command->handleBootstrap() /vendor/phpunit/phpunit/src/TextUI/Command.php:590
PHP   6. PHPUnit_Util_Fileloader::checkAndLoad() /vendor/phpunit/phpunit/src/TextUI/Command.php:755
PHP   7. PHPUnit_Util_Fileloader::load() /vendor/phpunit/phpunit/src/Util/Fileloader.php:36
PHP   8. include_once() /vendor/phpunit/phpunit/src/Util/Fileloader.php:52
PHP   9. CIPHPUnitTest::init() /application/tests/Bootstrap.php:296
PHP  10. require_once() /application/tests/_ci_phpunit_test/CIPHPUnitTest.php:62
PHP  11. load_class() /system/core/CodeIgniter.php:159
PHP  12. CI_Utf8->__construct() /application/tests/_ci_phpunit_test/replacing/core/Common.php:98

Fatal error: Call to a member function item() on null in /system/core/Utf8.php on line 48

Call Stack:
    0.0001     235664   1. {main}() /vendor/phpunit/phpunit/phpunit:0
    0.0061     866368   2. PHPUnit_TextUI_Command::main() /vendor/phpunit/phpunit/phpunit:36
    0.0061     866992   3. PHPUnit_TextUI_Command->run() /vendor/phpunit/phpunit/src/TextUI/Command.php:101
    0.0061     869712   4. PHPUnit_TextUI_Command->handleArguments() /vendor/phpunit/phpunit/src/TextUI/Command.php:111
    0.0081    1289032   5. PHPUnit_TextUI_Command->handleBootstrap() /vendor/phpunit/phpunit/src/TextUI/Command.php:590
    0.0082    1297344   6. PHPUnit_Util_Fileloader::checkAndLoad() /vendor/phpunit/phpunit/src/TextUI/Command.php:755
    0.0082    1297544   7. PHPUnit_Util_Fileloader::load() /vendor/phpunit/phpunit/src/Util/Fileloader.php:36
    0.0083    1323600   8. include_once('/application/tests/Bootstrap.php') /vendor/phpunit/phpunit/src/Util/Fileloader.php:52
    0.0084    1337648   9. CIPHPUnitTest::init() /application/tests/Bootstrap.php:296
    0.0102    1737704  10. require_once('/system/core/CodeIgniter.php') /application/tests/_ci_phpunit_test/CIPHPUnitTest.php:62
    0.0113    1874528  11. load_class() /system/core/CodeIgniter.php:159
    0.0114    1892072  12. CI_Utf8->__construct() /application/tests/_ci_phpunit_test/replacing/core/Common.php:98
~~~

**Comment by RodolfoSilva** [comment]
Example, please.

**Comment by felipe86hs** [comment]
Hi, in the terminal I did:

--------------------------------------------------
$ cd application/tests
$ ../../vendor/bin/phpunit --debug
--------------------------------------------------

And the result was the same as my original post.

**Comment by rochefort** [comment]
Hi, felipe86hs.

What is the version of CodeIgniter?
Is it version 2?

Now I have no problem as follows.
PHP 5.6.10
CodeIgniter 3.0

**Comment by felipe86hs** [comment]
Hi rochefot, im using CI version 3.
and I update php to 5.6.10.
I don't understand why i can't use this normally

**Comment by RodolfoSilva** [comment]
CodeIgniter  is not 3.0

```
PHP Fatal error: Call to a member function item() on null in /system/core/Utf8.php on line 48
PHP Stack trace:
```

CI 3: Utf8.php on line 48
https://github.com/bcit-ci/CodeIgniter/blob/develop/system/core/Utf8.php#L48

CI 2: Utf8.php on line 48
https://github.com/bcit-ci/CodeIgniter/blob/2.2.3/system/core/Utf8.php#L48

**Comment by felipe86hs** [comment]
Damn! wrong project... I'm sorry, now I installed in the correct project but now I got this error:

------------------------------------------------------------------------------------------
felipe@Lenovo-Y50-70:/application/tests$ ../../vendor/bin/phpunit --debug

A PHP Error was encountered

Severity: NoticeMessage:  Constant MODPATH already definedFilename: /application/core/MY_Router.phpLine Number: 95

Backtrace:
            
            
            
            
    File: /application/core/MY_Router.php Line: 95    Function: define
        
            
    File: /application/core/MY_Router.php Line: 24    Function: _set_routing
        
            
    File: /application/tests/_ci_phpunit_test/replacing/core/Common.php   Line: 98    Function: __construct
        
            
    File: /application/tests/_ci_phpunit_test/functions.php   Line: 37    Function: load_class
        
            
    File: /application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php    Line: 89    Function: reset_instance
        
            
    File: /application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php    Line: 41    Function: callControllerMethod
        
            
    File: /application/tests/_ci_phpunit_test/CIPHPUnitTestCase.php   Line: 54    Function: request
        
            
    File: /application/tests/controllers/Welcome_test.php Line: 15    Function: request
        
            
            
    File: /vendor/phpunit/phpunit/src/Framework/TestCase.php  Line: 881   Function: invokeArgs
        
            
    File: /vendor/phpunit/phpunit/src/Framework/TestCase.php  Line: 746   Function: runTest
        
            
    File: /vendor/phpunit/phpunit/src/Framework/TestResult.php    Line: 601   Function: runBare
        
            
    File: /vendor/phpunit/phpunit/src/Framework/TestCase.php  Line: 702   Function: run
        
            
    File: /vendor/phpunit/phpunit/src/Framework/TestSuite.php Line: 738   Function: run
        
            
    File: /vendor/phpunit/phpunit/src/Framework/TestSuite.php Line: 738   Function: run
        
            
    File: /vendor/phpunit/phpunit/src/TextUI/TestRunner.php   Line: 428   Function: run
        
            
    File: /vendor/phpunit/phpunit/src/TextUI/Command.php  Line: 147   Function: doRun
        
            
    File: /vendor/phpunit/phpunit/src/TextUI/Command.php  Line: 99    Function: run
        
            
    File: /vendor/phpunit/phpunit/phpunit Line: 36    Function: main

----------------------------------------------------------------------------------------------------------------

**Comment by RodolfoSilva** [comment]
Update MY_Route to CI 3.0

**Comment by kenjis** [comment]
If you define constant in your *MY_* core classes, you have to change it like this:

~~~php
if (! defined('MODPATH'))
{
	define('MODPATH', 'something');
}
~~~

Because ci-phpunit-test loads them again in `reset_instance()` (when you call `$this->request()`).

**Comment by kenjis** [comment]
I removed my comment, because it was wrong.

**Comment by felipe86hs** [comment]
Hi! and thanks to everybody, I found the mistake, it was my fault. Sorry

**Comment by kenjis** [comment]
No problem. What's your mistake?

**Comment by 2n2n** [comment]
for those who had still the same problem.. for codeigniter 2
http://www.jamesfairhurst.co.uk/posts/view/codeigniter_phpunit_and_netbeans

and the assignment of 
`$this->CI =& get_instance` 
should be inside the setUp() function of the test file.
