### ISSUE TITLE
Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by luckydonald** [kenjis/ci-phpunit-test#242]
```
Cannot modify header information - headers already sent by (output started at phar:///path/to/project/phpunit.phar/phpunit/Util/Printer.php:114)
Filename:    /path/to/project/tests/_ci_phpunit_test/patcher/3.x/Patcher/FunctionPatcher/Proxy.php
Line Number: 184
```
[Permalink to line](https://github.com/kenjis/ci-phpunit-test/blob/34eb4c6cdc02975b56aa860500d39078e5ddd0be/application/tests/_ci_phpunit_test/replacing/core/Common.php#L291) (revield when FunctionPatcher is off)

Happening when using internal requests
```php
$this->request($http_method, $argv, $params);
```
I have revived an older branch (I made PRs here xD), and this was working before, I'm currently investigating if that is due to a newer https://github.com/chriskacerguis/codeigniter-restserver though.

**Comment by luckydonald** [comment]
Might be [`replacing/core/Common.php:L280`](https://github.com/kenjis/ci-phpunit-test/blob/34eb4c6cdc02975b56aa860500d39078e5ddd0be/application/tests/_ci_phpunit_test/replacing/core/Common.php#L280)
```php
// Everything is done, so return
// added by ci-phpunit-test
if (ENVIRONMENT === 'testing')
{
	return;
}
```

not being called, as we use `'testing'` for our staging server,
So I have to run the unittests as `'development'` `ENVIRONMENT`.

Is there any reason to allow the other configurations to not return there too?

**Comment by luckydonald** [comment]
In fact changing the if to 
```php
ENVIRONMENT === 'testing' || ENVIRONMENT === 'development'
```
makes it work for my configuration.

I noticed this isn't the only `ENVIRONMENT === 'testing'` check in this library.

Maybe we could add a 
```php
define('IS_UNITTEST', ENVIRONMENT === 'testing')
```
to the `Bootstrap.php` file, to be easily overwritten?
Checks would just be 
```php
if (IS_UNITTEST)
```

Another Idea is 
```php
define('UNITTEST_ENVIRONMENT', 'development')
```php
```
if (ENVIRONMENT === UNITTEST_ENVIRONMENT)
```

**Comment by luckydonald** [comment]
Probably the `IS_UNITTEST` is the most flexible and still easy to read.

Searching for `ENVIRONMENT\s*[!=]==?\s*(['"])testing\1`: 
It is always this line skipping the end of some stuff in different versions of that file or of CI:
`Common.php`, `Common.php-3.0.0`, `Common.php-3.1.0` and `Common.php-3.1.2`.
In `download_helper.php` where it does the header via `$CI->output`,
and `url_helper.php` where it replaces any action with a `CIPHPUnitTestRedirectException`.

**Comment by luckydonald** [comment]
@kenjis What would you say?

**Comment by biechao** [comment]
@luckydonald 

Try this **phpunit --stderr**

It works for me when I try to test the download file request and get this error.

**Comment by kenjis** [comment]
`@runTestsInSeparateProcesses` and `@runInSeparateProcess` might help you.

https://phpunit.readthedocs.io/en/latest/annotations.html#runtestsinseparateprocesses

**Comment by kenjis** [comment]
@luckydonald 
I don't like to add new constants.
I'm going to add a new function: #354

**Comment by kenjis** [comment]
@luckydonald I changed from `is_testing_env()` to `TestCase::isTestingEnv()`
https://github.com/kenjis/ci-phpunit-test/pull/360
