### ISSUE TITLE
"Notice: Trying to get property of non-object" when run in container

### ISSUE THREAD

**Issue by aphofstede** [kenjis/ci-phpunit-test#244]
I'm getting similar errors to https://github.com/kenjis/ci-phpunit-test/issues/162 when running in a Docker container set up by my CI platform. (http://buddy.works)

```
./vendor/phpunit/phpunit/phpunit --bootstrap ./application/tests/Bootstrap.php --configuration ./application/tests/phpunit.xml --teamcity
Notice: Trying to get property of non-object in /buddy/oris/application/tests/_ci_phpunit_test/replacing/core/Common.php on line 269
Warning: Creating default object from empty value in /buddy/oris/application/tests/_ci_phpunit_test/replacing/core/Common.php on line 270
The configuration file does not exist.
```

I don't have config subdirectories, but the test suite works locally so I don't think that's the problem here. Any ideas?

PHPUnit 6.5.7
PHP 7.1.11
kenjis/ci-phpunit-test v0.16.0

**Comment by kenjis** [comment]
If you have still this problem, feel free to reopen.
