### ISSUE TITLE
Tests stopped working after updating to 0.16.1 from 0.15.0

### ISSUE THREAD

**Issue by graphicalx** [kenjis/ci-phpunit-test#256]
Hi,

Background:
I recently updated PHP from 7.1.6 to 7.2.4, and a few tests were giving issues (session_destory) wasn't working. I decided to update my CodeIgniter (3.1.6 to 3.1.8), and then updated ci-phpunit-test (0.15.0 to 0.16.1, replace the _ci folder, added UnitTestCase and updated Bootstrap.php).

However, now even the simple Welcome_test is showing this error:

> Argument 1 passed to CIPHPUnitTestRequest::__construct() must be an instance of TestCase, instance of Welcome_test given, called in \application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php on line 68
 \application\tests\_ci_phpunit_test\CIPHPUnitTestRequest.php:45
 \application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php:68
 \application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php:144
 \application\tests\controllers\Welcome_test.php:21

Welcome_test lines 19-22:
```
	public function testIndex()  
	{
		$output = $this->request('GET', '');
		$this->assertRedirect('login');
```

Any idea why this might be happening?
Thanks

**Comment by ytetsuro** [comment]
I have created PR of revision.

https://github.com/kenjis/ci-phpunit-test/pull/254

**Comment by graphicalx** [comment]
Yup, that seems to be the issue here. Lets see what kenjis thinks.

**Comment by kenjis** [comment]
@graphicalx Fixed the bug on master branch.

**Comment by graphicalx** [comment]
Thanks!
