### ISSUE TITLE
PHP Fatal error: Class 'TestCase' not found in path

### ISSUE THREAD

**Issue by sithara** [kenjis/ci-phpunit-test#257]
For some reason, the below code snippet throws me an error
```
<?php
class OrderControllerTest extends TestCase
{
  public function testupload() {
    $a='foo';
    $output = $this->request('POST',[Order', 'upload',$a] );
  }
}
```

throws `PHP Fatal error:  Class 'TestCase' not found in path`

Appreciate any help

**Comment by sithara** [comment]
I tried moving the tests to `application/tests` folder and now I get 

`PHPUnit 7.2.4 by Sebastian Bergmann and contributors.

  Warning - The configuration file did not pass validation!
  The following problems have been detected:

  Line 24:
  - Element 'log', attribute 'logIncompleteSkipped': The attribute 'logIncompleteSkipped' is not allowed.

  Test results may not be as expected.


Error:         No code coverage driver is available

.                                                                   1 / 1 (100%)

Time: 73 ms, Memory: 6.00MB

OK (1 test, 1 assertion)
`

**Comment by kenjis** [comment]
@sithara Please check your PHPUnit config file: `application/tests/phpunit.xml`.
Because the warning says "The configuration file did not pass validation!"

But it seems your test passed.

> OK (1 test, 1 assertion)

**Comment by sithara** [comment]
@kenjis Thanks a lot :+1: , that really helped

**Comment by sithara** [comment]
And there's one more issue I have been facing 

This is my controller: 

```
class Orders extends CI_Controller {
    public function __construct()
    {
        parent::__construct();
        $this->load->model('order_model');
    }

    # POST /orders/upload | accepts multi-part form encoded
    public function upload()
    {
        $config = array(
            'upload_path' => '../order_uploads/',
            'allowed_types' => 'jpg',
            'encrypt_name' => true
        );
        $this->load->library('upload', $config);

        # upload the file
        if ($this->upload->do_upload('order_file')) {
             // do something here
         }
}
```

and my tests

```
<?php
class OrderControllerTest extends TestCase
{
   public function testupload() {
     $this->request('POST', 'orders/upload?order_file=some_file.jpg');
   }
}
```
While running tests, `$this->upload->do_upload('order_file')` always returns a false. Is it because its not loading the library correctly?

Kind Regards
Sithara
