### ISSUE TITLE
.PHP Fatal error:  Uncaught CIPHPUnitTestExitException: exit()

### ISSUE THREAD

**Issue by Shadollu** [kenjis/ci-phpunit-test#258]
Hello guys,

When I use phpunit on tests folder, error pops.
its seems like exit() will cause error?

![default](https://user-images.githubusercontent.com/16536167/41152640-e061c03e-6b46-11e8-8895-ffe1e8998c45.png)

**Comment by kenjis** [comment]
@Shadollu It seems your code calls `exit()`.

In that case, you must catch the exception in your test code.
See <https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#exit>.
