### ISSUE TITLE
Cann't run test. show error message "The configuration file does not exist"

### ISSUE THREAD

**Issue by jeffcao** [kenjis/ci-phpunit-test#26]
hi, 
i installed the ci-phpunit-test through copy application/tests to my project's application folder, without use composer.
so, when cd to tests folder of my project, and then call phpunit,  the message "The configuration file does not exist" show me, then nothing to happen.
please help me, thanks advanced.

**Comment by kenjis** [comment]
I can't reproduce it.

Did you change your folder structure?
If you changed, you have to fix three paths in tests/Bootstrap.php:
https://github.com/kenjis/ci-phpunit-test/tree/15ac4a283279e5b5d6867b96afd80e448373d989#step-2

**Comment by kenjis** [comment]
What I did:
~~~
$ unzip CodeIgniter-3.0.0.zip
$ unzip ci-phpunit-test-0.3.0.zip
$ mv ci-phpunit-test-0.3.0/application/tests/ CodeIgniter-3.0.0/application/
$ cd CodeIgniter-3.0.0/application/tests/
$ phpunit
...

Time: 683 ms, Memory: 4.25Mb

OK (3 tests, 4 assertions)

Generating code coverage report in Clover XML format ... done

Generating code coverage report in HTML format ... done
~~~

**Comment by jeffcao** [comment]
@kenjis 
Thanks for your answer. 

I know the why for this issue. Because i moved the config.php from application/config to application/config/development.
Now i move config.php to application/config, the unit tests all can run correctly.

May be i should know how to let tests run with application/config/development/config.php. Would you like tell me this? 
Thanks.

**Comment by kenjis** [comment]
Tests always run on `testing` environment.
So you have to create `application/config/testing/config.php`.

See http://www.codeigniter.com/user_guide/libraries/config.html#environments if you don't know well about config files and environments.

**Comment by jeffcao** [comment]
@kenjis 
^_^
Yes, i have got these knowledges. 
Thanks.

**Comment by kenjis** [comment]
You're welcome.

> Tests always run on testing environment.

This was undocumented.

I added documentation:
https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#testing-environment

**Comment by antelove19** [comment]
you can using dynamic environment

	 switch ( $_SERVER['SERVER_NAME'] )
	 {
	 	case 'localhost':
	 		$env = 'development';
	 		break;
		case 'testing.com':
			$env = 'testing';
			break;
	 	case 'yourdomain.com':
	 		$env = 'production';
	 		break;
	 	default:
	 		$env = 'development';
	 		break;
	 }

	define( 'ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : $env );

application/config/development/config.php // $config['base_url'] = "http://localhost/your_project";
application/config/testing/config.php
application/config/production/config.php // $config['base_url'] = "http://{$_SERVER['HTTP_HOST']}";
