### ISSUE TITLE
Message: Too few arguments to function CI_Hooks::__construct(), 0 passed

### ISSUE THREAD

**Issue by apnmrv** [kenjis/ci-phpunit-test#260]
Hello everyone,

I've got the exception, while trying to apply ci-phpunit-test library to a just installed CI-project:

$ ./phpunit --debug

An uncaught Exception was encountered

Type: ArgumentCountError
Message: Too few arguments to function CI_Hooks::__construct(), 0 passed

==================
I use:
$ php --version
PHP 7.1.10 (cli) (built: Oct  2 2017 08:58:21) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.13, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

$ ./phpunit --version
PHPUnit 7.2.4 by Sebastian Bergmann and contributors.

CI 3.1.8 
ci-phpunit-test 0.16.1

Please, help

**Comment by kenjis** [comment]
@apnmrv 
`CI_Hooks::__construct()` has no arguments.
https://github.com/bcit-ci/CodeIgniter/blob/3.1-stable/system/core/Hooks.php#L88

Do you use your `MY_Hook` class?

**Comment by apnmrv** [comment]
Thank you a lot.

No, I do not use any extensions.

It's a brand new installation, made by git clone, and  CI_Hooks constructor signature looks like 

`public function __construct(CI_Config $config)`

Might be a wrong branch?

**Comment by apnmrv** [comment]
Yep, it' s a develop branch, the link from codeigniter.com is leading 
[https://github.com/bcit-ci/CodeIgniter](url)
I've just missed the point.
Thank you a lot for the hint.

**Comment by kenjis** [comment]
@apnmrv You're welcome.
