### ISSUE TITLE
Prevent loading of database

### ISSUE THREAD

**Issue by sumthingsup** [kenjis/ci-phpunit-test#263]
Hi. I don't have access to the database, and I'm trying to unit test the controller but my controller has in its `__construct`
`$this->load->model('some_model');`
and `some_model` has in its `__construct`
`$this->load->database()`

when I make the request, it would error since i don't have an actual database to access. How can I prevent the loading of the database and just have it use my mock library?

**Comment by kenjis** [comment]
You can configure database setting for `testing` environment.
For example, use sqlite for testing:
https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/master/application/config/database.php#L77
