### ISSUE TITLE
Should createCodeIgniterInstance use MY_Controller instead of CI_Controller?

### ISSUE THREAD

**Issue by monsterlane** [kenjis/ci-phpunit-test#268]
https://github.com/kenjis/ci-phpunit-test/blob/master/application/tests/_ci_phpunit_test/CIPHPUnitTest.php#L90

Our app does some funky autoloading in MY_Controller to support multiple 'modes' (clusters). The resetInstance( ) function doesn't reset it properly with this line set to CI_Controller. It does work properly if I change it to MY_Controller. Is this a bug?

Cheers,

**Comment by ytetsuro** [comment]
I think not bug.

Do you want to test unit tests? Or is it a functional test?

For unit tests such as model, there will be little need to rely on CI_Controller such as resetInstance.
In most cases it depends on CI_Loader, so the `newModel` method is enough.
`resetInstnce` method may be useful if you are calling a method of another class via CI_Controller in __construct with a rare case.

However, this UseCase does not require the controller instance to be MY_Controller.

Is that `autoloading` is implementation such that model depends on Controller?
If so, is not it just to solve model dependencies in test case?
Approach to solve this with MY_Controller is different from unit test.
In that case, I think that model is not a testable.

In case of Controller's unit test, you can obtain the target Controller with `newController`.

In case of controlle functional test, I think that the Controller to be tested will be passed as the first argument of `requrest->setCallable` closure.

Therefore, I think `resetInstance` does not need to have responsibility other than resetting CI_Controller.

**Comment by monsterlane** [comment]
Our app heavily extends CI's core to add a lot of new functionality. One of these is a 'mode' that's set in the main config that allows a single code base to operate as an application, API, or worker cluster. Each of these autoloads different libraries, whitelists and blacklists controllers, and a variety of other changes. This is all handled in a method that's called in MY_Controller's constructor.

The application mode uses Redis sessions, the API cluster uses a fake driver that's basically an array, the worker doesn't use sessions and does not load a driver.

Without changing that line none of the above code runs since it's done in MY_Controller. This is specific to our app and I'm sure there's others out there doing similar things that may need the base as their extended controller not the stock one.

**Comment by ytetsuro** [comment]
> This is all handled in a method that's called in MY_Controller's constructor.

In other words, is it meant to solve dependency relationships implemented in `MY_Controller` in the resetInstance method of `ci-phpunit-test`?
I do not think that is called unit test.

`ci-phpunit-test` is an excellent tool, and functional tests can be tested using the `request` method.

If model and library unit tests need a function to solve MY_Controller dependencies, simply think about it, that model and library are not testable code.

I think that model and library should be modified into testable form.

Or, as a functional test, was there any inconvenience by not obtaining `MY_Controller` with `resetInstance`?

> Without the change all the unit tests error on "library is null" since none of them are loaded.

Is it really a unit test?
I think it is problem that dependency of unit test is not solved.

Is resetInstance really a problem?

**Comment by ytetsuro** [comment]
> Yes it's a dependency problem since our app conditionally loads dependencies in MY_Controller based off other flags. It is unique to our setup the reason I reported it is if others have extended MY_Controller in various ways they'd run into the same issue.

From the above, I think that it is not a bug of resetInstance to use in unit tests.

**Comment by monsterlane** [comment]
Without the original code set to CI_Controller after it resets all the dependencies aren't loaded since it's extending the base controller not our custom one. Since each 'mode' loads a different session driver (loaded from inside MY_Controllers construct not autoload.php) tests throw a lot of errors for missing dependencies. Here's a few screenshots of the code inside MY_Controller and what tests do without the change I'm suggesting.

![screen shot 2018-09-12 at 1 38 30 pm](https://user-images.githubusercontent.com/3654199/45439865-4b9e9f80-b691-11e8-97d9-b75419a3a965.png)
![screen shot 2018-09-12 at 1 38 51 pm](https://user-images.githubusercontent.com/3654199/45439866-4b9e9f80-b691-11e8-84e4-6c397e94abfd.png)

**Comment by ytetsuro** [comment]
There is an exit, but how do you test the conditions going to this 403?

Is the Proposal a controller?
If so, resetInstance does not know the need to instance MY_Controller.
If it is a controller test, can you test with the following code?

```php
<?php

class Proposal_test extends TestCase
{
    public function test_get()
    {
         $this->request->setCallablePreConstructor(function() {
               $session_mock = $this->getDouble(CI_Session::class, [
                   'userdata' => 'foo',
               ]);

               load_class_instance('session', $session_mock);
         });

         $actual = $this->request('GET', 'proposal/get');
         // other...
    }
}

**Comment by monsterlane** [comment]
I'm not testing the 403 conditions. Lines 165 -> 169 are the issue I'm getting at. The code you asked me to test would probably work but then I'd have to add a bunch of logic to detect which session driver to load based on other config settings which is exactly what the code in MY_Controller is doing.

Maybe I'm not being clear; the root of the issue is that extensions to the base controller by using a MY_Controller are not carried over during a reset since it's instantiating the base class not the extended class (if you've created one).

**Comment by ytetsuro** [comment]
> Lines 165 -> 169 are the issue I'm getting at. The code you asked me to test would probably work but then I'd have to add a bunch of logic to detect which session driver to load based on other config settings which is exactly what the code in MY_Controller is doing.

If the session driver changes, what does the behavior of the test change?
Please see the following code.

https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Session/Session.php#L73

If CodeIgniter was in CLI mode when instantiating the Session class, session does not work.
As long as you do not run `set_is_cli(false)`, when running the test with ci-phpunit-test, I think that the problem will not arise if the session driver changes.

> Maybe I'm not being clear; the root of the issue is that extensions to the base controller by using a MY_Controller are not carried over during a reset since it's instantiating the base class not the extended class (if you've created one).

If the test you want to write is a Controller test, you can test the Controller class that inherited the extended MY_Controller by using the `request` method.
In this case, resetInstance is unnecessary when using the request method.

**Comment by monsterlane** [comment]
Correct the case I'm running into is testing a model. In your example test cases it shows to call resetInstance which is where it falls apart for me.

**Comment by ytetsuro** [comment]
Is it impossible to resolve the dependency unless MY_Controller is instantiated with `resetInstance`?
Why?
If session is a problem, is it also difficult to assign mock of session library to the property of model as follows?

```php
class Session_read_model_test extends TestCase
{
   private $obj;

   public function setUp()
   {
       parent::setUp();
       $this->obj = $this->newModel('session_read_model');
   }

   public function test_sess_read()
   {
       $this->obj->session = $this->getDouble(CI_Session::class, [
           'userdata' => 'foo',
        ]);

        // other...
   }
}

**Comment by kenjis** [comment]
@monsterlane Would you please show me a sample test code of your use case?

**Comment by monsterlane** [comment]
`<?php

class Proposal_test extends TestCase {
	private $_proposal_id = 1489;

	public function setUp( ) {
		$this->resetInstance( );
		$this->CI->load->model( 'Proposal' );
		$this->obj = $this->CI->Proposal;
	}

	public function test_get( ) {
		$actual = $this->obj->get( $this->_proposal_id );

		$this->assertArrayHasKey('id', $actual );
	}
}

?>
`

I do not want to code session loads as the driver we load depends on other config settings. Coding manual loads does not simulate our loading process.

**Comment by kenjis** [comment]
@monsterlane I've send PR #271. Does the PR work for you?

**Comment by kenjis** [comment]
Now you could create `MY_Controller` instance as `$this->CI` after `$this->resetInstance(true)`. 
See #271
