### ISSUE TITLE
$this->request does not work with (:num)-Wildcard

### ISSUE THREAD

**Issue by Tilogorn** [kenjis/ci-phpunit-test#270]
My test approach is to find out if all my routes serve a HTTP status code of `200`. Thats a simplified version (pseudo-code).

```php
public function test_availability()
{
    $routes = array(
        'user',
        'user/1'
    );

    foreach ($routes as $route) {
        $this->request('GET', $route);
        $this->assertResponseCode(200);
    }
}
```
My routes.php looks as follows
```php
$route['user']             = 'UserController/listAll';
$route['user/(:num)']      = 'UserController/read/$1';
```

The first route gets tested successfully, the second one returns `404`, although I am sure (the browser and curl verified) the route exists and returns 200.

In my long list of routes, this error occurs only when a route contains `:(num)` (`(:any)` works good!) Any ideas on this one?

**Comment by ytetsuro** [comment]
I made following code.
but, all green.

Controller
```php
class UserController extends CI_Controller
{
   public function listAll()
   {
   }

   public function read($num)
   {
   }
}
```

Test code and routes.php used what you made.

I used following ci-phpunit-test commit number.

https://github.com/kenjis/ci-phpunit-test/commit/8c1364cc2e205aaa0c1cdf5cb7b7b18bf0c2c5dd

I would be happy if you write describe the implementation of reproducible Controller.

**Comment by Tilogorn** [comment]
In a complete vanilla CodeIgniter-Installation it works perfectly. Sorry that I disturbed you, I have to debug this.

**Comment by ytetsuro** [comment]
Your problem seems to be solved, I am glad.😄
