### ISSUE TITLE
PHPUnit\Framework\Exception: Argument #1 (No Value) of PHPUnit\Framework\Assert::assertContains() must be a string

### ISSUE THREAD

**Issue by thdebay** [kenjis/ci-phpunit-test#278]
Hi,

After following the installation steps; when running phpunit I get the following message:
`PHPUnit\Framework\Exception: Argument #1 (No Value) of PHPUnit\Framework\Assert::assertContains() must be a string`

It seems that the $this->request() method is not working... any idea why that might be?

**Comment by kenjis** [comment]
If you have still the problem, please reopen and show the details.
