### ISSUE TITLE
Mock with models that already load database

### ISSUE THREAD

**Issue by SteeveDroz** [kenjis/ci-phpunit-test#279]
Hello,

I have  a problem similar to #263, with a twist: my unit tests run automatically on a GitLab server that doesn't have any database installed (not even SQLite). I **have** to use mocks instead of the production database or a test database. How do I prevent `$this->load->database()` in the model constructor?

**Comment by kenjis** [comment]
ci-phpunit-test uses modified version of the loader class.

You could change the database() method:
https://github.com/kenjis/ci-phpunit-test/blob/master/application/tests/_ci_phpunit_test/replacing/core/Loader.php#L388
