### ISSUE TITLE
 nikic/php-parser version dependency requirement conflicts with phpstan/phpstan

### ISSUE THREAD

**Issue by munkiepus** [kenjis/ci-phpunit-test#280]
Tried adding phpstan to an install with ci-phpunit-test

kenjis/ci-phpunit-test v0.16.1 requires nikic/php-parser ^2.1|^3.0 

however 

phpstan/phpstan 0.10.6 requires nikic/php-parser ^4.0.2 -> satisfiable by nikic/php-parser[v4.0.2, v4.0.3, v4.0.4, v4.1.0].

Not sure how difficult it would be to allow the dependency in kenjis/ci-phpunit-test to nikic/php-parser allow the 4x version of nikic/php-parser.

**Comment by jbackert** [comment]
+1 for this issue

**Comment by omizzy** [comment]
+1 as well

**Comment by TylerLHenderson** [comment]
+1 please and thank you!

**Comment by peterdorsi** [comment]
+1 been looking for a solution

**Comment by kenjis** [comment]
If you don't use monkey patching, ci-phpunit-test does not need nikic/php-parser.
So in that case you can use nikic/php-parser 4.

**Comment by jeisberg** [comment]
I pulled a fork and am going to test - will keep everyone posted!

**Comment by kenjis** [comment]
This might help you.
https://github.com/bamarni/composer-bin-plugin

**Comment by kenjis** [comment]
See #291

**Comment by kenjis** [comment]
@munkiepus @jbackert @omizzy @TylerLHenderson 
Now `master` branch requires nikic/php-parser ^2.1|^3.0|^4.2

**Comment by kenjis** [comment]
@jeisberg 
Now master branch requires nikic/php-parser ^2.1|^3.0|^4.2

**Comment by munkiepus** [comment]
@kenjis great thanks for doing this :)
