### ISSUE TITLE
How to spy on library's function in controller?

### ISSUE THREAD

**Issue by ayyazzafar** [kenjis/ci-phpunit-test#281]
Hi, I am struggling to spy on a function in library that is being called from my controller.

So basically I am testing my controller function. 
I want to test that if my function calls library function once but I could not find out any way. 
I have spent hours but could not find any way.

Please help me if anyone know about this.
I appreciate any response.
Thanks in advance.

**Comment by ytetsuro** [comment]
@ayyazzafar 

> I want to test that if my function calls library function once but I could not find out any way.

I like to use `verifyInvokedOnce`, but if you want to implement spy, what about the following?

```php
<?php

class Example_test extends TestCase {
    public function test_a(){
        $mock = $this->getDouble(CI_Form_validation::class, []);
        $spy  = $this->any();
        $mock->expects($spy)->method('run');

        $this->request->setCallable(function($CI) use($mock) {
            $CI->form_validation = $mock;
        }); 

        $this->request('GET', 'example/index');

        $this->assertCount(1, $spy->getInvocations());                                                                                                                        
        this->assertSame('contact/index', $spy->getInvocations()[0]->parameters[0]);
    }   
}
```
