### ISSUE TITLE
Fatal error: undefined function get_instance

### ISSUE THREAD

**Issue by gesmit** [kenjis/ci-phpunit-test#282]
I could use some help. I installed the latest release, installed phpunit (latest version) and I have CI3.1.9.
My folder structure is this:
root folder/
├── app/
│   └── tests/
├── ci3.1.9/
├── public/
└── vendor/

When I do cd app/tests/
phpunit, I get the fatal error in the title. Also when doing the controller/Welcome_controller.php file, I get the same error.

**Comment by ytetsuro** [comment]
Please `tests/Bootstrap.php`.

changed `$system_path` in tests/Bootstrap.php ?
