### ISSUE TITLE
running test throw warning and error

### ISSUE THREAD

**Issue by ferdianexe** [kenjis/ci-phpunit-test#283]
can someone help me ?
when i run phpunit in
`\application\tests`
i got error like this
`set_error_handler() expects the argument (_error_handler) to be a valid callback in C:\laragon\www\Sharif-Judge\application\tests\_ci_phpunit_test\CIPHPUnitTest.php on line 62`
by the way im using codeigniter 3.0-dev

**Comment by ytetsuro** [comment]
Please CodeIgniter version.
CodeIgniter version is written in `system/core/CodeIgniter.php` the `CI_VERSION`.

**Comment by ferdianexe** [comment]
its CodeIgniter 3.0-dev, i already mention that earlier sir @ytetsuro

**Comment by kenjis** [comment]
@ferdianexe 
ci-phpunit-test does not support 3.0-dev.
Why don't you use 3.1.x?
