### ISSUE TITLE
Any chance to have support for phpunit8?

### ISSUE THREAD

**Issue by saval** [kenjis/ci-phpunit-test#285]
There some [backward incompatible changes](https://phpunit.de/announcements/phpunit-8.html), so tests throw errors. The last mentioned in the README.md version 6.0 has reached its end of life on 1st Feb 2019 and thus it's vital to have support for the fresh versions. Thanks.

**Comment by deoomen** [comment]
+1 to support PHPUnit 8

**Comment by kenjis** [comment]
See #286

**Comment by kenjis** [comment]
@saval @saval 
I created new branch 2.x, and support PHPUnit 8.

See https://github.com/kenjis/ci-phpunit-test/tree/2.x

**Comment by NilsRenaud** [comment]
I saw the branch but the composer line explained in the doc is still installing the v0.17.0. what is the actual composer command to run in order to get a release from this branch ?

Thanks a lot !

**Comment by kenjis** [comment]
@NilsRenaud 

Use `2.x@dev`.
See <https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/2.x/composer.json#L10>.
