### ISSUE TITLE
while im trying to run phpunit it shows these errors , please help me

### ISSUE THREAD

**Issue by pradeep518** [kenjis/ci-phpunit-test#287]
```
PHP Warning:  set_error_handler() expects the argument (_error_handler) to be a valid callback in C:\xampp\htdocs\realestate\application\tests\_ci_phpunit_test\CIPHPUnitTest.php on line 62

Warning: set_error_handler() expects the argument (_error_handler) to be a valid callback in C:\xampp\htdocs\realestate\application\tests\_ci_phpunit_test\CIPHPUnitTest.php on line 62
PHP Warning:  set_error_handler() expects the argument (_error_handler) to be a valid callback in C:\xampp\htdocs\realestate\application\tests\_ci_phpunit_test\replacing\core\CodeIgniter.php on line 138

Warning: set_error_handler() expects the argument (_error_handler) to be a valid callback in C:\xampp\htdocs\realestate\application\tests\_ci_phpunit_test\replacing\core\CodeIgniter.php on line 138
PHP Warning:  register_shutdown_function(): Invalid shutdown callback '_shutdown_handler' passed in C:\xampp\htdocs\realestate\application\tests\_ci_phpunit_test\replacing\core\CodeIgniter.php on line 140

Warning: register_shutdown_function(): Invalid shutdown callback '_shutdown_handler' passed in C:\xampp\htdocs\realestate\application\tests\_ci_phpunit_test\replacing\core\CodeIgniter.php on line 140
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function _exception_handler(), 1 passed and exactly 4 expected in C:\xampp\htdocs\realestate\system\core\Common.php:470
Stack trace:
#0 [internal function]: _exception_handler(Object(Error))
#1 {main}
  thrown in C:\xampp\htdocs\realestate\system\core\Common.php on line 470

Fatal error: Uncaught ArgumentCountError: Too few arguments to function _exception_handler(), 1 passed and exactly 4 expected in C:\xampp\htdocs\realestate\system\core\Common.php:470
Stack trace:
#0 [internal function]: _exception_handler(Object(Error))
#1 {main}
  thrown in C:\xampp\htdocs\realestate\system\core\Common.php on line 470
```

**Comment by jasonrgd** [comment]
same issue.

**Comment by jasonrgd** [comment]
Hi @pradeep518 , what's the version of your codeigniter?

**Comment by pradeep518** [comment]
mine its codeigniter 3.1.9

**Comment by kenjis** [comment]
How do you run phpunit?
Why the function `_error_handler_` is not a valid callback?

**Comment by jasonrgd** [comment]
@kenjis I was getting this error. but I found out that my version of codeigniter was 2 so I used an older fork you have recommended https://github.com/kitsunde/CIUnit Everything works well so my issue is resolved. I couldn't replicate @pradeep518 's error.

**Comment by kenjis** [comment]
@jasonrgd Thanks for reporting!

**Comment by pravin067** [comment]
@kenjis : my version of Codeigniter is 2.1.0, so installed CIUnit as you had recommended : https://github.com/kitsunde/CIUnit. However, if i try to run the sample tests i get an error like : 

`Fatal error: Uncaught Error: Call to undefined function get_instance() in C:\frequence_repo\public\vendor\celc\ciunit\src\libraries\CIUnitTestCase.php on line 76`

This is how i invoke these test files:
`$ ./vendor/bin/phpunit tests/unit/controllers/SomeControllerTest.php`

PHP Fatal error:  Uncaught Error: Call to undefined function get_instance() in C:\frequence_repo\public\vendor\celc\ciunit\src\libraries\CIUnitTestCase.php:76
Stack trace:
#0 C:\frequence_repo\public\vendor\phpunit\phpunit\src\Framework\TestSuite.php(561): CIUnit_TestCase->__construct()
#1 C:\frequence_repo\public\vendor\phpunit\phpunit\src\Framework\TestSuite.php(842): PHPUnit_Framework_TestSuite::createTest(Object(ReflectionClass), 'testWelcomeCont...')
#2 C:\frequence_repo\public\vendor\phpunit\phpunit\src\Framework\TestSuite.php(188): PHPUnit_Framework_TestSuite->addTestMethod(Object(ReflectionClass), Object(ReflectionMethod))
#3 C:\frequence_repo\public\vendor\phpunit\phpunit\src\Runner\BaseTestRunner.php(104): PHPUnit_Framework_TestSuite->__construct(Object(ReflectionClass))
#4 C:\frequence_repo\public\vendor\phpunit\phpunit\src\TextUI\Command.php(125): PHPUnit_Runner_BaseTestRunner->getTest('tests/unit/cont...', 'C:\\frequence_re...', Array)
#5 C:\frequence_repo\public\vendor\phpunit\phpunit\src\TextUI\Command.php(104): in C:\frequence_repo\public\vendor\celc\ciunit\src\libraries\CIUnitTestCase.php on line 76

Fatal error: Uncaught Error: Call to undefined function get_instance() in C:\frequence_repo\public\vendor\celc\ciunit\src\libraries\CIUnitTestCase.php on line 76

Error: Call to undefined function get_instance() in C:\frequence_repo\public\vendor\celc\ciunit\src\libraries\CIUnitTestCase.php on line 76

```
Call Stack:
    1.8275     385528   1. {main}() C:\frequence_repo\public\vendor\phpunit\phpunit\phpunit:0
    1.9441    2706320   2. PHPUnit_TextUI_Command::main(???) C:\frequence_repo\public\vendor\phpunit\phpunit\phpunit:36
    1.9442    2708576   3. PHPUnit_TextUI_Command->run(???, ???) C:\frequence_repo\public\vendor\phpunit\phpunit\src\TextUI\Command.php:104
    1.9529    2892960   4. PHPUnit_TextUI_TestRunner->getTest(???, ???, ???) C:\frequence_repo\public\vendor\phpunit\phpunit\src\TextUI\Command.php:125
    1.9691    3674560   5. PHPUnit_Framework_TestSuite->__construct(???, ???) C:\frequence_repo\public\vendor\phpunit\phpunit\src\Runner\BaseTestRunner.php:104
    1.9693    3708696   6. PHPUnit_Framework_TestSuite->addTestMethod(???, ???) C:\frequence_repo\public\vendor\phpunit\phpunit\src\Framework\TestSuite.php:188
    1.9693    3709008   7. PHPUnit_Framework_TestSuite::createTest(???, ???) C:\frequence_repo\public\vendor\phpunit\phpunit\src\Framework\TestSuite.php:842
    1.9717    3817888   8. SomeControllerTest->__construct(???, ???, ???) C:\frequence_repo\public\vendor\phpunit\phpunit\src\Framework\TestSuite.php:561
```
Could you help in resolving this issue?
