### ISSUE TITLE
Issue executing PHPUnit

### ISSUE THREAD

**Issue by Manigandan-Vijayakumar** [kenjis/ci-phpunit-test#288]
Hi,
I am just start doing Unit tests. I have installed **ci-phpunit-test** in my CI application as mentioned in the Readme file and tried to run it with Welcome Test case. Then I got some errors. **I am not sure whether I missed any configuration.** Please find the issues below,

1. **Undefined index: scheme** in DB.php line number 121. Then, I statically gave mysqli instead of $dns['scheme'] to check further.
2. After 1, got an error such **Error: Call to a member function close() on string** in the file mysqli_driver line number 541.  Then I commented this line and executed the phpunit. Welcome controller got tested successfully. 
3. So, I thought to test the model and then I wrote a test and executed. The error is **Error: Call to a member function result() on null**. Model Code below,
       `$this->db->select('name,value');
        $query = $this->db->get('config');
        $configData=$query->result();`

I tried to fix it by myself but I couldn't. Please help me to fix these errors.

**Comment by ytetsuro** [comment]
Is the DB connection setting of config correct?

https://www.codeigniter.com/user_guide/database/configuration.html

**Comment by Manigandan-Vijayakumar** [comment]
Thank you! 
I got this fixed. It was my fault. I have wrongly defined a constant which cause the issue. Thanks again
