### ISSUE TITLE
'PHPUnit_Framework_TestCase' not found

### ISSUE THREAD

**Issue by Abonia1** [kenjis/ci-phpunit-test#293]
When I run vendor/bin/phpunit application/tests in vs code terminal I got this error:

Fatal error: Class 'PHPUnit_Framework_TestCase' not found in  C:\wamp\www\codeigniterproject\application\tests\_ci_phpunit_test\patcher\third_party\PHP-Parser-2.1.1\test\PhpParser\AutoloaderTest.php line 10

I saw the same issue with PS IDE but iam using VScode is there is any solution to clear this bug.Thank you in advance

**Comment by kenjis** [comment]
Try: https://github.com/kenjis/ci-phpunit-test#how-to-run-tests

**Comment by raksa** [comment]
faced same issue, but fixed by using Phpunit 7.5.17
