### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by pyboyxrb** [kenjis/ci-phpunit-test#295]
The error message is as follows:
Deprecation warning: require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use mikey179/vfsstream instead. Make sure you fix this as Composer 2.0 will error.
I hope this useful to you.

**Comment by kenjis** [comment]
@pyboyxrb Thank you for your info!

**Comment by kenjis** [comment]
https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/master/composer.json#L9
https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/2.x/composer.json#L9
