### ISSUE TITLE
Can you use it in production version? (I mean it changes some files)

### ISSUE THREAD

**Issue by glorsh66** [kenjis/ci-phpunit-test#297]
Is it secure to use my web application with installed ci-phpunit-test?
Or is it better after all tests have been passed to copy the application's file to new fresh CodeIgniter installation?

I mean, as I understand it - it changes some main files....

**Comment by kenjis** [comment]
If nobody can access in your `appliation` via web, your installation with ci-phpunit-test is safe.

ci-phpunit-test does not change any CodeIgniter files. It has modified version of the CodeIgniter files in it.

If you worry, remove `application/tests` in your production.
