### ISSUE TITLE
$assign_to_config lost when resetting instance

### ISSUE THREAD

**Issue by joshkel** [kenjis/ci-phpunit-test#298]
We're using Bootstrap.php / index.php's ability to override config items using the `$assign_to_config` global variable. This works the first time the CodeIgniter instance is initialized, but any assignments are lost if the CodeIgniter instance is reset by calling ci-phpunit-test's `reset_instance()`.

It seems to me that `reset_instance()` should have the same "Do we have any manually set config items in the index.php file?" logic as its [CodeIgniter.php](https://github.com/kenjis/ci-phpunit-test/blob/3f2ea5cde0ee5814aa9402a5291772495f9250e0/application/tests/_ci_phpunit_test/replacing/core/CodeIgniter.php#L224).

I can open a PR to implement this if everyone agrees.

Thank you.

**Comment by kenjis** [comment]
@joshkel I did not know it.
It seems undocumented: https://www.codeigniter.com/user_guide/search.html?q=assign_to_config&check_keywords=yes&area=default
But CI3 still has it: https://github.com/bcit-ci/CodeIgniter/blob/develop/system/core/CodeIgniter.php#L157

If you open a PR, I would merge it.

**Comment by kenjis** [comment]
@joshkel I've made the PR #314.
Dose it work?
