### ISSUE TITLE
Unable to locate the specified class: Session.php

### ISSUE THREAD

**Issue by igorlebedev** [kenjis/ci-phpunit-test#3]
After I do:
$ cd /path/to/codeigniter/
$ cd application/tests/
$ phpunit

I'm getting this error: Unable to locate the specified class: Session.php-sh-4.1

In application, session is configured to autoload as a library ($autoload['libraries'] = array('database', 'session',... ). 

Will be appreciated if you help me to configure application correctly!

**Comment by RodolfoSilva** [comment]
Verify this implementation here https://github.com/kenjis/codeigniter-tettei-apps

**Comment by kenjis** [comment]
What is class `Session.php-sh-4.1`? `-sh-4.1` is strange.

**Comment by igorlebedev** [comment]
RodolfoSilva, I've got an error "Severity: ErrorMessage:  Class 'Bbs' not found",

kenjis, I think maybe it is added by terminal... Forgot to mention, I'm using php 5.6

**Comment by kenjis** [comment]
See https://travis-ci.org/kenjis/codeigniter-tettei-apps/jobs/63829246

All tests passed on PHP 5.6.5.

**Comment by igorlebedev** [comment]
What should I do to help identify where problem is?

**Comment by kenjis** [comment]
I have no idea why you have the error.

Your error message `Unable to locate the specified class:` comes from:
https://github.com/kenjis/ci-phpunit-test/blob/master/application/tests/_ci_phpunit_test/replacing/core/Common.php#L78

**Comment by igorlebedev** [comment]
I'm looking through CI 3.0 file structure, and there is no system/libraries/Session.php file. There is a folder 'Session', and file Session.php placed in it. But in file ~/replacing/core/Common.php no checking if system/libraries folder have subfolders.
https://github.com/bcit-ci/CodeIgniter/tree/3.0.0/system/libraries

That's the point?

**Comment by kenjis** [comment]
I could reproduce the error. Yes, it is the point.

**Comment by kenjis** [comment]
It seems to be better we will change our `get_new_instance()` function.

Current implementation `get_new_instance()` creates `CI_Controller`. At that time, Session is autoloaded. After it, If you create new `CI_Controller`, the controller try to load Session using `load_class()`.

Removing creation of CI_Controller in `get_new_instance()` would solve the problem.

**Comment by kenjis** [comment]
Well, removing creation of CI_Controller in get_new_instance() makes us change our tests a lot.
It seems adding function to load Session to `load_class()` is better.

**Comment by kenjis** [comment]
@RodolfoSilva I've added functionality to load Session library to `load_class()`. How about this?

**Comment by RodolfoSilva** [comment]
@kenjis This is not good, but it solves the problem temporarily.

**Comment by kenjis** [comment]
What's wrong? Better solution?

**Comment by RodolfoSilva** [comment]
Verify this in CI Loader:
```php
1031		// One last attempt. Maybe the library is in a subdirectory, but it wasn't specified?
1032		if ($subdir === '')
1033		{
1034			return $this->_ci_load_library($class.'/'.$class, $params, $object_name);
1035		}
```
This solution is native, but I'm not understand why not work. :cold_sweat: :sob:

**Comment by kenjis** [comment]
The code is replaced in CI PHPUnit Test: https://github.com/kenjis/ci-phpunit-test/blob/master/application/tests/_ci_phpunit_test/replacing/core/Loader.php#L1031-1035

But the code is the exactly same as original CI_Loader.

The code works, but if you create new Controller, `load_class()` is called: https://github.com/bcit-ci/CodeIgniter/blob/develop/system/core/Controller.php#L73-76

But `load_class()` does not have code to load libraries in a subdirectory.

**Comment by kenjis** [comment]
@igorlebedev Does your test work?

**Comment by RodolfoSilva** [comment]
All right, but i have problem with autoload form_validation.

```
Severity: ErrorMessage:  Call to a member function helper() on a non-object
Filename: /var/www/ci-phpunit-test/system/libraries/Form_validation.php
Line Number: 147
```

**Comment by RodolfoSilva** [comment]
Closed #3

**Comment by kenjis** [comment]
@RodolfoSilva It seems your opinion is right. Adding functionality to load Session library to load_class() is not enough.

I've just removed it, and added better solution.

**Comment by kenjis** [comment]
@igorlebedev I fixed this problem.

If you get the error, call `reset_instance()` before creating your controller instance.
