### ISSUE TITLE
restfull api method ended with calling exit function, how to write test for it.

### ISSUE THREAD

**Issue by jeffcao** [kenjis/ci-phpunit-test#30]
Hi,
My project is restful api style.  So, my controller method ended with like below code:
$this->output
	        ->set_status_header(200)
	        ->set_content_type('application/json', 'utf-8')
	        ->set_output($output)
	        ->_display();
	exit;

I wrote a test for this method, but it did not run correctly.
I found the test stopped at  "call_user_func_array" in CIPHPUnitTestRequest/createAndCallController.
Now, i don't know how to go on. 
Please help me, thanks advanced.

**Comment by kenjis** [comment]
See https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#exit

If `exit()` or `die()` in your code are called on running tests, PHP (phpunit) stops.
So it can't be tested.

If you want to test it, you must remove or skip the `exit` somehow.

I don't know your code well, so I don't know this works correclty or not, but ad hoc way to skip `exit` is like below:

~~~php
if (ENVIRONMENT !== 'testing')
{
	exit;
}
~~~

**Comment by jeffcao** [comment]
@kenjis 
Thank you.  
Resolved it with your advice.

**Comment by kenjis** [comment]
I added new functionality that converts `exit` to Exception on the fly. See https://github.com/kenjis/ci-phpunit-test/pull/32

It will be included in v0.5.0.
