### ISSUE TITLE
While uploaded the code into aws server getting error

### ISSUE THREAD

**Issue by joskarthic** [kenjis/ci-phpunit-test#308]
Hi Team,

I have run the cmd in phpunit getting error, 

Your application folder path does not appear to be set correctly. Please open the following file and correct this: Bootstrap.php

my bootstap.php 

$system_path = '/var/www/system';
$application_folder = '/var/www/html';

I have changed manually but after running the above cmd again changed as default.

**Comment by kenjis** [comment]
Fix paths in`application/tests/Bootstrap.php`.
