### ISSUE TITLE
redirect() - url_helper autoload - Cannot modify header information

### ISSUE THREAD

**Issue by lcssanches** [kenjis/ci-phpunit-test#309]
I am trying to test this controller method:
```php
    public function search_applicant($terms=''){
        if(empty($terms)){
            redirect('/admin/activities');
        }
    }
```
Pretty simple so far, just need to redirect if parameter is empty.

This is the test method
```php
class Admin_Activities_test extends TestCase
{
    public function test_Search_Applicant_should_redirect_if_terms_is_empty(){

        $this->mockAuthentication();
        $this->mockAuthorization();

        $output = $this->request('POST', 'admin/activities/search_applicant/');

        $this->assertRedirect('/admin/activities', 302);

    }
}
```

But I am getting this error
```
RuntimeException : Cannot modify header information - headers already sent by (output started at D:\Projetos\sis-main\vendor\phpunit\phpunit\src\Util\Printer.php:109) on line 564 in file D:\Projetos\sis-main\system\helpers\url_helper.php
 D:\Projetos\sis-main\application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php:176
 D:\Projetos\sis-main\system\helpers\url_helper.php:564
 D:\Projetos\sis-main\application\modules\admin\controllers\Activities.php:602
 D:\Projetos\sis-main\application\tests\_ci_phpunit_test\CIPHPUnitTestRequest.php:368
 D:\Projetos\sis-main\application\tests\_ci_phpunit_test\CIPHPUnitTestRequest.php:297
 D:\Projetos\sis-main\application\tests\_ci_phpunit_test\CIPHPUnitTestRequest.php:160
 D:\Projetos\sis-main\application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php:151
 D:\Projetos\sis-main\application\tests\controllers\Admin_Activities_test.php:18
```

Based on documentation, redirect was rewritten, but the test is looking for the default one @ `
 D:\Projetos\sis-main\system\helpers\url_helper.php:564`

If I manually load the url helper, the error goes away.

**But, is there a way to just use the autoload ?**

**Comment by lcssanches** [comment]
OK

I think I found the problem.

When `CIPHPUnitTest.php@84` calls `require __DIR__ . '/replacing/core/CodeIgniter.php';` it will call the `Loader.php`, which will autoload the helpers, models, etc...

In `CIPHPUnitTest.php@86`, which is suppose to `replaceHelpers`, it will not replace `redirect`, as it was already loaded..

Moving `self::replaceHelpers()` to before of `require __DIR__ . '/replacing/core/CodeIgniter.php';` solve the problem.

Any down sides?

**Comment by kenjis** [comment]
@lcssanches Thank you for reporting.
It seems your fix is okay.

I will look into it again for sure.
