### ISSUE TITLE
How to override configuration values?

### ISSUE THREAD

**Issue by aug70** [kenjis/ci-phpunit-test#31]
Is it possible to override CI config values within tests?
E.g. A controller has below code.
    $someValue = $this->config->item("xyz");

Can I override "xyz"'s value inside controller test?
Thank you.

**Comment by kenjis** [comment]
Why do you override?

If you can create config file for testing, create it in `application/config/testing` folder.
Tests always run on `testing` environment.
See https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#testing-environment

If you want to change the value dynamically, you might change it with `$this->request->setCallable()`.
See https://github.com/kenjis/ci-phpunit-test/blob/master/docs/FunctionAndClassReference.md#request-setcallable

~~~php
$this->request->setCallable(
    function ($CI) {
        $CI->config->set_item('xyz', 'new value');
    };
);
$output = $this->request('GET', 'welcome/index');
~~~

But the callable code runs after controller instantiation. That is you can't change the value inside controller constructor.

**Comment by aug70** [comment]
@kenjis thank you, that solves the problem.
