### ISSUE TITLE
upgrading to phpunit 8.4.3 - issue with stubbing.

### ISSUE THREAD

**Issue by pgee70** [kenjis/ci-phpunit-test#315]
Using versions: CI 3.1.11,  ci-phpunit-test v0.17.0, phpunit 8.4.3

This may not be an issue, but I am having trouble understanding what is happening.
my SUT code for a migration controller method called current:
````
  public function current()
  {
    $output = $this->migration->current();
    if ($output === FALSE)
    {
      $error = $this->migration->error_string();
      $this->output->append_output("The migration failed! with error:'{$error}'");
    }
    elseif ($output === TRUE)
    {
      $this->output->append_output('No migrations were found!');
    }
    else
    {
      $this->output->append_output("The migration call was successful, and the current version is $output");
    }
  }
````

my testing code:

````
 /**
   *
   * @dataProvider current_provider
   *
   * @param $expected
   * @param $value
   */
  public function test_current($expected, $value)
  {
    $this->request->setCallable(
      function($CI) use ($value)
      {
        $CI->load->library('migration');
        $stub = $this->getMockBuilder('migration')
                     ->setMethods(['current', 'error_string'])
                     ->getMock();
        $stub->method('current')
             ->willReturn($value);
        $stub->method('error_string')
             ->willReturn('error');
        $CI->migration = $stub;
      }
    );
    $output = $this->request('GET', 'migrate/current');
    $this->assertEquals($expected, $output);
  }

  /**
   * @return array
   */
  public function current_provider()
  {
    return [
      'error'             => ['The migration failed! with error:\'error\'', FALSE],
      'no migrations'     => ['No migrations were found!', TRUE],
      'migration success' => ['The migration call was successful, and the current version is 88', 88]
    ];
  }
````

with the migration to phpunit 7 to phpunit 8  setMethods is now deprecated. In other parts of my code i have substituted this with the onlyMethods call, which in all other cases has worked fine.

There is something about the method being called from $this->request->setCallable that makes the migrations library not visible to the onlyMethods reflection code.  I have tried explicitly adding a call to $CI->load->library('migration') in the generator function but it doesn't help - the code trace returns that the library is not loaded a second time.
If I use the onlyMethods call instead of getMethods I get:
````
 ⚠ Current with error
   ┐
   ├ Class migration does not exist
   ┴

 ⚠ Current with no·migrations
   ┐
   ├ Class migration does not exist
   ┴

 ⚠ Current with migration·success
   ┐
   ├ Class migration does not exist
   ┴
````
The difference between the older setMethods and the onlyMethods methods is that onlyMethods makes sure that the class method exists using reflection.

Any ideas what is going on?

**Comment by kenjis** [comment]
@pgee70 

```
        $stub = $this->getMockBuilder('migration')
```

The `'migration'` is right? `CI_Migration::class`?

**Comment by pgee70** [comment]
yes

**Comment by kenjis** [comment]
The `migration` in `$this->load->library('migration')` is not a class name.
`getMockBuilder()` needs a class name.

What if you do?
```php
$stub = $this->getMockBuilder(CI_Migration::class)
```

**Comment by pgee70** [comment]
Thanks, that was it.
