### ISSUE TITLE
TestCase Not Found

### ISSUE THREAD

**Issue by rajeev-singh-github** [kenjis/ci-phpunit-test#316]
Stuck because of TestCase Not found issue.
Version Details
PHP - 7.3.8
CI - 3.1.11
PHPUNIT - 8.4
ci-phpunit-test - 2.x
xampp - 3.2.4

In config
$config['composer_autoload'] = '../../vendor/autoload.php';

application/tests/controllers/Hello_test.php
```php
<?php

class Hello_test extends TestCase{
    
    public function test_get_hello(){
        $output = $this->request('GET', ['Hello', 'get_hello']);
        $expected = '<h2>Hello Test</h2>';
        $this->assertEquals($expected, $output);
    }

}
```

Getting Error : - PHP Fatal error:  Uncaught Error: Class 'TestCase' not found

execution
while in root folder  and hit
1. vendor/bin/phpunit application/tests/controllers/Hello_test.php
2. php vendor/phpunit/phpunit/phpunit application/tests/controllers/Hello_test.php

Any help would be appreciable.
Thank you very much.

**Comment by kenjis** [comment]
What if?
```
$ vendor/bin/phpunit -c application/tests/
```
