### ISSUE TITLE
Declaration … should be compatible warnings.

### ISSUE THREAD

**Issue by linnaingcmm** [kenjis/ci-phpunit-test#325]
In my test execution result, I got below Exception message.

`RuntimeException: Declaration of Account_ImportFile::validate($recode) should be compatible with Form::validate()`

I know the error message came out due to childClass::validate($recode) has different arguments of parentClass::validate().
If I change to my code to childClass::validate($recode = null), there is no error to occur.
Test execution finished normally.

Could you show me if there is a way to fix the problem without changing anything?

Thank you.

**Comment by kenjis** [comment]
Can you catch the exception?

> Another problem is Project Owner don't want to change any code of current project.

It might be the real problem is the project owner :-)

**Comment by linnaingcmm** [comment]
> Can you catch the exception?
> 
> > Another problem is Project Owner don't want to change any code of current project.
> 
> It might be the real problem is the project owner :-)

I can't catch the exception.
PhpUnit test execution is stop when the above the "RuntimeException: Declaration" is  occur.

**Comment by kenjis** [comment]
@linnaingcmm What if you use `$this->warningOff()`?
https://github.com/kenjis/ci-phpunit-test/blob/master/docs/FunctionAndClassReference.md#testcasewarningoff
