### ISSUE TITLE
RuntimeException: stat(): stat failed with MonkeyPatchManager setting

### ISSUE THREAD

**Issue by linnaingcmm** [kenjis/ci-phpunit-test#326]
Test execution working normally without MonkeyPatchManager setting of `Bootstrap` file.
There we are using smarty template.

Could you teach me any suggestion about this issue?

```
1) User_controller_test::test_index_method_valid
RuntimeException: stat(): stat failed for /var/www/app/application/cache/smarty/compiled/b6b0eeb762ca9ed46ad1769d2ac2ff580605dfab.file.index.tpl.php on line 129 in file /var/www/app/tests/_ci_phpunit_test/patcher/IncludeStream.php
```

Thank you.

**Comment by kenjis** [comment]
> Test execution working normally without MonkeyPatchManager setting of Bootstrap file.

What do you mean exactly?
Like this?
"If you turn off the monkey patch, test execution is working normally.
But if you turn it on, the error occurs."

Check the permission of the `/var/www/subscription/application/cache/smarty/compiled/b6b0eeb762ca9ed46ad1769d2ac2ff580605dfab.file.index.tpl.php`.

**Comment by linnaingcmm** [comment]
> > Test execution working normally without MonkeyPatchManager setting of Bootstrap file.
> 
> What do you mean exactly?
> Like this?
> "If you turn off the monkey patch, test execution is working normally.
> But if you turn it on, the error occurs."
> 
> Check the permission of the `/var/www/subscription/application/cache/smarty/compiled/b6b0eeb762ca9ed46ad1769d2ac2ff580605dfab.file.index.tpl.php`.

yes sure,

After I changed the permission of the file, it got **same error** above as.

**Comment by kenjis** [comment]
@linnaingcmm 
> After I changed the permission of the file, it got same error above as.

What did you do? How did you change it?
And what changed?

```shell
$ ls -l /var/www/subscription/application/cache/smarty/compiled/b6b0eeb762ca9ed46ad1769d2ac2ff580605dfab.file.index.tpl.php
```
Please show me the output.

**Comment by linnaingcmm** [comment]
@kenjis 

I changed the compiled file permission of smarty library.

`public $_file_perms = 0644;  -> public $_file_perms = 0777;  `

And try to execute again without `MonkeyPatchManager` of bootstrap.
The result is 
`-rwxrwxrwx. 1 48 48 13972 Mar  6 12:47 eaf8b719b19f49485cb0371208cb94851b044eba.file.index.tpl.php`

PhpUnit Test execution was finished without error.


And I turn `MonkeyPatchManager`  on of bootstrap, the error occurs."

Thank you.

**Comment by kenjis** [comment]
@linnaingcmm 
> -rwxrwxrwx. 1 48 48 13972 Mar 6 12:47 eaf8b719b19f49485cb0371208cb94851b044eba.file.index.tpl.php

Check the setting of SELinux.
SELinux might prevent to access that file.

**Comment by linnaingcmm** [comment]
@kenjis 
Thank you.
I made `SELinux` to disabled permanently with below way.
`/etc/selinux/config file and set the SELINUX mod to disabled`

```
[root@localhost containers]# sestatus
SELinux status:                 disabled
```


It is same error.
`RuntimeException: stat(): stat failed for /var/www/subscription/application/cache/smarty/compiled/1c7c7f1d9c21633b56cb0ae375d01bebf4ae6c61.file.login.tpl.php on line 127 in file /var/www/subscription/unittests/_ci_phpunit_test/patcher/IncludeStream.php`

Is there any problem with Docker?

**Comment by linnaingcmm** [comment]
@kenjis 

The problem solved.
The problem is version compatibility of `PHP and Smarty.`

Thank you.
