### ISSUE TITLE
No any response data for testing of function that include exit($data_body) in API.

### ISSUE THREAD

**Issue by linnaingcmm** [kenjis/ci-phpunit-test#330]
@kenjis 

Could I make testing of function that include` exit($data_body)`?

Now, I only can making testing by status code.
There any response data I can't get.

If I changed from `exit($data_body) to echo $data_body`, I get response all data.

```php
function response(){
   $data_body = $this->_encode_body($data, $this->output_format);
   exit($data_body );
}


function test_get_data(){
      try {

            $this->request->setHeader('Content-Type', 'application/json');
            $output = $this->request('POST', 'api/v1.0/test/get_upsert_data', $data_json);
            //$ouput is empty
          } catch (CIPHPUnitTestExitException $e) {
            $output = ob_get_clean();
            //$ouput is empty
          }

          $this->assertResponseCode(200);
}

```

Thank you.

**Comment by kenjis** [comment]
@linnaingcmm Check `$e->exit_status`.

**Comment by linnaingcmm** [comment]
@kenjis 

> $e->exit_status

The checked the` $e->exit_status`  like as below.
Output result is nothing.
Test execution is not entering to`catch` block.


```php

function test_get_data(){
      try {

            $this->request->setHeader('Content-Type', 'application/json');
            $output = $this->request('POST', 'api/v1.0/test/get_upsert_data', $data_json);
            //$ouput is empty
          } catch (CIPHPUnitTestExitException $e) {
            $output = ob_get_clean();
            log_message('info', $e->exit_status);
            //$ouput is empty
          }
          $this->assertResponseCode(200);
}

```

**Comment by kenjis** [comment]
@linnaingcmm 
> Test execution is not entering tocatch block.

Configure monkey patch (exit patcher) correctly.

**Comment by linnaingcmm** [comment]
@kenjis 

> @linnaingcmm
> 
> > Test execution is not entering tocatch block.
> 
> Configure monkey patch (exit patcher) correctly.

I made configure for it correctly.
I am using it  for other test items also.

Thank you.

**Comment by kenjis** [comment]
@linnaingcmm You should find out why it does not go into the `catch` block.
For example, debug by step execution.

If you write right tests, it goes into the `catch` block.
