### ISSUE TITLE
$CI =& get_instance(); return null in createAndCallController function in CIPHPUnitTestRequest.php

### ISSUE THREAD

**Issue by biechao** [kenjis/ci-phpunit-test#332]
In CIPHPUnitTestRequest.php there is a function createAndCallController funtion.
When I try to test my controller with code:

```php
class Saml_test extends TestCase
{

	public function test_ut_test()
	{
		$output = $this->request('GET', "saml/ut_test");
		$this->assertContains('1', $output);
	}

}
```

I got this error message in console:
> Saml_test::test_ut_test
> RuntimeException: Argument 1 passed to CIPHPUnitTestCase::setCI() must be an instance of CI_Controller, instance of CIPHPUnitTestNullCodeIgniter given, called in xxx

After further debugging, I found this function return null, and it supposes to return an instance of CI.

```php
		// Create controller
		if (CIPHPUnitTest::wiredesignzHmvcInstalled())
		{
			new CI();
		}
		$controller = new $class;
		$CI =& get_instance();
		**// The $CI is null here**
		// Set CodeIgniter instance to TestCase
		$this->testCase->setCI($CI);

```

**Comment by kenjis** [comment]
@biechao Read the error message carefully, so you might have any clue.

**Comment by biechao** [comment]
@kenjis, thanks for your reply, I just change my example code as below:
`class Saml_test extends TestCase
{

        public function test_ut_test()
        {
                $this->resetInstance();
                $output = $this->request('GET', "saml/ut_test");
                $this->assertContains('1', $output);
        }

}
`

My controller just defined this function:

`
public function ut_test(){
        return 1;
    }
`

And it shows this error message to me:

There was 1 error:
Saml_test::test_ut_test
RuntimeException: Argument 1 passed to CIPHPUnitTestCase::setCI() must be an instance of CI_Controller, instance of CIPHPUnitTestNullCodeIgniter given, called in xxxx

**Comment by kenjis** [comment]
@biechao  I don't know why the `$CI` is null.
And the error message says the argument is `CIPHPUnitTestNullCodeIgniter`, not null.
