### ISSUE TITLE
Is there any way to extends PHPUnit_Extensions_Database_TestCase in TestCase for database test purpose

### ISSUE THREAD

**Issue by biechao** [kenjis/ci-phpunit-test#333]
I try to extend PHPUnit_Extensions_Database_TestCase in my model instead of TestCase, but it can not use below code any more
```
        $this->resetInstance();
        $this->CI->load->model('Cousin_domain_model');
        $this->obj = $this->CI->Cousin_domain_model; 
```
I also try to extend PHPUnit_Extensions_Database_TestCase in TestCase or CIPHPUnitTest class, but I failed since it will always report some error.
I just want to do database test like this: 
https://phpunit.de/manual/6.5/en/database.html

Is there any way I can do this?
Thanks in advance for any suggestions

**Comment by kenjis** [comment]
ci-phpunit-test does not support `PHPUnit_Extensions_Database_TestCase`.
And it is very old class that is not used now.

> I just want to do database test like this:
https://phpunit.de/manual/6.5/en/database.html

Did you do as the manual says (`use PHPUnit\DbUnit\TestCaseTrait;`)? What error do you have?

**Comment by biechao** [comment]
@kenjis I am using an old version of PHPUnit(4.8.36), so it does not support  `PHPUnit\DbUnit\TestCaseTrait`, I will find another way to do DB test.
Thank you.

**Comment by kenjis** [comment]
@biechao To use `PHPUnit_Extensions_Database_TestCase`, you must implement a TestCase class that extends `PHPUnit_Extensions_Database_TestCase` and implements all functionality in `CIPHPUnitTestCase`.

**Comment by biechao** [comment]
@kenjis I have found my own way to do the DB test.
I was wondering is there a test result report page just like the coverage report page?
It may be a simple page to just show how many test cases passed/failed for each module/controllers.
The coverage report page is awesome, but do I need to parse the junit.xml to generate my own test report page?

**Comment by kenjis** [comment]
@biechao I don't know.

**Comment by kenjis** [comment]
ci-phpunit-test database testing functionality:
- https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#database-seeding
- https://github.com/kenjis/ci-phpunit-test/blob/master/docs/FunctionAndClassReference.md#class-dbtestcase
