### ISSUE TITLE
About Constant IP Already Defined

### ISSUE THREAD

**Issue by DisAppear7** [kenjis/ci-phpunit-test#334]
i get some error about constant has been defined when i run phpunit ,please give me some suggestion about it

**Comment by kenjis** [comment]
@DisAppear7 For example, if you call `define("CONSTANT", "Hello world.");` twice, you get the error. It is the language specification.

When you run phpunit, all tests run in a single process. 2 or more controllers may run in a single process. It may call the same `define()` more than once.

In that case, you can avoid it if you change your code like this:
```php
if (! defined('CONSTANT')) {
	define("CONSTANT", "Hello world.");
}
```

**Comment by DisAppear7** [comment]
oh，Thank you so much
