### ISSUE TITLE
About cache problem！

### ISSUE THREAD

**Issue by DisAppear7** [kenjis/ci-phpunit-test#335]
when i run phpunit , the progress request my method twice ,this code will break down my phpunit process in secend times, but first time is OK,  has anyone encountered the same problem as me?
`$CI = &get_instance();`
`$data = $CI->cache->get("textCacheKey");`

**Comment by kenjis** [comment]
Sorry, I don't understand your problem.
If you still have the issue, feel free to reopen and add more details.
