### ISSUE TITLE
Cannot redeclare class User_model in phpunit

### ISSUE THREAD

**Issue by DisAppear7** [kenjis/ci-phpunit-test#337]
when i run phpunit in a process ,i got a warm about Cannot redeclare class User_model,because i load this model in two different method ,but phpunit is in a process,how can i deal with it

**Comment by kenjis** [comment]
@DisAppear7 How many times you load one model, you don't have to *declare* the model class more than once.
Do you `require` the class somewhere?
How do you load the class?

**Comment by pgee70** [comment]
i left a request to not warn when model is re-declared.
For me this is because i load models in the test's setUp() function so i don't need to repeat my code.
my fix is to just change the file `vendor/kenjis/ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/core/Loader.php`

from 

```
$CI =& get_instance();
if (isset($CI->$name))
{
  throw new RuntimeException('The model name you are loading is the name of a resource that is already being used: '.$name);
}
```

to:

```
$CI =& get_instance();
if (isset($CI->$name))
{
  return $this;
}
```

**Comment by kenjis** [comment]
#341

**Comment by kenjis** [comment]
@pgee70 In your case, can't you use `UnitTestCase::newModel()`?
https://github.com/kenjis/ci-phpunit-test/blob/master/docs/FunctionAndClassReference.md#unittestcasenewmodelclassname
