### ISSUE TITLE
Prevent model loading throwing 'The model name you are loading is the name of a resource that is already being used' exception

### ISSUE THREAD

**Issue by pgee70** [kenjis/ci-phpunit-test#341]
Hi This is a feature request.
attempting to load a model that is already loaded throws a 'The model name you are loading is the name of a resource that is already being used' RuntimeException.
while it isn't ideal to load a model in CI twice, it also doesn't really hurt.
I request instead of throwing a RuntimeException, It would be preferable to issue an INFO, or 'DEBUG' warning.

**Comment by kenjis** [comment]
You don't need to load a model twice.
Fixing application code is better.
