### ISSUE TITLE
Class Not Found How do I solve this?

### ISSUE THREAD

**Issue by sunggun1** [kenjis/ci-phpunit-test#345]
I have application_common which is for both pc and mobile version of my company's website
There are
'refactoring/application_common'
'refactoring/application_pc'
'refactoring/application_mobile'

Each directory has a MVC pattern 

I downloaded ci-phpunit-test on
'refactoring/application_common/tests'

This is a test code in
'refactoring/application_common/tests/controllers/Email_test' 

    <?php
    use OFM_COMMON\Tests\Service\Service;
    class Email_test extends TestCase
    {
        private $service;
        private $obj;
        
        public function setUp(){
        $this->assertInstanceOf(Service::class,Service::test_find_login_email());
        }

        public function test_find_login_email(){
            $this->obj->find_login_email();
            $this->assertEmpty($this->obj->find_login_email());
        }
    }

Service Code
'refactoring/application_common/tests/service/Service' 

    <?php
    namespace OFM_COMMON\Tests\Service;
    
    use OFM_COMMON\Models\Account\Account;
    use CI_Model;
    
    
    class Service extends CI_Model
    {
        private $obj;
        public function __construct()
        {
            parent::__construct();
            $this->load->database();
            $this->CI =& get_instance();
            $this->CI->load->model('Account/Account','Account');
            $this->obj = $this->CI->Account;
        }
    
        private function find_login_email(){
            $result = $this->obj ->find_login_email('Kevin','01012345678');
            return $result;
        }
    }

Account Model is on 
'refactoring/application_common/models/Account/Account.php'

Error is like

    Configuration read from D:\refactoring\application_common\tests\phpunit.xml
    
    PHP Fatal error:  Class 'OFM_COMMON\Tests\Service\Service' not found in 
    D:\refactoring\application_common\tests\controllers\Email_test.php on line 9
    PHP Stack trace:
    PHP   1. {main}() C:\xampp\php\phpunit:0
    PHP   2. PHPUnit_TextUI_Command::main() C:\xampp\php\phpunit:46
    PHP   3. PHPUnit_TextUI_Command->run() C:\xampp\php\pear\PHPUnit\TextUI\Command.php:129
    PHP   4. PHPUnit_TextUI_TestRunner->doRun() C:\xampp\php\pear\PHPUnit\TextUI\Command.php:176
    PHP   5. PHPUnit_Framework_TestSuite->run() C:\xampp\php\pear\PHPUnit\TextUI\TestRunner.php:349
    PHP   6. PHPUnit_Framework_TestSuite->run() C:\xampp\php\pear\PHPUnit\Framework\TestSuite.php:705
    PHP   7. PHPUnit_Framework_TestSuite->runTest() C:\xampp\php\pear\PHPUnit\Framework\TestSuite.php:745
    PHP   8. PHPUnit_Framework_TestCase->run() C:\xampp\php\pear\PHPUnit\Framework\TestSuite.php:775
    PHP   9. PHPUnit_Framework_TestResult->run() C:\xampp\php\pear\PHPUnit\Framework\TestCase.php:776
    PHP  10. PHPUnit_Framework_TestCase->runBare() C:\xampp\php\pear\PHPUnit\Framework\TestResult.php:648
    PHP  11. Email_test->setUp() C:\xampp\php\pear\PHPUnit\Framework\TestCase.php:828

I typed 
        'cd application_common/tests'
        'phpunit'

PHPUnit is on
'refactoring/application_common/tests/phpunit.xml'

    	    <phpunit
    	    	bootstrap="./Bootstrap.php"
    		backupGlobals="true"
    		colors="true">
    		<testsuites>
    			<testsuite name="CodeIgniter Application Test Suite">
    				<directory suffix="test.php">./</directory>
    				<exclude>./_ci_phpunit_test/</exclude>
    			</testsuite>
    		</testsuites>
    		<filter>
    			<whitelist>
    				<directory suffix=".php">../controllers</directory>
    				<directory suffix=".php">../../application_pc/model</directory>
    				<directory suffix=".php">../../application_m/model</directory>
    				<directory suffix=".php">../../application_common/model</directory>
    				<directory suffix=".php">./models</directory>
    				<directory suffix=".php">./views</directory>
    				<directory suffix=".php">./libraries</directory>
    				<directory suffix=".php">./helpers</directory>
    				<directory suffix=".php">./hooks</directory>
    				<directory suffix=".php">service</directory>
    				<directory suffix=".php">../../application_pc</directory>
    				<directory suffix=".php">../../application_common</directory>
    				<directory suffix=".php">../../application_m</directory>
    				<directory suffix=".php">../../application_sm</directory>
    				<directory suffix=".php">../../application_file</directory>
    				<directory suffix=".php">../../application_job</directory>
    			</whitelist>
    		</filter>
    		<logging>
    			<log type="coverage-html" target="build/coverage"/>
    			<log type="coverage-clover" target="build/logs/clover.xml"/>
    			<log type="junit" target="build/logs/junit.xml"/>
    	    	</logging>
    	</phpunit>

**Comment by kenjis** [comment]
@sunggun1 
> PHP Fatal error:  Class 'OFM_COMMON\Tests\Service\Service' not found in 
D:\refactoring\application_common\tests\controllers\Email_test.php on line 9

How do you load the `OFM_COMMON\Tests\Service\Service` class?
Do you have an autoloader for it?
It seems you don't have an autoloader.

**Comment by sunggun1** [comment]
@kenjis What is an autoloader? How do I set it?

**Comment by sunggun1** [comment]
IF I do like this

![image](https://user-images.githubusercontent.com/17981550/91386724-99a51180-e86e-11ea-9950-2fd6a47d68e6.png)

Then , error exist like this
![image](https://user-images.githubusercontent.com/17981550/91386749-a9bcf100-e86e-11ea-8533-c0492e31689b.png)

**Comment by kenjis** [comment]
@sunggun1 
> What is an autoloader?

PHP does not have class autoloader. You have to write it by yourself.
See https://www.php.net/manual/en/language.oop5.autoload.php

Or you can use thrid-party autoloader like Composer autoloader.

**Comment by kenjis** [comment]
@sunggun1 The autoloader of ci-phpunit-test does not support namespaced classes.

**Comment by kenjis** [comment]
@sunggun1 
![image](https://user-images.githubusercontent.com/17981550/91386749-a9bcf100-e86e-11ea-8533-c0492e31689b.png)

It seems your test runs perfectly. The error is because of your model code.

**Comment by sunggun1** [comment]
Error : 
![image](https://user-images.githubusercontent.com/17981550/91410295-a97a2100-e881-11ea-945e-ceeff2ef2c1b.png)


Function : 

![image](https://user-images.githubusercontent.com/17981550/91410317-b139c580-e881-11ea-9f50-b09d92a9e81a.png)


Model : 
application_common/models/Account/Account

    <?php
    namespace OFM_COMMON\Models\Account;

    class Account extends \CI_Model{
        public function __construct()
        {
            parent::__construct();
            $this->load->helper('datetime');
            $this->load->helper('url');
            $this->load->database();
        }
    `
        public function find_login_email($name, $phone){
            $sql = "SELECT USER_EMAIL_ADDR
                    FROM 
                        user_info ui
                    WHERE 
                        ui.USE_YN = 'Y' AND ui.USER_NM =:USER_NM AND ui.USER_CEL_NO =:USER_CEL_NO
                    ";
    
            $query = $this->db->prepare($sql)
                    ->bind('USER_NM', $name)
                    ->bind('USER_CEL_NO', $phone)
                    ->execute(null, true);
    
            return $query->result_array();
            }
        }

applicaion_common model can reach to pc and mobile
I tested on 
pc (which is now on application_pc/models and can be approached into the mode files ) environment

**Comment by sunggun1** [comment]
![image](https://user-images.githubusercontent.com/17981550/91409709-c19d7080-e880-11ea-9374-5bd274ed1cee.png)

**Comment by kenjis** [comment]
@sunggun1 Can you load the model `Account` when you call it via web (not in testing)?
If my memory is correct, CodeIgniter3 does not support namespaced model classes.

**Comment by sunggun1** [comment]
Uhmm.. I found out APPPATH was only 'application_pc/'
 so I added 'application_common/' with array_push();

![image](https://user-images.githubusercontent.com/17981550/91533822-83b94e80-e94b-11ea-9006-a9725db7189e.png)

**Comment by kenjis** [comment]
@sunggun1 It seems that is not a problem of ci-phpunit-test, but a problem of your customized CodeIgniter.
