### ISSUE TITLE
Fatal error: Cannot redeclare spl_autoload_register() 

### ISSUE THREAD

**Issue by CaptainATG** [kenjis/ci-phpunit-test#353]
adding this function to config.php

```php
function spl_autoload_register($class)
{
    if (strpos($class, 'CI_') !== 0) {
        if (file_exists($file = APPPATH . 'core/' . $class . '.php'))
            include $file;
        elseif (file_exists($file = APPPATH . 'libraries/' . $class . '.php'))
            include $file;
        elseif (file_exists($file = APPPATH . 'third_party/' . $class . '.php'))
            include $file;
    }
}
```

Fatal error: Cannot redeclare spl_autoload_register() in C:\xampp\htdocs\homedir\login.gmp-solutions.net\application\config\config.php on line 537

**Comment by kenjis** [comment]
You cannot redeclare PHP native functions.
https://www.php.net/manual/en/function.spl-autoload-register.php

**Comment by CaptainATG** [comment]
what am i going to do sir kenjis?

**Comment by kenjis** [comment]
@CaptainATG What do you want to do?
