### ISSUE TITLE
Running the test prints the actual response of the API I am testing.

### ISSUE THREAD

**Issue by roGreenRock** [kenjis/ci-phpunit-test#357]
When I run:
`./phpunit.sh --debug`

or

`./phpunit.sh`

Instead of showing the RESULT of the TEST, it gives me the ACTUAL response of the API.

Here is my controller:

Invoices.php
```php
function another_sample_get()
{
     $response = $this->invoice->sample_lib();
     $this->response(['data' => $response], RestController::HTTP_OK);
}
```

My library:
Invoice.php
```php
function sample_lib()
{
      return 'Hello World';
}
```

My Unit test:
Invoices_test.php
```php
public function test_another_sample_get()
    {
        $this->request->setHeader('Authorization', <token>);
        $data = $this->request('GET', '/invoices/another_sample');

        $this->assertEquals("data", $data);
    }
```

Expected Result:
For the result of the TEST to be displayed; I expect a Failed result.

Actual Result:
The actual response data of the API is displayed instead.

**Comment by kenjis** [comment]
If you use CodeIgniter RestServer, it calls `exit()` and phpunit itself dies.

See <https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#codeigniter-rest-server>.

**Comment by roGreenRock** [comment]
@kenjis thanks for the reply. I have already uncommented the MonkeyPatch and add the block of code like so:

```
try
{
    // Call controller method
    call_user_func_array([$controller, $method], $params);
}
catch (CIPHPUnitTestExitException $ex)
{
    throw $ex;
}

```

However, I am getting the error below:
```
Warning: Uncaught LogicException: Replacement data still remain in /Users/me/Sites/api/application/tests/_ci_phpunit_test/patcher/3.x/Patcher/FunctionPatcher.php:204
Stack trace:
#0 /Users/me/Sites/api/application/tests/_ci_phpunit_test/patcher/3.x/Patcher/AbstractPatcher.php(45): Kenjis\MonkeyPatch\Patcher\FunctionPatcher::generateNewSource('<?php\n/**\n * Pa...')
#1 /Users/me/Sites/api/application/tests/_ci_phpunit_test/patcher/3.x/MonkeyPatchManager.php(326): Kenjis\MonkeyPatch\Patcher\AbstractPatcher->patch('<?php\n/**\n * Pa...')
#2 /Users/me/Sites/api/application/tests/_ci_phpunit_test/patcher/3.x/MonkeyPatchManager.php(289): Kenjis\MonkeyPatch\MonkeyPatchManager::execPatchers('<?php\n/**\n * Pa...')
#3/Users/me/Sites/api/application/tests/_ci_phpunit_test/patcher/IncludeStream.php(57): Kenjis\MonkeyPatch\MonkeyPatchManager::patch('/Users/me.. in /Users/me/Sites/api/application/tests/_ci_phpunit_test/patcher/3.x/Patcher/FunctionPatcher.php on line 204
PHP Fatal error:  CIPHPUnitTest::init(): Failed opening required '/Users/me/Sites/api/application/tests/_ci_phpunit_test/replacing/core/Common.php' (include_path='.:/usr/local/Cellar/php@7.3/7.3.26_1/share/php@7.3/pear') in /Users/me/Sites/api/application/tests/_ci_phpunit_test/CIPHPUnitTest.php on line 69
```

**Comment by kenjis** [comment]
Try this:

`REST_Controller`
```php
        catch (CIPHPUnitTestExitException $ex)
        {
            echo ob_get_clean();
            throw $ex;
        }
```

**Comment by kenjis** [comment]
@roGreenRock What's your environment?

- CodeIgniter version
- CodeIgniter RestServer version
- ci-phpunit-test version
- PHP version
- PHPUnit version

**Comment by roGreenRock** [comment]
@kenjis I get the same error: 

PHP Warning:  Uncaught LogicException: Replacement data still remain in /Users/me/Sites/api/application/tests/_ci_phpunit_test/patcher/3.x/Patcher/FunctionPatcher.php:204
Stack trace:
#0 /Users/me/Sites/api/application/tests/_ci_phpunit_test/patcher/3.x/Patcher/AbstractPatcher.php(45): Kenjis\MonkeyPatch\Patcher\FunctionPatcher::generateNewSource('<?php\n/**\n * Pa...')
#1 /Users/me/Sites/api/application/tests/_ci_phpunit_test/patcher/3.x/MonkeyPatchManager.php(326): Kenjis\MonkeyPatch\Patcher\AbstractPatcher->patch('<?php\n/**\n * Pa...')
#2 /Users/me/Sites/api/application/tests/_ci_phpunit_test/patcher/3.x/MonkeyPatchManager.php(289): Kenjis\MonkeyPatch\MonkeyPatchManager::execPatchers('<?php\n/**\n * Pa...')
#3 /Users/me/Sites/api/tests/_ci_phpunit_test/patcher/IncludeStream.php(57): Kenjis\MonkeyPatch\MonkeyPatchManager::patch('/Users/me.. in /Users/me/Sites/api/application/tests/_ci_phpunit_test/patcher/3.x/Patcher/FunctionPatcher.php on line 204

Warning: Uncaught LogicException: Replacement data still remain in /Users/me/Sites/api/application/tests/_ci_phpunit_test/patcher/3.x/Patcher/FunctionPatcher.php:204
Stack trace:
#0 /Users/me/Sites/api/application/tests/_ci_phpunit_test/patcher/3.x/Patcher/AbstractPatcher.php(45): Kenjis\MonkeyPatch\Patcher\FunctionPatcher::generateNewSource('<?php\n/**\n * Pa...')
#1 /Users/me/Sites/api/application/tests/_ci_phpunit_test/patcher/3.x/MonkeyPatchManager.php(326): Kenjis\MonkeyPatch\Patcher\AbstractPatcher->patch('<?php\n/**\n * Pa...')
#2 /Users/me/Sites/api/application/tests/_ci_phpunit_test/patcher/3.x/MonkeyPatchManager.php(289): Kenjis\MonkeyPatch\MonkeyPatchManager::execPatchers('<?php\n/**\n * Pa...')
#3 /Users/me/Sites/api/application/tests/_ci_phpunit_test/patcher/IncludeStream.php(57): Kenjis\MonkeyPatch\MonkeyPatchManager::patch('/Users/me.. in /Users/me/Sites/api/application/tests/_ci_phpunit_test/patcher/3.x/Patcher/FunctionPatcher.php on line 204
PHP Fatal error:  CIPHPUnitTest::init(): Failed opening required '/Users/me/Sites/api/application/tests/_ci_phpunit_test/replacing/core/Common.php' (include_path='.:/usr/local/Cellar/php@7.3/7.3.26_1/share/php@7.3/pear') in /Users/me/Sites/api/application/tests/_ci_phpunit_test/CIPHPUnitTest.php on line 69

Fatal error: CIPHPUnitTest::init(): Failed opening required '/Users/me/Sites/api/application/tests/_ci_phpunit_test/replacing/core/Common.php' (include_path='.:/usr/local/Cellar/php@7.3/7.3.26_1/share/php@7.3/pear') in /Users/me/Sites/api/application/tests/_ci_phpunit_test/CIPHPUnitTest.php on line 69

**Comment by roGreenRock** [comment]
CodeIgniter version: 3.1.5
CodeIgniter RestServer version: 3.1.1
ci-phpunit-test version: v0.18.0
PHP version: 7.3.26
PHPUnit version: 7.5.20

**Comment by roGreenRock** [comment]
@kenjis  are my packages incompatible?

**Comment by kenjis** [comment]
I don't know. I have never used CodeIgniter RestServer 3.1.1.

**Comment by roGreenRock** [comment]
@kenjis  do you think I should downgrade?

**Comment by kenjis** [comment]
Your error message is the same as #340
But it seems you are using php-parser 3.x.

**Comment by roGreenRock** [comment]
Oh okay. I'll just try to play around more.

**Comment by roGreenRock** [comment]
Hi. Update. So I tried to use the version 2.8.0 for the RestSErver instead of the 3.1.1.
However, I am still encountering the same error. Is it normal that its hightlighted in red?
Do I need to import something?

This is the REST_Controller.php file:
![Screen Shot 2021-02-03 at 8 34 38 PM](https://user-images.githubusercontent.com/56145613/106747771-504bc000-665f-11eb-8e87-fe6645dcfb48.png)

**Comment by kenjis** [comment]
I recommend you read the PHP Manual.

PHP: Namespaces overview - Manual
https://www.php.net/manual/en/language.namespaces.rationale.php

**Comment by kenjis** [comment]
But the error comes from MonkeyPatch.
There may be something wrong with MonkeyPatch.

**Comment by kenjis** [comment]
@roGreenRock You can't use PHP-Parser 3.x.

> PHP version: 7.3.26

> Documentation for version 3.x (unsupported; for running on PHP >= 5.5; for parsing PHP 5.2 to PHP 7.2).
https://github.com/nikic/PHP-Parser

**Comment by kenjis** [comment]
If you still have this problem, feel free to reopen.
