### ISSUE TITLE
Create a session to authenticate 

### ISSUE THREAD

**Issue by ayokay123** [kenjis/ci-phpunit-test#358]
I would like to perform some tests on authenticated routes how can I set the session to do tests

**Comment by kenjis** [comment]
Like this?
https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/094be665c65800e7f934d587899f858eb0c4e633/application/tests/controllers/Sessions_test.php#L26-L36

**Comment by ayokay123** [comment]
yes I have done that, but for me, it keeps redirecting me to the sign-in page for some reason.

**Comment by kenjis** [comment]
Can you show steps to reproduce?

**Comment by ayokay123** [comment]
```
public function test_index_authenticated()
    {
        $this->request->setCallable(
            function ($CI) {
                $CI->session->member_id = 1;
            }
        );
        $this->request('GET', 'foo/index');
        $this->assertResponseCode(200);
    }
```
and the controller checks if member_id in the session exists to let it pass

**Comment by kenjis** [comment]
I can't reproduce it if I don't have the controller code.

> keeps redirecting me to the sign-in page

Do you mean phpunit goes infinite loop?

Anyway, it seems it is because your controller code. Not because of ci-phpunit-test.

**Comment by ayokay123** [comment]
yeah i think it's from the controller.

**Comment by ayokay123** [comment]
well still didn't find a solution. the controller contains in the __construct this 
```
if (!$this->Members_model->member_id()) {
    redirect('signin');
}
```

and this is the member_id function 
```
function member_id()
    {
        return $this->session->member_id ? $this->session->member_id : false;
    }
```

**Comment by kenjis** [comment]
See <https://github.com/kenjis/ci-phpunit-test/blob/master/docs/FunctionAndClassReference.md#request-setcallable>.
You can't use `request->setCallable()`, because you check login in controller constructor.

**Comment by kenjis** [comment]
Try <https://github.com/kenjis/ci-phpunit-test/blob/master/docs/FunctionAndClassReference.md#request-setcallablepreconstructor>.

**Comment by ayokay123** [comment]
ArgumentCountError: Too few arguments to function Taxes_test::{closure}(), 0 passed in /var/www/html/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php on line 334 and exactly 1 expected

```
$this->request->setCallablePreConstructor(
            function ($CI) {
                $CI->session->member_id = 1;
            }
        );
```

**Comment by kenjis** [comment]
You can't $CI or CodeIgniter object, because there is no CodeIgniter object yet.
CodeIgniter object is a controller object.

**Comment by ayokay123** [comment]
how can i set the session then?

**Comment by kenjis** [comment]
There is no `$CI->session` yet. 

Create session object (or mock), and use `load_class_instance()`.

**Comment by kenjis** [comment]
If you can move `redirect()` logic out of the constructor, you can use `$this->request->setCallable()`

**Comment by ayokay123** [comment]
but that would break some functionality in the controller

**Comment by ayokay123** [comment]
can i create session by using just $_SESSION ? would that work with load_class_instance() ?

**Comment by kenjis** [comment]
Does this work?

```php
$this->request->setCallablePreConstructor(
	function () {
		// Get mock object
		$session = $this->getDouble(
			'CI_Session', []
		);
		$session->member_id = 1;
		// Inject mock object
		load_class_instance('session', $session);
	}
);
```

**Comment by kenjis** [comment]
> can i create session by using just $_SESSION ? 

No. You have to create CI_Session object.
$_SESSION is a global variable.

**Comment by ayokay123** [comment]
> ```
> $this->request->setCallablePreConstructor(
> 	function () {
> 		// Get mock object
> 		$session = $this->getDouble(
> 			'CI_Session', []
> 		);
> 		$session->member_id = 1;
> 		// Inject mock object
> 		load_class_instance('session', $session);
> 	}
> );
> ```

no didn't work

**Comment by kenjis** [comment]
Try <https://github.com/kenjis/ci-phpunit-test/issues/183#issuecomment-297724884>.

**Comment by ayokay123** [comment]
i think it did work because it's printing other error than 302

**Comment by ayokay123** [comment]
it might be related to using hmvc I'm not sure

**Comment by kenjis** [comment]
The error message must come from HMVC.

**Comment by ayokay123** [comment]
do you have any idea how to fix that?

**Comment by kenjis** [comment]
Can you show exact steps to reproduce your error?
I don't know what's the problem.

**Comment by ayokay123** [comment]
I found a solution 
https://github.com/diegosolo/ci-phpunit-test/commit/ed92001dbd0669cd6b827c012c7668b4d4216a7a
I followed his steps and it finally worked
thanks for your quick responses
