### ISSUE TITLE
Error CI_DB class not found

### ISSUE THREAD

**Issue by jagandecapri** [kenjis/ci-phpunit-test#36]
Hi when I try these codes for testing my model.

```php
        $db = $this->getMockBuilder('CI_DB_pdo_sqlite_driver')
            ->disableOriginalConstructor()
            ->getMock();
```

There is an error saying `PHP Fatal error:  Class 'CI_DB' not found`. Any idea why is this happening?

**Comment by kenjis** [comment]
Have you loaded `CI_DB` (`load->database()`)?

**Comment by jagandecapri** [comment]
Hi @kenjis ,

Just realized my mistake. I did not load database. Anyway thanks for helping out. ;)

**Comment by kenjis** [comment]
No problem.
