### ISSUE TITLE
PHP Warning:  Cannot modify header information - headers already sent by (output started at ...)

### ISSUE THREAD

**Issue by kenjis** [kenjis/ci-phpunit-test#37]
| Q | A |
| --- | --- |
| version | 1.0.x@dev (dev-master; after v0.5.0) |
| PHP | PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:17:32) |
| OS | Ubuntu 14.04 |

The warnings like below appear.

> PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/kenji/tmp/ci-app-for-ci-phpunit-test/vendor/phpunit/phpunit/src/Util/Printer.php:133) in /home/kenji/tmp/ci-app-for-ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/helpers/url_helper.php on line 84

This error is related to monkey patching. If I turn it off, the errors will be gone. 

And if I run tests again, the errors also will be gone. That is, if once patched source files are cached, the errors will be gone.

How to reproduce:

```
$ git clone https://github.com/kenjis/ci-app-for-ci-phpunit-test.git
$ cd ci-app-for-ci-phpunit-test
$ composer update
$ ./install.php
$ cd application/tests/
$ ../../vendor/bin/phpunit
```

Output:

```
PHPUnit 4.7.7 by Sebastian Bergmann and contributors.
Warning:    The Xdebug extension is not loaded
        No code coverage will be generated.

..........................PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/kenji/tmp/ci-app-for-ci-phpunit-test/vendor/phpunit/phpunit/src/Util/Printer.php:133) in /home/kenji/tmp/ci-app-for-ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/helpers/url_helper.php on line 84
...PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/kenji/tmp/ci-app-for-ci-phpunit-test/vendor/phpunit/phpunit/src/Util/Printer.php:133) in /home/kenji/tmp/ci-app-for-ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/helpers/url_helper.php on line 84
....PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/kenji/tmp/ci-app-for-ci-phpunit-test/vendor/phpunit/phpunit/src/Util/Printer.php:133) in /home/kenji/tmp/ci-app-for-ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/helpers/url_helper.php on line 87
................PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/kenji/tmp/ci-app-for-ci-phpunit-test/vendor/phpunit/phpunit/src/Util/Printer.php:133) in /home/kenji/tmp/ci-app-for-ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/helpers/url_helper.php on line 87
.PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/kenji/tmp/ci-app-for-ci-phpunit-test/vendor/phpunit/phpunit/src/Util/Printer.php:133) in /home/kenji/tmp/ci-app-for-ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/helpers/url_helper.php on line 87
.PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/kenji/tmp/ci-app-for-ci-phpunit-test/vendor/phpunit/phpunit/src/Util/Printer.php:133) in /home/kenji/tmp/ci-app-for-ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/helpers/url_helper.php on line 84
.PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/kenji/tmp/ci-app-for-ci-phpunit-test/vendor/phpunit/phpunit/src/Util/Printer.php:133) in /home/kenji/tmp/ci-app-for-ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/helpers/url_helper.php on line 84
............. 65 / 70 ( 92%)
.....

Time: 7.15 seconds, Memory: 19.25Mb

OK (70 tests, 101 assertions)
```

**Comment by kenjis** [comment]
If I turn on `ExitPatcher` only, no error occurs.

3 patchers:
~~~
$ ../../vendor/bin/phpunit controllers/Redirect_test.php
PHPUnit 4.7.7 by Sebastian Bergmann and contributors.
Warning:	The Xdebug extension is not loaded
		No code coverage will be generated.

.PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/kenji/tmp/ci-app-for-ci-phpunit-test/vendor/phpunit/phpunit/src/Util/Printer.php:133) in /home/kenji/tmp/ci-app-for-ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/helpers/url_helper.php on line 87
.PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/kenji/tmp/ci-app-for-ci-phpunit-test/vendor/phpunit/phpunit/src/Util/Printer.php:133) in /home/kenji/tmp/ci-app-for-ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/helpers/url_helper.php on line 84
.PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/kenji/tmp/ci-app-for-ci-phpunit-test/vendor/phpunit/phpunit/src/Util/Printer.php:133) in /home/kenji/tmp/ci-app-for-ci-phpunit-test/application/tests/_ci_phpunit_test/replacing/helpers/url_helper.php on line 84
.

Time: 4.27 seconds, Memory: 15.75Mb

OK (4 tests, 8 assertions)
~~~

`ExitPatcher` only:
~~~
$ ../../vendor/bin/phpunit controllers/Redirect_test.php 
PHPUnit 4.7.7 by Sebastian Bergmann and contributors.
Warning:	The Xdebug extension is not loaded
		No code coverage will be generated.

....

Time: 288 ms, Memory: 7.25Mb

OK (4 tests, 8 assertions)
~~~

And I found that when I turn on `FunctionPatcher` or `MethodPatcher`, the error occurs.

**Comment by RodolfoSilva** [comment]
The Output library not resolve that?

**Comment by kenjis** [comment]
I found the cause, but I don't know why it happens.

From the beginning, when `header()` was called in `redirect()`, CI's error handler catched it and discarded. Therefore the error (warning) was not outputted.

But when the error is outputted, CI's error handler does not catch it.

At least, I found workaround. So I'm going to commit it tomorrow.

**Comment by RodolfoSilva** [comment]
All right.

**Comment by kenjis** [comment]
I added workaround: https://github.com/kenjis/ci-phpunit-test/commit/b2ec257029311f644d970314b9d648cfc2262f87

And added fix to `redirect()`: https://github.com/kenjis/ci-phpunit-test/commit/d3945404193a5031690e42e4b6f51df4889693df
Because caling `header()` in `redirect()` is meaningless for testing.
* in php-cli, `header()` does nothing, but it causes "Cannot modify header information", because PHPUnit outputs progress info on testing already.
* *ci-phpunit-test* has special logic for testing redirect headers.

**Comment by kenjis** [comment]
> The Output library not resolve that?

Unfortunately no. Because Output library does not manage all response headers.
In this case, `redirect()` helper directly calls `header()` and `exit()`.

**Comment by RodolfoSilva** [comment]
All right.

**Comment by lingfengchencn** [comment]
once we run PHPUnit test, PHPUnit..phar will output :
   
    PHPUnit 4.8.9 by Sebastian Bergmann and contributors.

So ,we can't change header();
 
I adds "ob_start();"  at "CIPHPUnitTet.php" line 2; and it works. 

    <?php
       ob_start();
       /**
         * Part of CI PHPUnit Test
         *
         * @author     Kenji Suzuki <https://github.com/kenjis>
         * @license    MIT License
        * @copyright  2015 Kenji Suzuki
        * @link       https://github.com/kenjis/ci-phpunit-test
        */
        class CIPHPUnitTest

**Comment by kenjis** [comment]
@lingfengchencn The error happened in your app?

In my understanding I added workround for the error, so we never see the error.

**Comment by lingfengchencn** [comment]
Yes,  en....
wait a monent  to build a demo, We need them maybe:

    ob_start();

    ob_end_flush();

**Comment by lingfengchencn** [comment]
application\controllers\Welcome.php  codes:

    public function index()
	{

		$encoding = strtolower($this->config->item('charset'));
		header("Content-type: application/json; charset=$encoding", true, 200 );
		header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");                       // Date in the past
		header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");          // always modified
		header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");// HTTP/1.1
		header("Cache-Control: post-check=0, pre-check=0", false);
		header("Pragma: no-cache");
		echo '';
     }


Run test\controllers\Welcome_test.php :


$output


    
    A PHP Error was encountered

    Severity: WarningMessage:  Cannot modify header information - headers already sent by (output started at D:\Codes\test\system\core\Exceptions.php:272)Filename: D:\Codes\test\application\controllers\Welcome.phpLine Number: 35

    Backtrace:
			
			
			
			
	File: D:\Codes\test\application\controllers\Welcome.php	Line: 35	Function: header
		
			
			
	File: D:\Codes\test\application\tests\_ci_phpunit_test\CIPHPUnitTestRequest.php	Line: 312	Function: call_user_func_array
		
			
	File: D:\Codes\test\application\tests\_ci_phpunit_test\CIPHPUnitTestRequest.php	Line: 215	Function: createAndCallController
		
			
	File: D:\Codes\test\application\tests\_ci_phpunit_test\CIPHPUnitTestRequest.php	Line: 126	Function: callControllerMethod
		
			
	File: D:\Codes\test\application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php	Line: 106	Function: request
		
			
	File: D:\Codes\test\application\tests\controllers\Welcome_test.php	Line: 16	Function: request

**Comment by kenjis** [comment]
Thanks. I reproduced the error.

**Comment by kenjis** [comment]
Is there any good way to test `header()` in PHPUnit?
I don't know except for `@runInSeparateProcess`.
See https://github.com/sebastianbergmann/phpunit/issues/720

@lingfengchencn I added test case for `header()`: https://github.com/kenjis/ci-app-for-ci-phpunit-test/commit/e5609c358cbf60d3fbc16efd21d6ab65f249c6e6

In your case, it is not a bug of ci-phpunit-test, but the specification of PHPUnit.

I think your code is bad coding in CodeIgniter. I recomennd you use `$this->output`.
Because if you use it, you don't have to use `@runInSeparateProcess` and you can test headers using `$this->assertResponseHeader()`: https://github.com/kenjis/ci-phpunit-test/blob/master/docs/FunctionAndClassReference.md#testcaseassertresponseheadername-value

**Comment by lingfengchencn** [comment]
aha....
thinks,

**Comment by esetnik** [comment]
I have the same error output during each test and I am not using monkey patching. Is there anything I should check?

```
A PHP Error was encountered

Severity:    Warning
Message:     Cannot modify header information - headers already sent by (output started at phar:///usr/local/Cellar/phpunit/5.1.0/libexec/phpunit-5.1.0.phar/phpunit/Util/Printer.php:134)
Filename:    /system/core/Input.php
Line Number: 410
```

**Comment by esetnik** [comment]
To add a bit more context to my previous message. I have narrowed it down to usage of `$this->resetInstance()` in combination with a library that calls set_cookie in it's constructor. It looks like the `$this->resetInstance()` starts the output at which point no headers can be set by codeigniter in the test case. Anyone have any suggestions on how to work around this?

**Comment by kenjis** [comment]
> with a library that calls set_cookie in it's constructor

Basically, you can't call any functions which send headers during your test execution.

See https://github.com/sebastianbergmann/phpunit/issues/720#issuecomment-10399612
> PHPUnit assumes that neither the test code nor the tested code emit output or send headers.

So the solution is not to call the `setcookie()` during the test execution.

1. replace the Input object with a mock
2. patch `Input::set_cookie()` using monkey patching

But most easy workround is to use `$this->warningOff()`: https://github.com/kenjis/ci-phpunit-test/blob/master/docs/FunctionAndClassReference.md#testcasewarningoff

**Comment by esetnik** [comment]
@kenjis thanks for the feedback. I was hoping your previous statement would make it possible to use set_cookie() during test execution:

> I think your code is bad coding in CodeIgniter. I recomennd you use $this->output.
Because if you use it, you don't have to use @runInSeparateProcess and you can test headers using $this->assertResponseHeader()

Note that I am using [CI set_cookie](http://www.codeigniter.com/user_guide/libraries/input.html?highlight=set_cookie#CI_Input::set_cookie) not [setcookie](http://php.net/manual/en/function.setcookie.php) and I am using it with `$this->load->view()` which I assume uses `$this->output`. With those in place I should be able to avoid @runInSeparateProcess right?

Can you clarify how I would `$this->assertResponseHeader()` for set_cookie per the example you provided above?

**Comment by kenjis** [comment]
Unfortunately, you can't write tests like in the `$this->output->set_header()` case, because `CI_Input::set_cookie()` calls `setcookie()`. That is, whichever you use `CI_Input::set_cookie()` or `setcookie()`, there is no difference. So the answer to your question is no.

To do what you want, we have to provide a special CI_Input class for testing.

**Comment by esetnik** [comment]
Maybe this is something we should investigate. I think it would be a pretty common use case to want to test whether cookies were set by the controller under test. I'm happy to take a stab at implementing it if you can give me some direction as to what should be tweaked. It would be also nice to implement `$this->assertResponseSetCookie()` or something similar.

**Comment by kenjis** [comment]
@esetnik Yes, I opened https://github.com/kenjis/ci-phpunit-test/issues/86

**Comment by esetnik** [comment]
Thanks!

**Comment by lf-uraku-yuki** [comment]
I confirmed the same message without using monkey-patch.
Changed ENVIRONMENT definition from 'original-string' to 'testing' and solved it (Bootstrap.php).

**Comment by MarcioQuimbundo** [comment]
error_reporting(0) will not solve the problem, but it will clean the output error

**Comment by kenjis** [comment]
This is an old issue. If you have the same error `PHP Warning: Cannot modify header information - headers already sent by (output started at ...)`, open an new issue.
