### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'PHPUnit\Framework\TestCase' not found 

### ISSUE THREAD

**Issue by PooranSinghTricon** [kenjis/ci-phpunit-test#370]
I have  CodeIgniter 2.x with PHP 7.4. I followed all your given instructions   
1. composer.json 
	require => 
			"kenjis/ci-phpunit-test":"^3.0" 
  2. composer update 
  
  3. within root dir : php vendor/kenjis/ci-phpunit-test/install.php --from-composer 
  it does not install completely.  if I execute my step 3 as ->  within root dir : php vendor/kenjis/ci-phpunit-test/install.php
it install complete. 

Now  how to run  ?    1. cd application/tests/  2. PHPUnit 

it gives "PHP Fatal error:  Uncaught Error: Class 'PHPUnit\Framework\TestCase' not found in D:\xampp\htdocs\ubw-testing\application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php:24" 

![image](https://user-images.githubusercontent.com/81763146/114022577-8a1f8980-988f-11eb-8d9a-814f6200bbf1.png)

I did too much R&D on google. Nothing work.  Can you please help to find the solution ? if I need to change any file or code , Please let me know.

**Comment by kenjis** [comment]
I'm sorry, ci-phpunit-test supports CI 3.x only.

**Comment by kenjis** [comment]
See <https://github.com/kenjis/my-ciunit> for CI 2.x.
