### ISSUE TITLE
Configure vendor directory location

### ISSUE THREAD

**Issue by ndharithreesan** [kenjis/ci-phpunit-test#375]
We use `ci-phpunit-test` with `Composer` and it seems to only work when the application and vendor directories are parallel (looking at the `Bootstrap.php` file, this is by design). Is it possible to have the vendor dir a configurable setting, like how we set the application/test/public dirs? Our current Docker design has our vendor directory at the top level, so it breaks `ci-phpunit-test` unless we install it into our tests dir, and we would like to take advantage of the package manager instead of committing third party packages into our repos.

**Comment by kenjis** [comment]
@ndharithreesan 
How about changing the value of `CI_PHPUNIT_TESTPATH` in your `Bootstrap.php`?

https://github.com/kenjis/ci-phpunit-test/blob/202441b1d2143eb602a3804854297da1d23dc4d5/application/tests/Bootstrap.php#L319-L330
