### ISSUE TITLE
Coverage report is acting weird

### ISSUE THREAD

**Issue by purdy** [kenjis/ci-phpunit-test#388]
I'm trying to get this up & running in a new CodeIgniter 3 project, using php 7.3 and phpunit 9.5.13. I'm using a Lando container with a lamp recipe. When I ssh into the container and run phpunit w/ the `XDEBUG_MODE=coverage` turned on, it goes thru the tests, but then it seems to run all of my application views (generating lots of HTML output and errors from missing variables) and then hangs.

What can I do to generate the coverage reports?

Thanks!

**Comment by kenjis** [comment]
I'm not sure.
Exclude views.
Use Twig or something.

**Comment by purdy** [comment]
Ah, that was it ... plus I had a vendor subdir in my libraries that it was including and that was eating up a lotta time. I actually left it running overnight and it still wasn't done.

Thanks for the help!
