### ISSUE TITLE
Class 'TestCase' not found.

### ISSUE THREAD

**Issue by AhabTheCaptain** [kenjis/ci-phpunit-test#39]
Hello,
I am having problems setting up ci-phpunit-test with PHPUnit 4.7 and CodeIgniter 3. I have gone through the documentation here and on the PHPUnit site to ensure I haven't missed any setup steps, but maybe that is all that is happening here. When I run a specific test case file with phpunit, I receive the following error message:

~~~
vagrant@vagrant-ubuntu-trusty-64:/var/www/html/application/tests/models/User$ phpunit User_model_test.php
/*
** Unit tests for the User Model.
**
**
*/

PHP Fatal error:  Class 'TestCase' not found in /var/www/html/application/tests/models/User/User_model_test.php on line 11
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:537
PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:99
PHP   4. PHPUnit_Runner_BaseTestRunner->getTest() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:121
PHP   5. PHPUnit_Runner_BaseTestRunner->loadSuiteClass() phar:///usr/local/bin/phpunit/phpunit/Runner/BaseTestRunner.php:66
PHP   6. PHPUnit_Runner_StandardTestSuiteLoader->load() phar:///usr/local/bin/phpunit/phpunit/Runner/BaseTestRunner.php:121
PHP   7. PHPUnit_Util_Fileloader::checkAndLoad() phar:///usr/local/bin/phpunit/phpunit/Runner/StandardTestSuiteLoader.php:37
PHP   8. PHPUnit_Util_Fileloader::load() phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php:36
PHP   9. include_once() phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php:52
~~~

This clears up if I add "include '../TestCase.php';" but then it can't find another class, and so on down the rabbit hole.

The code below is a meaningless test as I am trying to get phpunit to run and be able to find the necessary classes for core functionality.

~~~
<?php
// include '../TestCase.php';

class User_model_test extends TestCase 
{
    public function setUp()
    {
        $this->CI =& get_instance();
        $this->load->model('User_model');
        $this->obj = $this->CI->User_model;
    }
    
    public function testSignUp()
    {
        $actual = $this->obj->signUp();
        $this->assertTrue($actual);
    }
}
?>
~~~

Please let me know if I can provide additional relevant details. My PHP knowledge is weak, but I am experienced with JUnit. 

Thank You!

**Comment by RodolfoSilva** [comment]
See this: https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md

**Comment by kenjis** [comment]
It seems you don't load `tests/Bootrap.php`.

I've got your problem.

> vagrant@vagrant-ubuntu-trusty-64:/var/www/html/application/tests/models/User$ phpunit User_model_test.php

You are in `application/tests/models/User`. But you should have been in `application/tests`.

`phpunit` reads `phpunit.xml` in the current folder.

**Comment by RodolfoSilva** [comment]
Do you have in your folder test the file TestCase.php

**Comment by AhabTheCaptain** [comment]
Thank you for the help. Running phpunit from the tests directory cleared this up. I am getting different errors now, but I will bang on them myself for awhile so I can learn the system. Thanks again for your quick responses to my fairly derpy issue. =)

**Comment by kenjis** [comment]
No problem.

I added note: https://github.com/kenjis/ci-phpunit-test/commit/ccc0489c0fbd44f2b311bb0db70cd94f235b6bfb
