### ISSUE TITLE
How to extend the test runner for post operations?

### ISSUE THREAD

**Issue by vivek-23** [kenjis/ci-phpunit-test#395]
Hello Kenjis. Hope you are doing well. 

I wish to perform an operation post to execution of all tests and coverage report in clover.xml etc. 
How could I do that with your repo?

As per the official docs, there does seem to be a way to do this(as shown in the below link):
https://phpunit-document-english.readthedocs.io/en/8.4/extending-phpunit.html#extending-the-testrunner

I tried but the `Runner` classes or interfaces are missing in your `_ci_phpunit_test` folder.

**Comment by kenjis** [comment]
See `vendor/phpunit/phpunit/src/`. 

ci-phpunit-test just uses PHPUnit. If you want to extend PHPUnit, ci-phpunit-test does not matter.

**Comment by vivek-23** [comment]
Thanks for your quick response. I could replace this with the actual PHPUnit using composer, but my seniors would deny such huge changes as of now w.r.t. testing environment. 

Apparently, the below code seems to be syntactically valid when I run it with `phpunit8.phar` but I wish to read `clover.xml` log file after it's report has been generated. 

**phpunit.xml**

```
<phpunit
	bootstrap="./Bootstrap.php"
	backupGlobals="true"
	colors="true">
	<extensions>
    	     <extension class="MyExtension"/>
	</extensions>
</phpunit>

```

**MyExtension.php**

```
<?php

use \PHPUnit\Runner\AfterLastTestHook;

class MyExtension implements AfterLastTestHook{
    public function executeAfterLastTest(): void {
        echo "Hello from Runner";
    }
}
```

As a workaround, maybe I can run any CLI command in the Codeigniter project that does the job? Only overhead would be running 2 different commands which I can probably encapsulate in a batch file.

**Comment by kenjis** [comment]
> As a workaround, maybe I can run any CLI command in the Codeigniter project that does the job?

Yes, you can write shell script or batch file to run phpunit and your script.

**Comment by vivek-23** [comment]
Thanks a lot. Yes, I have created a `test.bat` file with the following commands as a workaround solution:

```
phpunit8.phar
php ../../index.php CloverXMLReportModifier modifyCloverReport
```

[`CI docs`](https://devdocs.io/codeigniter~3/general/cli)
