### ISSUE TITLE
3.x new version with Updates for PHP 8.1

### ISSUE THREAD

**Issue by pabloolvcastro** [kenjis/ci-phpunit-test#396]
Dear Maintainers,

I'm curious when would you generate a new version with the updates to cover PHP 8.1 required changes? I checked the Repository and this PR https://github.com/kenjis/ci-phpunit-test/pull/392 covers everything I found as problems. And it is merged into the branch [3.x](https://github.com/kenjis/ci-phpunit-test).
I see also that the code coverage is failing. If I help with the coverage, would it be possible to get a new version up?

I appreciate all the hard work done here and want to collaborate in any way possible. ❤️

**Comment by kenjis** [comment]
You are the first person who requested updates for PHP 8.1.
Yes, `3.x` branch supports PHP 8.1. Do you have no problem at all?

**Comment by pabloolvcastro** [comment]
Yeah, no problems at all. Our only blocking issue was related to those properties in the class ExitException. I patched the files using the code in the `3.x` and had no problems. I could run our tests normally. All the other warnings vanished also. I was left with only the ones that were related to our code.

 ```PHP
Fatal error: Type of Kenjis\MonkeyPatch\Exception\ExitException::$file must be string (as in class Exception) in /var/www/html/private/vendor/kenjis/ci-phpunit-test/application/tests/_ci_phpunit_test/patcher/4.x/Exception/ExitException.php on line 15

Fatal error: Type of Kenjis\MonkeyPatch\Exception\ExitException::$line must be int (as in class Exception) in /var/www/html/private/vendor/kenjis/ci-phpunit-test/application/tests/_ci_phpunit_test/patcher/4.x/Exception/ExitException.php on line 15
 ```

**Comment by kenjis** [comment]
v3.0.4 was released!
https://github.com/kenjis/ci-phpunit-test/releases/tag/v3.0.4
