### ISSUE TITLE
How to clear RAM memory after run testcase in testsuite?

### ISSUE THREAD

**Issue by hongdung92** [kenjis/ci-phpunit-test#404]
Every time I run a test suite, the data from the previous test cases are not cleared, causing memory usage, Thank you!

**Comment by kenjis** [comment]
I don't understand your situation.
What is the exact error message?
What is the data?

**Comment by hongdung92** [comment]
I have a test suite with 100 test cases, and after running that test suite, my RAM lost 5GB, which means on average each test case takes 50MB. I want to release the memory after finishing each test case. Specifically, I want to ensure that running all 100 test cases will only consume 50MB instead of 5GB.

**Comment by kenjis** [comment]
5GB seems to be too big.
But it is not a issue in ci-phpunit-test, but in your test code.

> I want to release the memory after finishing each test case.

Release the memory with the normal ways in PHP programming.

Run tests by a directory or by a test file, identify tests that consume a lot of memory and have not been freed, and add code to free memory when the test is finished.
