### ISSUE TITLE
Controller in folder

### ISSUE THREAD

**Issue by serazoli** [kenjis/ci-phpunit-test#48]
Hi.
I have controller in 2 folder depth  from controllers folder (ex. controllers/api/aa/Example.php).  I make a request the following form 
```php
$this->request('GET', ['Example', 'users_get']);
```
i will get
```
 Example_test::test_users_get
Status code is not 200 but 404.
Failed asserting that 404 is identical to 200.
```
If i move the controller one folder up (ex. controller/api/Example.php) the above form work ok.
OR i make the request in the following form
```php
$this->request('GET', '/api/bb/example/users_get');
```
work ok.
Sorry my bad English.

**Comment by kenjis** [comment]
Please use `$this->request('GET', '/api/bb/example/users');` at the moment.

This is because controller autoload of ci-phpunit-test only seeks in sub folder.

**Comment by serazoli** [comment]
Ok. 
Thanks.

**Comment by kenjis** [comment]
I've fixed autoloader: https://github.com/kenjis/ci-phpunit-test/commit/2ebac535602df259e8b69c6a926957403f775e37

**Comment by serazoli** [comment]
Thanks. I made a quick test and is look like OK
