### ISSUE TITLE
Codeigniter-restserver and GET parameters

### ISSUE THREAD

**Issue by serazoli** [kenjis/ci-phpunit-test#49]
Hi.
The codeigniter-rest-server not accept the GET parameter from array (['name' => 'Mike'])
```php
$output = $this->request('GET', 'query_string/index', ['name' => 'Mike']);
```
because rest-server don't use $_GET variable - if i saw good.
and
```php
$output = $this->request('GET', 'query_string/index?name=Mike');
```
not work.
$output will be NULL
Sorry my bad English
Thanks.

**Comment by kenjis** [comment]
It seems you are right. But I don't know why codeigniter-restserver does not use `CI_Input::get()`.

**Comment by kenjis** [comment]
How about this?

~~~php
$output = $this->request('GET', 'query_string/index/name/Mike');
~~~

**Comment by serazoli** [comment]
I have a little bit complicated parameters. 
From client side I will get similar GET parameters
```
"page":"1","rows":"10",'filterRules':[{"field":"time","op":"between","value":["2015-08-01","2015-08-31"]}]
```
What will be from this parameter in the form proposed by you? 
If I use "?" and "&" sign will be this
```
log?page=1&rows=10&filterRules=%5B%7B%22field%22%3A%22time%22%2C%22op%22%3A%22between%22%2C%22value%22%3A%5B%222015-08-01%22%2C%222015-08-31%22%5D%7D%5D
```
Thanks

**Comment by serazoli** [comment]
have you any suggestion how I inject the above url to the codigniter?

**Comment by kenjis** [comment]
Do you mean like this?

~~~php
$output = $this->request('GET', 'foo/bar/log?page=1&rows=10&filterRules=[{"field":"time","op":"between","value":["2015-08-01","2015-08-31"]}]');
~~~

**Comment by kenjis** [comment]
This is workaround for example 7 (`User #1 - get it in XML (users/id/1?format=xml)`):

~~~php
		set_is_cli(FALSE);
		$this->warningOff();
		$_SERVER['REQUEST_URI'] = 'api/example/users/id/1?format=xml';
		$output = $this->request('GET', 'api/example/users/id/1');
		set_is_cli(TRUE);
		$this->warningOn();

		$this->assertEquals(
			'<?xml version="1.0" encoding="utf-8"?>
<xml><id>1</id><name>John</name><email>john@example.com</email><fact>Loves coding</fact></xml>
',
			$output
		);
		$this->assertResponseCode(200);
~~~

In your case, you set `$_SERVER['REQUEST_URI']` like this:

~~~php
$_SERVER['REQUEST_URI'] = 'log?page=1&rows=10&filterRules=%5B%7B%22field%22%3A%22time%22%2C%22op%22%3A%22between%22%2C%22value%22%3A%5B%222015-08-01%22%2C%222015-08-31%22%5D%7D%5D';
~~~

**Comment by kenjis** [comment]
I posted issue to ask why.
https://github.com/chriskacerguis/codeigniter-restserver/issues/544

**Comment by serazoli** [comment]
Thanks.
I made a quick test  for workaround you wrote above and is look like ok.

**Comment by kenjis** [comment]
I sent PR: https://github.com/kenjis/ci-phpunit-test/pull/51

With this PR, we can write test like this:

~~~php
		set_is_cli(FALSE);
		$this->warningOff();
		$output = $this->request(
			'GET',
			'api/example/users/id/1?format=xml'
		);
		set_is_cli(TRUE);
		$this->warningOn();

		$this->assertEquals(
			'<?xml version="1.0" encoding="utf-8"?>
<xml><id>1</id><name>John</name><email>john@example.com</email><fact>Loves coding</fact></xml>
',
			$output
		);
		$this->assertResponseCode(200);
~~~

But we can't remove below, because of implementation of codeigniter-restserver.

~~~php
        set_is_cli(FALSE);
        $this->warningOff();
~~~

**Comment by serazoli** [comment]
Thanks, I will try ASAP

**Comment by kenjis** [comment]
If you use latest `master` of ci-phpunit-test, and this `MY_Session` class https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/master/application/libraries/Session/MY_Session.php ,

You can write tests without `$this->warningOff()`:
https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/master/application/tests/controllers/api/Example_test.php#L49

**Comment by kenjis** [comment]
@serazoli 
The latest reset server (see `master` brach) is fixed. And I added a test you want:
https://github.com/kenjis/ci-app-for-ci-phpunit-test/commit/308a47b123cc571d04a31fb250d064d5ad2c5756

**Comment by serazoli** [comment]
Thanks
