### ISSUE TITLE
 Problem with autoload

### ISSUE THREAD

**Issue by RodolfoSilva** [kenjis/ci-phpunit-test#5]
I have problem with auto load **form_validation**.

```
Severity: ErrorMessage:  Call to a member function helper() on a non-object
Filename: /var/www/ci-phpunit-test/system/libraries/Form_validation.php
Line Number: 147
```

**Comment by kenjis** [comment]
Thanks for your reporting.

I will remove `get_new_instance()` and added `reset_instance()`.
See https://github.com/kenjis/ci-phpunit-test#deprecated-get_new_instance

I think it solves all autoloader problems.

**Comment by RodolfoSilva** [comment]
Thanks, now is working.
