### ISSUE TITLE
Integrate unit-test on netbeans 8.0.2

### ISSUE THREAD

**Issue by Explox** [kenjis/ci-phpunit-test#56]
Hi,

I'm currently searching for a way to develop using CodeIgniter >= 3.0 with Netbeans and Unit Test.

So far, i didn't found any good tutorial which worked. All your tests are working in CLI in my application/tests folder. I've the same result, but it seems I can't run them on Netbeans. 
I've always the same result when i'm trying to execute tests :
     unrecognized option --run

In Testing properties, I have enabled PHPUnit and added the application/tests folder as test directory

In Netbeans's Options : PHP > Frameworks & Tools :
        - I added the path of the phpunit.phar (4.7 if no mistake)

If you have any idea, I'd be very happy :D 

Thanks.

**Comment by kenjis** [comment]
Are you sure you are using PHPUnit 4.7? 

~~~
$ phpunit --version
~~~

NetBeans 8.0.2 does not support PHPUnit 4.8.
See https://netbeans.org/bugzilla/show_bug.cgi?id=254276

**Comment by Explox** [comment]
You're right. I was probably using 4.8.X version. I tried at work and it's working. But i search to retrieve the 4.7 version which I thought I did because I read your note about Netbeans not being compatible with 4.8.X phpunit. But OK, my bad, thanks.
