### ISSUE TITLE
Can't get the testsuite to run IN PHPSTORM

### ISSUE THREAD

**Issue by PhoenixFnX** [kenjis/ci-phpunit-test#59]
Following the main tutoriel, I can't get the testsuite to be ran.

It searches for test files with the default suffixes .phpt ans Test.php, therefore it tries to use CIPHPUnitTest.php as a testCase...

How do you specify the default test suite to run ?

**Comment by PhoenixFnX** [comment]
Ok I just found the reason why it was failing. On JetBrains PHPStorm, in the run configurations, you must NOT select directory in the Test scope. Better choose the defined in the configuration file.

![image](https://cloud.githubusercontent.com/assets/993122/10138752/3f4c6710-6600-11e5-917f-a491bb7681d4.png)

**Comment by kenjis** [comment]
Yes, you need to specify `application/tests/phpunit.xml`.
