### ISSUE TITLE
Suggestion for move the files

### ISSUE THREAD

**Issue by RodolfoSilva** [kenjis/ci-phpunit-test#6]
Move the ci-phpunit-test library files to directory **third_party** and rename for CIUnit.

## Actual

~~~
codeigniter/
├── application/
│   └── tests/
│        ├── _ci_phpunit_test/ ... don't touch! files CI PHPUnit Test uses
│        ├── Bootstrap.php     ... bootstrap file for PHPUnit
│        ├── TestCase.php      ... TestCase class
│        ├── controllers/      ... put your controller tests
│        ├── mocks/
│        │   └── libraries/    ... mock libraries
│        ├── models/           ... put your model tests
│        └── phpunit.xml       ... config file for PHPUnit
└── vendor/
~~~

## Suggestion

~~~
codeigniter/
├── application/
│   ├── tests/
│   │    ├── controllers/           ... put your controller tests
│   │    ├── mocks/
│   │    │   └── libraries/         ... mock libraries
│   │    ├── models/                ... put your model tests
│   │    ├── libraries/             ... put your library tests
│   │    └── phpunit.xml            ... config file for PHPUnit
│   └── third_party/
│        └── CIUnit
│             ├── _ci_phpunit_test/ ... don't touch! files CI PHPUnit Test uses
│             ├── Bootstrap.php     ... bootstrap file for PHPUnit
│             └── TestCase.php      ... TestCase class
└── vendor/
~~~

**Comment by kenjis** [comment]
First of all, this is not `CIUnit`. Probably you know original CIUnit is http://foostack.com/ .
And there are a lot of forks.

I wrote this ci-phpunit-test from scratch. It is confusing to use the name CIUnit.

Why do you suggest to move to `third_party`? What's the point?
I put all files in `test` folder to install this as easy as possible.

**Comment by RodolfoSilva** [comment]
Yes, I know what original CIUnit is http://foostack.com/.

`CIUnit` it's one example, maybe use this name: `CIPHPUnitTest`

I think it is easier to upgrade or define as subrepo.
Already unit test cases can stay in the `tests` directory.

**Comment by kenjis** [comment]
Okay, I'll move `Bootstrap.php` and `TestCase.php` into `_ci_phpunit_test/`.
Then when we update, all we have to do is replacing `_ci_phpunit_test/` folder.

**Comment by kenjis** [comment]
`Bootstrap.php` contains paths: https://github.com/kenjis/ci-phpunit-test#step-2

Users may change them. So it should not be changed when you update ci-phpunit-test.

**Comment by kenjis** [comment]
From now on, you can upgrade easier than before:
https://github.com/kenjis/ci-phpunit-test#upgrading

**Comment by RodolfoSilva** [comment]
All right. Now is better.
