### ISSUE TITLE
call to ini_set

### ISSUE THREAD

**Issue by PhoenixFnX** [kenjis/ci-phpunit-test#60]
I have the following error during controller test execution : 

    <p>Message:  ini_set(): A session is active. You cannot change the session module's ini settings at this time</p>
    <p>Filename: Session/Session.php:313</p>

**Comment by kenjis** [comment]
As the error message says, you cannot change the session module's ini settings after a session is active.
Normally session initialization is aborted under CLI. See `Session/Session.php` line 72.

Do you call `set_is_cli(FALSE)`? If you really need to call it, try [`MY_Session.php`](https://github.com/kenjis/ci-phpunit-test/blob/master/application/libraries/Session/MY_Session.php).

**Comment by PhoenixFnX** [comment]
Yes, I called is_cli(false); because I strongly rely on sessions using session_destroy(), session_write(), session_open() in order to release session locks to improve performances. 

Therefore I suppose I need your MY_Session.php hook, how to use ? do I copy it into my application folder ?

**Comment by kenjis** [comment]
Yes, to use `MY_Session.php`, you just put it in `application/libraries/Session` folder.
But I don't know it works for your apps. I think basically we can't use session functions during test execution.
