### ISSUE TITLE
exit; handling

### ISSUE THREAD

**Issue by PhoenixFnX** [kenjis/ci-phpunit-test#61]
Hello, 

Is it possible to handle the exit; function ?
I have to call it when the user is not loggedin to abort a controller execution. Here is my simplified code:
    
    class MY_Controller extends CI_Controller {
        function __construct() {
            parent::__construct();
            if (!$this->tank_auth->is_logged_in()) {
                $this->output->append_output($this->load->view('auth/timeOutV2', $this->timeOut(), true));
                echo $this->output->get_output();	
                exit;
            }
        }
    }

This Issue is only to know if its possible to handle the exit php instruction as it brutally stops the phpunit process.

I think it's not possible but I prefer to ask you first.

**Comment by kenjis** [comment]
See https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#exit
