### ISSUE TITLE
getDouble not used in controller constructor

### ISSUE THREAD

**Issue by PhoenixFnX** [kenjis/ci-phpunit-test#62]
If you read my issue about the exit function, you already know my context. I have a isLoggedIn method in the controller constructor. I want to mock it to make it return true to test the method underneath. 

THE problem is that the Mock functions are called AFTER this controller initialization.

Here is my test code:
<pre>
	public function test_index_logged_in()
	{
		$this->request->setCallable(
			function ($CI) {
				// Get mock object
				$auth = $this->getDouble(
					'Tank_auth', ['is_logged_in' => TRUE]
				);
				// Inject mock object
				$CI->tank_auth = $auth;
			}
		);
		$output = $this->request('GET', ['Main', 'index']);
		$this->assertContains('result OK', $output);
	}
</pre>

But the Main controller extends MY_Controller which contains a is_logged_in in its constructor. So when I call the $this->request method, here is the stack trace:

<pre>
$this->request('GET', ['Main', 'index']);
CIPHPUnitTestCase.php:106
CIPHPUnitTestRequest.php:120
CIPHPUnitTestRequest.php:200
CIPHPUnitTestRequest.php:277
Main.php // Here is my code, it extends M_Controller then calls its constructor
</pre>

And finally, here is the MY_Controller constructor:

    class MY_Controller extends CI_Controller {
        function __construct() {
            parent::__construct();
            if (!$this->tank_auth->is_logged_in()) {
                $this->output->append_output($this->load->view('auth/timeOutV2', $this->timeOut(), true));
                echo $this->output->get_output();	
                exit;
            }
        }
    }

**Comment by kenjis** [comment]
See https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#request-and-use-mocks
See the example of ion_auth and `setCallablePreConstructor()`.

**Comment by PhoenixFnX** [comment]
Oh lala I didn't see that PreConstructor method... The name is so OBVIOUS, thank you
