### ISSUE TITLE
Return in bootstrap aborts hooks loading (post-controller for instance)

### ISSUE THREAD

**Issue by PhoenixFnX** [kenjis/ci-phpunit-test#64]
I have a custom language loading using a post_controller_constructor hook : 
<pre>

	$hook['post_controller_constructor'] = array(
			'class' => 'LanguageLoader',
			'function' => 'initialize',
			'filename' => 'LanguageLoader.php',
			'filepath' => 'hooks'
	);
</pre>

I then decided to use the commit you did yesterday but you added a return before all the hook calls, you can't abort the bootstrap like this, all the hooks are bypassed !

therefore, all my lang() calls fails.

PS: Just before upgrading my code to your last commit, the `new CI_Controller()` function call was resetting the language arrays because it rebuilds the CI Single Instance. `self::$instance =& $this;`

My hack seems to work. Here is my CIPHPUnitTest file:
<pre>
		try {
			// Request to 404 route
			// This is needed for not to call Welcome::index()
			// If controller Welcome is called in bootstrap, we can't test
			// the same name sub controller Welcome even when we use
			// `@runInSeparateProcess` and `@preserveGlobalState disabled`
			require_once BASEPATH . 'core/CodeIgniter.php';
		} catch (CIPHPUnitTestShow404Exception $e) {
			// Catch 404 exception
			//new CI_Controller(); COMMENTED BY NTH Because it resets the post_controllers hooks
		}
</pre>

Sorry for writing this message while debugging your code. I just found that you rebootstrap Codeigniter when calling the the `$this->request(...)` method. My problem is that `$this->enableHooks`

**Comment by PhoenixFnX** [comment]
Wait a minute, I have a custom language loading, they are not in the autoload file.

**Comment by kenjis** [comment]
It is by design.
See https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#hooks

**Comment by kenjis** [comment]
If you have an opinion to the current design, let me know.
We're discussing about hooks on #20.

**Comment by PhoenixFnX** [comment]
Actually reading the documentation I just have to do `$this->request->enableHooks();` :+1:
