### ISSUE TITLE
[enhancement] Call setCallable many times

### ISSUE THREAD

**Issue by PhoenixFnX** [kenjis/ci-phpunit-test#66]
Hi Kenjis, 

I have a proposal : To be able to call many times the `$this->request->setCallable()` method.
My goal is to add many mocks, at differents moments during the testcase.

**Comment by kenjis** [comment]
Sorry, what do you mean? I don't get what you want to say.

**Comment by PhoenixFnX** [comment]
Ok. Sorry. 

when I call many times the $this->request->setCallable({Closure}) method, only the last {closure} is executed. Here is an example:

<pre>
class DataTableServer_test extends TestCase {
	public function setUp() {
		$this->resetInstance();
		$this->request->setCallable(
			function ( $CI ) use ($damaaasName) {
				$session = $this->getMockBuilder('MY_Session')->getMock();
				$session->method('userdata')->will($this->returnValueMap([
					['user_id',27],
					['language', 'french']
				]));
				$CI->session =  $session;
			}
		);
	}
	public function test_getTable() {
		$this->request->setCallable(
			function ( $CI ) use ($damaaasName) {
				$damaaasId = $this->CI->db->select("id")->like("name", $damaaasName)->get("damaaas")->result_array()[0]['id'];
				$CI->mockController($damaaasId, 27); //my hack to mock the Controller
			}
		);
	}
}
</pre>

The example does not work, I have to put all the mocks in the same {Closure} method.

**Comment by kenjis** [comment]
In my opinion, your code will be like this:

~~~php
class TestCase extends CIPHPUnitTestCase
{
	public function setSession($CI)
	{
		$session = $this->getMockBuilder('MY_Session')->getMock();
		$session->method('userdata')->will($this->returnValueMap([
			['user_id', 27],
			['language', 'french']
		]));
		$CI->session = $session;
	}

	public function setAppAndUser($CI, $appName, $userId)
	{
		$appId = $CI->db->select("id")->like("name", $appName)->get("app")->result_array()[0]['id'];
		$CI->mockController($appId, $userId); //my hack to mock the Contr
	}
}


class DataTableServer_test extends TestCase
{
	public function test_getTable()
	{
		$this->request->setCallable(
			function ($CI) {
				$this->setSession($CI);
				$this->setAppAndUser($CI, "testing userRights", 21);
			}
		);
		// HERE IS THE ACTUAL TEST, in a simple method
	}
}
~~~

**Comment by PhoenixFnX** [comment]
I find the setcallable call a bit heavy to write but OK, I accept the workaround ;-)
Thank you

**Comment by kenjis** [comment]
You can create a method to call `setCallable()`:

~~~php
class DataTableServer_test extends TestCase
{
    public function setMocks($appName, $userId)
    {
        $this->request->setCallable(
            function ($CI) use ($appName, $userId) {
                $this->setSession($CI);
                $this->setAppAndUser($CI, $appName, $userId);
            }
        );
    }

    public function test_getTable()
    {
        $this->setMocks("testing userRights", 21);
        // HERE IS THE ACTUAL TEST, in a simple method
    }
}
~~~

Do you really need to call `setCallable()` multiple times?

**Comment by PhoenixFnX** [comment]
This actually what I did (a method to call `setCallable()`)but yes I think some cases would like this feature.

I use a mock during the setup for example. Fortunately it is a preconstructor mock:

<pre>
public function setUp() {
		parent::setUp();
		$this->request->setCallablePreConstructor(
			function () {
				$this->setLogged();
			}
		);
	}
</pre>

But If I have had to use `setCallable` here, I couldn't...

**Comment by kenjis** [comment]
`setCallable()` and `setCallablePreConstructor()` are completely different.

> But If I have had to use setCallable here, I couldn't...

I don't get what you want to do. Please show me example code.

**Comment by PhoenixFnX** [comment]
Ok. 
What I wanted to do is to get a class level mock which will be used for all tests in the class.

```php
class DataTableServer_test extends TestCase {
	public function setUp() {
		parent::setUp();
		$this->request->setCallable(
			function () {
				$this->setLogged();
			}
		);
	}
```

Then, in a specific test, I want to get a test dependent mock, specifying a context for instance:

```php
	public function test_rights_WhereActorIsInField() {
		$this->setContext("Recette Droits d'accès", "damaaas.test5@gmail.com");
		// Rest of test code with asserts....
	}
```

**Comment by kenjis** [comment]
How about this? #68

**Comment by PhoenixFnX** [comment]
You're just amazing ! Thank you, this is exactly what I meant !

**Comment by kenjis** [comment]
I merged the PR.
