### ISSUE TITLE
Fatal error: Call to undefined function get_instance()

### ISSUE THREAD

**Issue by StefanSx** [kenjis/ci-phpunit-test#70]
I followed your instructions for version v0.8.2 and tried to run unit tests on a fresh codeigniter 3.0.1 installation with:

$ cd application/tests/
$ phpunit

I got this error:

**PHP Fatal error:  Call to undefined function get_instance() in /media/sf_deals/application/tests/_ci_phpunit_test/replacing/core/Common.php on line 259**

The function **get_instance()** is defined in **application\tests\_ci_phpunit_test\replacing\core\CodeIgniter.php**.

In **application\tests\_ci_phpunit_test\CIPHPUnitTest.php** the file **Common.php** (line 36) is loaded before the file **CodeIgniter.php** (line 59).

I'm wondering, why this works for you.

**Comment by kenjis** [comment]
Because `get_instance()` is not called at that time.

~~~
$ composer create-project kenjis/codeigniter-composer-installer codeigniter
  - Installing codeigniter/framework (3.0.2)
$ cd codeigniter
$ composer require kenjis/ci-phpunit-test --dev
  - Installing kenjis/ci-phpunit-test (v0.8.2)
$ php vendor/kenjis/ci-phpunit-test/install.php
~~~

~~~
$ cd application/tests/
$ phpunit
PHPUnit 4.7.7 by Sebastian Bergmann and contributors.

...

Time: 809 ms, Memory: 5.50Mb

OK (3 tests, 3 assertions)
~~~

**Comment by StefanSx** [comment]
Sorry, my fault.

I didn't create the config for the testing environment.
That's why it jumped into the set_status_header() function in  application/tests/_ci_phpunit_test/replacing/core/Common.php

**Comment by kenjis** [comment]
You didn't have `config/config.php` nor `config/testing/config.php`?

**Comment by StefanSx** [comment]
Yes, none of them was there.

**Comment by sofiangrh** [comment]
I also have same issue here, when I run test with PHPUnit in model file test I got this **error**:

```
1) Manageuser_model_test::test_get_all_user
Error: Call to undefined function get_instance()

C:\xampp\htdocs\simaungv4\application\tests\models\Manageuser_model_test.php:7
```

**and here's my model test file**:
```
<?php

use PHPUnit\Framework\TestCase;

class Manageuser_model_test extends TestCase {
    public function setup():void {
        $this->CI =& get_instance();
        $this->CI->load->model('manageuser_model');
        $this->obj = $this->CI->Manageuser_model;
    }

    public function test_get_all_user() {
  		$expected = [
  			1 => 'Fakultas',
  			2 => 'UPT',
  			3 => 'Prodi',
  		];
  		$user = $this->obj->get_all_user();
  		foreach ($user as $user_name) {
  			$this->assertEquals($expected[$user_name->user_id], $user_name->username);
  		}
	  }
}
```

I'm using PHPUnit version 8.5.0. I'm trying using the different version of PHPUnit, but still got the same error. could you help me the way hot to fix this?

Thanks in advance..
