### ISSUE TITLE
help wanted loading libraries in subdirectories for controller testing

### ISSUE THREAD

**Issue by jkudebeh** [kenjis/ci-phpunit-test#72]
HI,

I'm having trouble getting a controller test to run.

The message is : 
> Unable to locate the specified class: Session.php
 
The line from my autoload.php is : 
~~~php
 $autoload['libraries'] = array('database', 'session',  'PERM/Perm_hrpws');
 ~~~

The Session library is in `"system/libraries/Session/Session.php"`

I also had a use library at `"application/libraries/PERM/Perm_ws.php"`, If I comment out 'session' 
The message is : 
> Unable to locate the specified class: Perm_ws.php

 If I comment both out I don't get the message above, but get the error:
>   Fatal error: Call to a member function flashdata() on null
   
Any thoughts on what I'm doing wrong?

I tried both v0.8.2 and 1.0x-dev builds

thanks
Jim

**Comment by kenjis** [comment]
Can you load the libraries when you access via your web browser?

I added a test, but can't reproduce the error:
https://github.com/kenjis/ci-app-for-ci-phpunit-test/commit/7ca540ea3245a68c43401e4aaab0a391c85a8772

**Comment by jkudebeh** [comment]
Hi,

Yes, the libraries load fine when using the web site.

Any ideas as to what else I can look at?
Any debugging I can do on my side to help identify the problem?

Jim

**Comment by kenjis** [comment]
Install the repository: https://github.com/kenjis/ci-app-for-ci-phpunit-test/
and see my test case: https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/master/application/tests/controllers/Ci_autoload_library_test.php

Compare it with your code, you may find something different.

In my understanding, the autoload issue was solved in the past. So I don't know why you get the error again.

**Comment by PhoenixFnX** [comment]
Hi,

Make sure you don't have another class which has the same name. Autoload
seeks for the first class with a name you search using the scope order
discussed on another issue here.

**Comment by jkudebeh** [comment]
I've been temporarily pulled of the project to get unit tests working on our CI. I'll try the above when I can.  
Thanks for the responses
Jim

**Comment by DakuTree** [comment]
I've been having a similar issue like this after moving all the Ion_Auth files into subfolders (libraries/vendor, models/vendor etc.).
PHPUnit is returning ```"Unable to locate the specified class: Bcrypt.php"``` even though it seems load perfectly fine when viewing the website.

Doing something like:
```php
public function setUp() {
	$this->CI =& get_instance();
	$this->CI->load->library('vendor/ion_auth');
}
```
...seems to fix the issue, but it causes travis to return ```"RuntimeException: Unable to locate the model you have specified: Ion_auth_model"```.  
The order of tests also seems to change whether it will work or not, which seems a bit strange.

The tests I use are basically the same as the ones included in the test repo (https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/v0.9.0/application/tests/controllers/Auth_check_in_construct_test.php), so I'm not sure what's going wrong.

**Comment by kenjis** [comment]
How about like this?

~~~php
public function setUp() {
    $this->resetInstance();
    $this->CI->load->library('vendor/ion_auth');
}
~~~

**Comment by DakuTree** [comment]
Same issue. Tests run fine locally, but fail with ```"RuntimeException: Unable to locate the model you have specified: Ion_auth_model"``` in travis. PHPUnit version is the same and is run from the same location.

Travis Error:
```
1) Login_test::test_index_logged_in
RuntimeException: Unable to locate the model you have specified: Ion_auth_model
/home/travis/build/DakuTree/gemushi2/application/tests/_ci_phpunit_test/replacing/core/Loader.php:316
/home/travis/build/DakuTree/gemushi2/application/libraries/vendor/Ion_auth.php:69
/home/travis/build/DakuTree/gemushi2/application/tests/_ci_phpunit_test/replacing/core/Loader.php:1252
/home/travis/build/DakuTree/gemushi2/application/tests/_ci_phpunit_test/replacing/core/Loader.php:1046
/home/travis/build/DakuTree/gemushi2/application/tests/_ci_phpunit_test/replacing/core/Loader.php:218
/home/travis/build/DakuTree/gemushi2/application/tests/controllers/User/Auth/Login_test.php:6
/home/travis/build/DakuTree/gemushi2/vendor/phpunit/phpunit/phpunit:36
```

**Comment by kenjis** [comment]
Is your filename `Ion_auth_model.php`?

If you get error in only travis, it may be because the case (upper/lower) in your filename is wrong.
It happens if you use case insensitive file system (Mac or Windows) on local.

**Comment by DakuTree** [comment]
That seemed to fix it, thanks :)

Still not sure why the library has to be loaded in the test though, shouldn't the controller be able to handle all the loading?

**Comment by kenjis** [comment]
Yes, the controller should handle the loading.

If you remove the `setUp()` method, what happens?

**Comment by DakuTree** [comment]
Removing setUp() gives the ```"Unable to locate the specified class: Bcrypt.php"``` error.
Strangely this only seems to occur on one of the tests that uses ion_auth. Commenting it out shows another similar test works perfectly fine.

I've uploaded a gist with the controllers & tests which might help find the issue: https://gist.github.com/DakuTree/94e29543d750b9836334

**Comment by kenjis** [comment]
Probably you must load `Ion_auth` in your test code. Because you autoload it before the controller construction in `setCallablePreConstructor()`.

~~~php
$auth = $this->getDouble('Ion_auth', ['logged_in' => TRUE]);
~~~

The above code only autoload (PHP autoloading) `Ion_auth`. So `$this->load->library()` in your controller does not work perfectly.

**Comment by DakuTree** [comment]
I guess I'll just stick with using setUp() then. Thanks for the help.

**Comment by kenjis** [comment]
@DakuTree My explanation was not accurate. 

I'm not sure but the patch below may resolve the error:

~~~
--- a/application/tests/_ci_phpunit_test/CIPHPUnitTestDouble.php
+++ b/application/tests/_ci_phpunit_test/CIPHPUnitTestDouble.php
@@ -38,6 +38,7 @@ class CIPHPUnitTestDouble
        $methods = array_keys($params);
 
        $mock = $this->testCase->getMockBuilder($classname)
+         ->disableOriginalConstructor()
            ->setMethods($methods)->getMock();
 
        foreach ($params as $method => $return)
~~~

**Comment by kenjis** [comment]
@jkudebeh Do you use `$this->request->setCallablePreConstructor()`?

**Comment by DakuTree** [comment]
That patch seems to have fixed the error. Tests seem to run fine without needing to load the library in setUp() now. :smile:

**Comment by kenjis** [comment]
@DakuTree Thank you for your beedback!

Basically, we can't use `$this->load` in `$this->request->setCallablePreConstructor()`, because the *CodeIgniter instance* which we test does not exist yet.

But in your case, when you create the mock object, the constructor of mocked `Ion_auth` class is executed and it calls `$this->load->model('ion_auth_model');` and it calls `$this->load->library('vendor/bcrypt',$params);`.

It causes `Unable to locate the specified class: Bcrypt.php` error, when you create the new controller (= *CodeIgniter instance*).

The `disableOriginalConstructor()` method disables the constructor call when you create the mock object.

I'm going to merge the patch in the next release.

**Comment by jkudebeh** [comment]
this works:  $output = $this->request('GET', 'libraries/Session/Session');
closing issue
