### ISSUE TITLE
config/autoload.php is called 2 times

### ISSUE THREAD

**Issue by PagamosRox** [kenjis/ci-phpunit-test#77]
Hi,

I got a message "Cannot redeclare class class_name" only for controller tests. I think this happens because I'm using "require" for load some libraries on my autoload.php.

After some tests I saw this problem coming from request() method.

It seems that ci-phpunit needs to call autoload again, that's correct?

**Comment by kenjis** [comment]
ci-phpunit-test creates the Controller object when you call `$this->request()`.
Controller objects call `$this->load->initialize()`.
`$this->load->initialize()` loads (`include`) `config/autoload.php`.

Therefore, every time you call `$this->request()`, `config/autoload.php` is loaded.

**Comment by PagamosRox** [comment]
Ok, I will change my implementation on config/autoload.php to fix it!

Still on $this->request(), first parameter is the HTTP method, but if I'm calling a CLI controller, what Should I do? Should I choose one method or have a specific approach? Considering that CLI is not GET nor POST.

Thanks,

**Comment by kenjis** [comment]
If you assume via CLI, use `GET`.
