### ISSUE TITLE
 Use of undefined constant  XXXX- assumed 'XXXX'

### ISSUE THREAD

**Issue by lingfengchencn** [kenjis/ci-phpunit-test#78]
Hi,
  I required "config_dict.php" in my "config.php"  ,it used some constant;

 CI will load "config/constants.php" first,and then load "config.php"

 In unit test ,we will use it in "CIPHPUnitTest.php" line 101 : replcaeHelpers() ;

 so,I got this message :
 
    A PHP Error was encountered

    Severity: NoticeMessage:  Use of undefined constant "XXXX" - assumed 'XXXX'Filename: D:\XXX\apps\config\config_dict.phpLine Number: 7

    Notice: Use of undefined constant XXXX - assumed 'XXXX' in D:\XXXX\apps\config\config_dict.php on line 8

config.php
   
    require_once APPPATH.'config/config_dict.php';

config_dict.php

    $config['sys.role_id'] = array (
	    XXXX     => 'Admin',
    );

**Comment by kenjis** [comment]
Thanks for your report.

How about this?
~~~diff
--- a/application/tests/_ci_phpunit_test/CIPHPUnitTest.php
+++ b/application/tests/_ci_phpunit_test/CIPHPUnitTest.php
@@ -53,8 +53,6 @@ class CIPHPUnitTest
        // Load ci-phpunit-test CI_Loader
        require __DIR__ . '/replacing/core/Loader.php';
 
-       self::replaceHelpers();
-
        // Change current directroy
        chdir(FCPATH);
 
@@ -67,6 +65,8 @@ class CIPHPUnitTest
         */
        require __DIR__ . '/replacing/core/CodeIgniter.php';
 
+     self::replaceHelpers();
+
        // Create CodeIgniter instance
        new CI_Controller();
 
~~~

**Comment by lingfengchencn** [comment]
it's ok;
