### ISSUE TITLE
Create base class for ci-phpunit-test library

### ISSUE THREAD

**Issue by RodolfoSilva** [kenjis/ci-phpunit-test#8]
@kenjis, I was thinking it would be good create a base class for ci-phpunit-test library?

**Comment by kenjis** [comment]
Yes, you're right.

First we have to remove our logic from Bootstrap.php.

**Comment by kenjis** [comment]
I moved code to CIPHPUnitTest class: https://github.com/kenjis/ci-phpunit-test/commit/b52941037ee39a8c6b365e7d3f59d47e0fe0de3f

**Comment by RodolfoSilva** [comment]
Ok, now it's better.
