### ISSUE TITLE
Takes long to run

### ISSUE THREAD

**Issue by Jammyman** [kenjis/ci-phpunit-test#80]
Hi!
Everything seems to be working great, but for some reason, it takes pretty long to complete in my homestead/vagrant box.

Example single test in Codeigniter project (logging removed from phpunit.xml):
Time: 11.97 seconds, Memory: 6.75Mb

One single test with logging:
Time: 16.86 seconds, Memory: 12.50Mb
And building code coverage report takes several minutes.

I have Laravel project on same server and runnig 18 tests take:
Time: 2.5 seconds, Memory: 33.50Mb

Any ideas how I could make it run a bit faster?

**Comment by kenjis** [comment]
If you use monkey patching (default is off), it makes your tests slow.

If you want to make it run faster without changing your app/test code,
there are few things you can do:
* disable Xdebug
* use php7

Or you could skip slow tests using `@group` tag of PHPUnit.

1. add `@group slow` to slow tests
2. add `--exclude-group slow` option to `phpunit`

**Comment by Jammyman** [comment]
Thanks!
Disabling xdebug did it.

I just logged to vm and:
sudo php5dismod xdebug
sudo service php5-fpm restart

After that same test takes:
Time: 3.12 seconds, Memory: 5.75Mb

Keep up the great work! I'm gonna write some tests next :)

**Comment by kenjis** [comment]
Thanks!

Two more for your information:
* In my experience, phpunit 4.7 was much faster than 4.6. So latest phpunit might be faster.
* If you want to get coverage, try with phpdbg. See <https://thephp.cc/news/2015/08/phpunit-4-8-code-coverage-support>. It requires PHPUnit 4.8 and later, but it is much faster than with Xdebug. See <http://blog.remirepo.net/post/2015/11/09/PHPUnit-code-coverage-benchmark>.

**Comment by Jammyman** [comment]
Thanks, 
I try to upgrade phpunit next.
Also phpdbg might come handy if I ever get that far with this 5 years old project :)
