### ISSUE TITLE
CI_Output and JSON

### ISSUE THREAD

**Issue by cigzigwon** [kenjis/ci-phpunit-test#82]
In my app all ajax response data payloads have keys like : "id":"456" but when output is returned in the test case it is "id":456 or in some cases a mix of both. I'm using output like so... and in my controller the original array had strings.

<code>
$output = json_encode($data);
    $length = strlen($output);
    
    $this
      ->output
      ->set_header("Content-length: $length")
      ->set_content_type('application/json')
      ->set_output($output);
</code>
It doesn't make too much sense that the underlying test framework is using `$output = $CI->output->get_output();` but gets different results. After tracing through both CIv3.0.3 and your lib I cannot see what is the problem. Could it be the CLI? and in this case I'm using `$output = $this->request('GET', 'handbook/search');` in the request.

**Comment by kenjis** [comment]
Sorry, I can't get what you exactly say.

> it is "id":456 or in some cases a mix of both.

What do you mean? Would you give me an sample output?

**Comment by cigzigwon** [comment]
at this point I need to check my environment because the web dump of json seems to differ because the cli in another environment has some issue, I believe. I will post the dump after I update the CLI environment. Since I'm running a stable build in prod I'm literally scraping the json endpoint as a basis for expected and of course my cli db is synced

**Comment by cigzigwon** [comment]
Ok, what we have here is @cigzigwon trying to use too many environments... My stub environment was xampp and in that install we get numerically encoded integers instead of strings in a standard ubuntu trusty docker container and I installed php5 and php5-cli and ran the tests and it is passing

good work here @kenjis I think this is a great solution for wanting to cover my public controller methods, I really appreciate and will contribute under issues whenever I run into something like this

**Comment by kenjis** [comment]
Your English is a bit difficult to understand to me, but in my understanding your problem was because of your stub environment, and it is not because of ci-phpunit-test. And you have solved it.

Thanks for your appreciation! If you have issues, feel free to open an issue again.

**Comment by cigzigwon** [comment]
Yes correct. XAMPP 5.6 on Debian does not json_encode() correctly. It is
somehow applying JSON_NUMERIC_CHECK in the CLI environment.
