### ISSUE TITLE
How can I use db transactions to rollback the db for controller tests?

### ISSUE THREAD

**Issue by esetnik** [kenjis/ci-phpunit-test#85]
If I start a transaction in `setup()` and insert a record into the db, then the controller instantiated by `$this->request()` does not have access to that record since it hasn't been committed and they do not share a transaction context. How do I pass the transaction context to $this->request so that it can lookup records  of the open transaction created in `setup()`?

**Comment by kenjis** [comment]
It is a bit difficult. I'm not sure but probably you could manage.

Inject your database object using `$this->request->setCallablePreConstructor()` and `load_class_instance()`
See <https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#inject-mocks-into-controller-constructors>.

But you don't use `$CI->db`, because it will be closed by `reset_instance()` which is called in `$this->request()`: https://github.com/kenjis/ci-phpunit-test/blob/master/application/tests/_ci_phpunit_test/functions.php#L31
Get the database instance directly: https://www.codeigniter.com/user_guide/database/connecting.html#connecting-to-multiple-databases

**Comment by kenjis** [comment]
See https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/4060660ef3df9e44f692b0c4ebcc3a14f3ced6b7/application/tests/controllers/Add_callable_pre_constructor_test.php#L14-L32

**Comment by esetnik** [comment]
Fantastic! I haven't dove into the callables yet but this looks like exactly what i'm after. I'll test that out and report back.

Thanks for all your hard work on this framework. Happy new year!

**Comment by esetnik** [comment]
Provided example using addCallablePreConstructor works perfectly. Thanks! I think this is a common use case @kenjis want me to add some documentation to the wiki? I've implemented it as a `ControllerTestCase` which my controllers subclass, but I think it might be better to use pre_controller and post_controller hooks for db transaction logic. What do you think?

**Comment by kenjis** [comment]
> I've implemented it as a ControllerTestCase which my controllers subclass

What do you mean? Why  is it a controller subclass?

The db transaction logic is just for testing, isn't it? Hooks are only for your application logic, not for test code.

Actually I don't recommend controller tests with db much. I think, in most cases, it is enough to test models with db. And I prefer db fixture (or db seeding), because it is more simple.
If you need to test controllers, you can test them with mocked models. Then you don't need database at all when you test controllers.

I think testing with db transaction to rollback is a technique to speed up database testing.

**Comment by esetnik** [comment]
It's a fair point but sometimes it's necessary to rollback some db state that was changed after making a request to a controller. For example, let's say you had an api with various tests that perform customer registration but you had a unique key constraint on the customer's email. You'd want to rollback your db to the initial state after each controller test to ensure that you could perform the insert customer operation in multiple test cases without dependence on the ordered execution of your tests.

**Comment by kenjis** [comment]
In that case, you can revert the database state using db fixtures. For example, truncate table and insert initial data in `setUp()`. But probably to rollback your db is faster.

One drawback of the way is, you can't use it when you are using transactions in your application code.

**Comment by esetnik** [comment]
I was under the impression that it should work with nested transactions so even if my code under test also uses transactions it should still be able to rollback.

**Comment by esetnik** [comment]
Hi @kenjis i'm having trouble with the latest version of `ci-phpunit-test` with db rollback.

My `TestCase` looks like the following which is a slight modification of the provided example:
```<?php

class TestCase extends CIPHPUnitTestCase
{    
    public function setUp()
  	{
  		$this->resetInstance();
                $CI = $this->CI;
  		$this->db = $CI->load->database('default', TRUE);
  		$this->db->trans_begin();
  		$DB = $this->db;
  		
  		$this->request->setCallablePreConstructor(
  			function () use ($DB) {
  				// Inject db object
  				load_class_instance('db', $DB);
  			}
  		);
  	}
  	public function tearDown()
  	{
  		$this->db->trans_rollback();
  	}
}
```

The problem with the example is that it reuses the $CI instance across tests because there is no call to `resetInstance()` so I get other errors about libraries being loaded more than once, etc. I want to setup transactions such that each test gets a new instance of $CI and a new transaction accompanying. The above code does not produce any errors, but does not actually rollback the transaction. It appears that load_class_instance is not actually injecting the transaction db instance.

**Comment by kenjis** [comment]
@esetnik Do you mean that your code above worked fine, but when you upgraded ci-phpunit-test, you get errors?

**Comment by kenjis** [comment]
> The above code does not produce any errors, but does not actually rollback the transaction. It appears that load_class_instance is not actually injecting the transaction db instance.

`$this->resetInstance()` creates new CI instance, and assing it to `$this->CI`.
So `$CI` is new every test, and `$CI->load->database('default', TRUE)` returns also new db instance.
So transaction does not works.

You must inject the same db instance. How about like this?

1. in `setUpBeforeClass()`, save the current db instance in a static property.
2. Inject it in `setUp()`.

**Comment by kenjis** [comment]
>  I get other errors about libraries being loaded more than once,

I'm not sure, but it may be a bug in ci-phpunit-test.

**Comment by esetnik** [comment]
> $this->resetInstance() creates new CI instance, and assing it to $this->CI.
> So $CI is new every test, and $CI->load->database('default', TRUE) returns also new db instance.
> So transaction does not works.

$CI is new in every test, but the transaction should start before each test and rollback after each test. All I need is for the db used by the code under test to be the same instance of the db returned by `$CI->load->database()` and that `$this->db` can end the transaction after each test.

What I want to happen is.
1. setUp
2. resetInstance
3. start a transaction for that test
4. run the request
5. rollback any changes to the db introduced by that request
6. repeat for next test

**Comment by kenjis** [comment]
1. in `setUpBeforeClass()`, save the current db instance in a static property.
2. Inject it in `setUp()`.

**Comment by kenjis** [comment]
Sorry, my explanation before was wrong.

I added a test case:
https://github.com/kenjis/ci-app-for-ci-phpunit-test/blob/f7d1aebee3c678297c3a3919c3bda7d2ade0bb33/application/tests/controllers/Db_transaction_test.php

And it seems your code has no problem.

> The above code does not produce any errors, but does not actually rollback the transaction. It appears that load_class_instance is not actually injecting the transaction db instance.

I don't know why. My test above passes.

**Comment by esetnik** [comment]
Is there a reason why you call load twice?
```
		$this->CI->load->database();
		$this->db = $this->CI->load->database('default', TRUE);
```

And also, is it possible that it is working with the sqlite db but not with mysql?

**Comment by kenjis** [comment]
You're right. The first line is not needed.

> And also, is it possible that it is working with the sqlite db but not with mysql?

No. If transaction does not work with MySQL, only reason I think is using storage without transaction support. For example, MyIsam.

**Comment by esetnik** [comment]
Yeah I am using InnoDB and transactions do work in tested code, just don't seem to work in the test itself. I thought maybe it was only working with sqlite is the following code i found in `reset_instance()`

```
	// Close db connection
	$CI =& get_instance();
	if (isset($CI->db))
	{
		if (
			$CI->db->dsn !== 'sqlite::memory:'
			&& $CI->db->database !== ':memory:'
		)
		{
			$CI->db->close();
			$CI->db = null;
		}
		else
		{
			// Don't close if SQLite in-memory database
			// If we close it, all tables and stored data will be gone
			load_class_instance('db', $CI->db);
		}
	}
```

**Comment by kenjis** [comment]
@esetnik It is not to close db connection when you use SQLite in-memory database.

I changed the code below, and still tests pass:

~~~diff
--- a/application/tests/_ci_phpunit_test/functions.php
+++ b/application/tests/_ci_phpunit_test/functions.php
@@ -32,20 +32,20 @@ function reset_instance()
        $CI =& get_instance();
        if (isset($CI->db))
        {
-               if (
-                       $CI->db->dsn !== 'sqlite::memory:'
-                       && $CI->db->database !== ':memory:'
-               )
+//             if (
+//                     $CI->db->dsn !== 'sqlite::memory:'
+//                     && $CI->db->database !== ':memory:'
+//             )
                {
                        $CI->db->close();
                        $CI->db = null;
                }
-               else
-               {
-                       // Don't close if SQLite in-memory database
-                       // If we close it, all tables and stored data will be gone
-                       load_class_instance('db', $CI->db);
-               }
+//             else
+//             {
+//                     // Don't close if SQLite in-memory database
+//                     // If we close it, all tables and stored data will be gone
+//                     load_class_instance('db', $CI->db);
+//             }
        }
 
        // Load core classes
~~~

**Comment by NerdsvilleCEO** [comment]
I too seem to be having trouble running
 ``load_class_instance('db', $CI->db);``
Still digging into it but I think for some reason $CI->db is ending up null

**Comment by kenjis** [comment]
If you still have the problem, feel free to reopen or create an issue.
