### ISSUE TITLE
Config values are not reset between tests

### ISSUE THREAD

**Issue by esetnik** [kenjis/ci-phpunit-test#94]
https://github.com/kenjis/ci-app-for-ci-phpunit-test/pull/3

When running tests that set some CI config, the config is not reset back to defaults in subsequent tests. See the failing test case in the attached PR.

**Comment by kenjis** [comment]
Thank you for reporting.

Please try the latest `dev-master`.
https://github.com/kenjis/ci-phpunit-test/commit/57eaac2808d96a1f4ae0fe77d847fafd62c04397

**Comment by esetnik** [comment]
Confirmed working now thanks!
