### ISSUE TITLE
running an individual test

### ISSUE THREAD

**Issue by cjjsjr5656** [kenjis/ci-phpunit-test#97]
I am not able to figure out how to run the tests in a single test case file. I can run all tests with phpunit command.

**Comment by kenjis** [comment]
~~~
$ cd application/tests/
$ phpunit models/Category_model_test.php 
~~~

**Comment by kenjis** [comment]
I've added the explanation: https://github.com/kenjis/ci-phpunit-test#how-to-run-tests

It seems you are not familiar with PHPUnit and/or testing, our book [CodeIgniter Testing Guide](https://leanpub.com/codeigniter-testing-guide) might help you.
