### ISSUE TITLE
NetBeans 8.1, no Use Custom Test Suite checkbox

### ISSUE THREAD

**Issue by cjjsjr5656** [kenjis/ci-phpunit-test#98]
I can run phpunit fine from the command line but would like to run it from NetBeans.

In NetBeans, I go to Project Properties > Testing, but there is no Use Custom Test Suite checkbox. I see an Add Folder button, which can add a folder to Test Directories, and under Testing Providers there is a checkbox for PHPUnit.

I also have installed NetBeans 8.1, PHP 5.6,  PHPUnit  5.2.9, and ci-phpunit-test 11.0 on the Linux client Ubuntu 14.04 LTS.

**Comment by kenjis** [comment]
First, add the `application/tests` folder, and check `PHPUnit`:
![netbeans81-project-testing](https://cloud.githubusercontent.com/assets/87955/13267541/3552651c-dac1-11e5-9635-fca15e776c52.png)

Next, check and configure *Use Custom Test Suite*:
![netbeans81-project-testing-phpunit](https://cloud.githubusercontent.com/assets/87955/13267551/4001a662-dac1-11e5-8c3e-69884625e125.png)

**Comment by kenjis** [comment]
I fixed the instruction: https://github.com/kenjis/ci-phpunit-test/commit/5c09ce3b3da32a7780e141595bde9fb9294391f5
Thank you for your reporting.

**Comment by cjjsjr5656** [comment]
Thx!
