### ISSUE TITLE
Undefined property: CI_Controller::$db

### ISSUE THREAD

**Issue by pascencio** [kenjis/ci-phpunit-test#99]
Hi,

I'm trying to use your project for run my unit tests in **codeigniter 3**. I don't know if the problem is that I'm using an custom model (**MY_Model**), but the firt try to run an unit test and I get this error:

```
Filename:    /var/www/html/myproject/system/core/Model.php
Line Number: 77

Backtrace:
	File: /var/www/html/myproject/application/core/MY_Model.php
	Line: 118
	Function: __get

	File: /var/www/html/myproject/application/third_party/community_auth/models/Auth_model.php
	Line: 23
	Function: __construct

	File: /var/www/html/myproject/application/tests/_ci_phpunit_test/replacing/core/Loader.php
	Line: 355
	Function: __construct

	File: /var/www/html/myproject/application/tests/_ci_phpunit_test/replacing/core/Loader.php
	Line: 246
	Function: model

	File: /var/www/html/myproject/application/tests/_ci_phpunit_test/replacing/core/Loader.php
	Line: 1366
	Function: model

	File: /var/www/html/myproject/application/tests/_ci_phpunit_test/replacing/core/Loader.php
	Line: 157
	Function: _ci_autoloader

	File: /var/www/html/myproject/application/tests/_ci_phpunit_test/CIPHPUnitTest.php
	Line: 93
	Function: __construct

	File: /var/www/html/myproject/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php
	Line: 218
	Function: createCodeIgniterInstance

	File: /var/www/html/myproject/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php
	Line: 137
	Function: callControllerMethod

	File: /var/www/html/myproject/application/tests/_ci_phpunit_test/CIPHPUnitTestCase.php
	Line: 106
	Function: request

	File: /var/www/html/myproject/application/tests/controllers/MyFirst_test.php
	Line: 21
	Function: request

	File: phar:///usr/bin/phpunit/phar/phpunit/Framework/TestCase.php
	Line: 881
	Function: invokeArgs

	File: phar:///usr/bin/phpunit/phar/phpunit/Framework/TestCase.php
	Line: 746
	Function: runTest

	File: phar:///usr/bin/phpunit/phar/phpunit/Framework/TestResult.php
	Line: 601
	Function: runBare

	File: phar:///usr/bin/phpunit/phar/phpunit/Framework/TestCase.php
	Line: 702
	Function: run

	File: phar:///usr/bin/phpunit/phar/phpunit/Framework/TestSuite.php
	Line: 735
	Function: run

	File: phar:///usr/bin/phpunit/phar/phpunit/Framework/TestSuite.php
	Line: 735
	Function: run

	File: phar:///usr/bin/phpunit/phar/phpunit/TextUI/TestRunner.php
	Line: 432
	Function: run

	File: phar:///usr/bin/phpunit/phar/phpunit/TextUI/Command.php
	Line: 148
	Function: doRun

	File: phar:///usr/bin/phpunit/phar/phpunit/TextUI/Command.php
	Line: 100
	Function: run

	File: /usr/bin/phpunit
	Line: 547
	Function: main 
```

Do you any clues or workaround for this error?

Thanks!

**Comment by kenjis** [comment]
It seems your customization (not only MY_Model, but also other MY_***) cause the error. But I don't know what exactly happened.

The error message `Undefined property: CI_Controller::$db` shows CI's database class is not loaded properly. But I don't know why.

**Comment by pascencio** [comment]
Thanks Kenjis, I will look my code. 
Your project have some way to write a log?

**Comment by kenjis** [comment]
No.

**Comment by pascencio** [comment]
Hi Kenji:

I found why the database library was not loaded. In the "library" function (in the file Loader.php)  the argument "library" come with an array and the "database" item is missing.

Do you know why this is happening?

Thanks!
![atom-debug](https://cloud.githubusercontent.com/assets/9783678/13373815/7b146640-dd50-11e5-968a-7debbb848b97.png)

**Comment by kenjis** [comment]
@pascencio The database object is loaded by `CI_Loader::database()`, not `CI_Loader::library()`. So it is no wonder the `$library` has no `database`.

**Comment by pascencio** [comment]
I found the problem, the error was in my class "MY_Loader" because the database loading was doing only one time (If I test my controllers like an REST service they work). I fix that and now I have another problem with my json response in my controller.

```
public function json_response($data) {
        $d = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);

        $this->output
        ->set_status_header(200)
        ->set_content_type('application/json', 'utf-8')
        ->set_output($d)
        ->_display();
        exit;
    }
```
The code above, is used in my controller for return a JSON response.

Thanks in advance!

**Comment by pascencio** [comment]
I fix the problem with a damn `if`.

```
public function json_response($data) {
        $d = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);

        $this->output
        ->set_status_header(200)
        ->set_content_type('application/json', 'utf-8')
        ->set_output($d)
        ->_display();
        if(ENVIRONMENT!='testing') {
          exit;
        }
    }
```
Personally, this don't like me but work.
If you know another approach for this problem, please tell me.
**Thanks for your help! and congratulations because your library is very useful and work perfectly**

**Comment by kenjis** [comment]
@pascencio 

> I found the problem, the error was in my class "MY_Loader" because the database loading was doing only one time (If I test my controllers like an REST service they work).

Do you mean your MY_Loader changed the behavior of the `database()` method?

**Comment by kenjis** [comment]
About `exit()`, I wrote *Monkey Patching* functionality.

See
https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#exit
https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#monkey-patching
https://github.com/kenjis/ci-phpunit-test/blob/master/docs/HowToWriteTests.md#converting-exit-to-exception

Monkey Patching works fine in most cases, but it has negative impact to testing speed.
If you could remove `exit()` in your code, I recommend you do it.
